// app/[locale]/astrology-methodology/page.tsx
import type { Metadata } from "next";

export async function generateMetadata({ params }: { params: { locale: string } }): Promise<Metadata> {
  const isHi = params.locale === "hi";
  return {
    title: isHi ? "ज्योतिष पद्धति | ज्योतिष आशा इंजन का विज्ञान" : "Astrology Methodology | The Science Behind Jyotishasha Engine",
    description: isHi 
      ? "समझें कि ज्योतिष आशा कैसे उच्च-सटीक गणनाओं और वैदिक नियमों का उपयोग करके आपकी कुंडली तैयार करता है।"
      : "Understand how Jyotishasha calculates Kundali using precision computation and Vedic rules.",
  };
}

export default function AstrologyMethodologyPage({ params }: { params: { locale: string } }) {
  const isHi = params.locale === "hi";

  const faqs = [
    {
      q: isHi ? "ज्योतिष आशा ग्रहों की स्थिति की सटीकता कैसे सुनिश्चित करता है?" : "How does Jyotishasha ensure the accuracy of planetary positions?",
      a: isHi 
        ? "ज्योतिष आशा 'Swiss Ephemeris' के माध्यम से ग्रहों के देशांतर (longitudes) की गणना करता है। यह वही उच्च-सटीक मानक है जिसका उपयोग NASA और प्रमुख खगोलीय संस्थान करते हैं।"
        : "Jyotishasha computes planetary longitudes using Swiss Ephemeris. These follow high-precision ephemeris standards referenced by NASA and other leading astronomical institutions."
    },
    {
      q: isHi ? "जन्म स्थान की सटीकता इतनी महत्वपूर्ण क्यों है?" : "Why is birth location precision so important?",
      a: isHi
        ? "वैदिक ज्योतिष में, एक छोटे से स्थान परिवर्तन से लग्न बदल सकता है। हम Google Places API का उपयोग करके सटीक अक्षांश (Latitude) और देशांतर (Longitude) प्राप्त करते हैं।"
        : "In Vedic Astrology, the Ascendant (Lagna) can shift with small location changes. We use Google Places API to fetch exact coordinates for high geographic integrity."
    },
    {
      q: isHi ? "क्या ज्योतिष सामग्री AI द्वारा बनाई गई है?" : "Is the astrology content generated by AI?",
      a: isHi
        ? "नहीं। हमारा सिस्टम नियम-आधारित (Rule-based) है। भविष्यवाणियां केवल तभी दिखाई जाती हैं जब शास्त्रीय वैदिक स्थितियां गणितीय रूप से चार्ट में मौजूद हों।"
        : "No. Jyotishasha uses a deterministic, rule-based system. Insights appear only when classical Vedic conditions are mathematically present in the chart."
    }
  ];

  return (
    <section className="min-h-screen py-12 px-4 text-white bg-gradient-to-b from-[#0f0a1e] to-[#1a1435]">
      <div className="max-w-4xl mx-auto bg-white/5 backdrop-blur-lg rounded-3xl shadow-2xl p-8 border border-indigo-500/20">
        
        {/* Header */}
        <h1 className="text-3xl sm:text-4xl font-black text-indigo-300 mb-4 uppercase tracking-tighter">
          {isHi ? "ज्योतिष पद्धति: ज्योतिष आशा का विज्ञान" : "Methodology: The Science of Jyotishasha"}
        </h1>
        <p className="text-gray-300 text-lg border-b border-white/10 pb-8">
          {isHi 
            ? "खगोलीय गणना, लहिरी अयनांश और शास्त्रीय वैदिक नियमों का एक पारदर्शी विवरण।"
            : "A transparent explanation of ephemeris-based astronomy, Lahiri Ayanamsa, and classical Vedic rules."}
        </p>

        <div className="mt-10 space-y-12">
          
          {/* Vision Section */}
          <div className="space-y-4">
            <h2 className="text-2xl font-bold text-indigo-200">
              {isHi ? "हमारा विजन: ज्योतिष और गणितीय सटीकता" : "Our Vision: Astrology Meets Math"}
            </h2>
            <p className="text-gray-300 leading-relaxed">
              {isHi 
                ? "ज्योतिष आशा में, हम वैदिक ज्योतिष को केवल अनुमान नहीं, बल्कि एक संरचित गणितीय अनुशासन मानते हैं। हमारा इंजन मानव पूर्वाग्रह और मनगढ़ंत भविष्यवाणियों को खत्म करने के लिए बनाया गया है।"
                : "At Jyotishasha, we treat Jyotish as a structured mathematical discipline. Our engine is designed to eliminate human bias and hallucinated predictions."}
            </p>
          </div>

          {/* Precision Data Section */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="p-6 rounded-2xl bg-white/5 border border-white/10">
              <h3 className="text-lg font-bold text-white mb-2 underline decoration-indigo-500">
                {isHi ? "सटीक डेटा मानक" : "Precision Data Standards"}
              </h3>
              <ul className="text-sm text-gray-400 space-y-2 list-disc list-inside">
                <li>Swiss Ephemeris / PyEphem</li>
                <li>Lahiri Ayanamsa (Chitra Paksha)</li>
                <li>Sidereal Zodiac System</li>
                <li>Google Places REST Integration</li>
              </ul>
            </div>
            <div className="p-6 rounded-2xl bg-white/5 border border-white/10">
              <h3 className="text-lg font-bold text-white mb-2 underline decoration-indigo-500">
                {isHi ? "नियम-आधारित इंजन" : "Rule-Based Engine"}
              </h3>
              <ul className="text-sm text-gray-400 space-y-2 list-disc list-inside">
                <li>Deterministic Vedic Logic</li>
                <li>No Random AI Text</li>
                <li>Mathematical Yoga Triggers</li>
                <li>Repeatable Results</li>
              </ul>
            </div>
          </div>

          {/* Dasha & Panchang Section */}
          <div className="space-y-4">
            <h2 className="text-2xl font-bold text-indigo-200">
              {isHi ? "पंचांग और दशा गणना" : "Panchang & Dasha Computation"}
            </h2>
            <p className="text-gray-300 leading-relaxed">
              {isHi 
                ? "विंशोत्तरी दशा की गणना चंद्रमा की सटीक स्थिति पर आधारित होती है। क्योंकि हम उच्च-सटीक डेटा का उपयोग करते हैं, इसलिए हमारी समय-सीमा (timelines) अन्य सामान्य ऐप्स की तुलना में कहीं अधिक सटीक होती हैं।"
                : "Vimshottari Dasha timelines are significantly more accurate because we compute Moon longitude using arc-second level precision instead of approximations."}
            </p>
          </div>

          {/* FAQ Section */}
          <div className="space-y-6 pt-6 border-t border-white/10">
            <h2 className="text-2xl font-bold text-indigo-200 mb-6">
              {isHi ? "तकनीकी प्रश्न (FAQ)" : "Technical FAQ"}
            </h2>
            <div className="space-y-4">
              {faqs.map((f, i) => (
                <details key={i} className="group rounded-2xl bg-white/5 border border-white/10 p-4 transition-all">
                  <summary className="cursor-pointer font-bold text-indigo-100 flex justify-between items-center">
                    {f.q}
                    <span className="text-indigo-500 group-open:rotate-180 transition-transform">↓</span>
                  </summary>
                  <p className="mt-4 text-gray-400 text-sm leading-relaxed border-t border-white/5 pt-4">
                    {f.a}
                  </p>
                </details>
              ))}
            </div>
          </div>

          {/* Privacy Note */}
          <div className="p-6 rounded-2xl bg-indigo-500/10 border border-indigo-500/20 italic text-center">
            <p className="text-indigo-200 text-sm">
              {isHi 
                ? "सटीक जन्म डेटा सफलता की कुंजी है। ज्योतिष आशा आपकी गोपनीयता का सम्मान करता है और आपके डेटा को सुरक्षित रखता है।"
                : "Accurate birth data is key. Jyotishasha respects your privacy and keeps your data secure."}
            </p>
          </div>

        </div>
      </div>
    </section>
  );
}