import type { RetrogradeHubData } from "./types"

export const retrogradeHubData: RetrogradeHubData = {
  faqs: [
    {
      q: `Which planets can go retrograde in Vedic astrology?`,
      q_hi: `वैदिक ज्योतिष में कौन से ग्रह वक्री हो सकते हैं?`,
      a: `Five of the nine Vedic grahas can turn retrograde: Mercury (Budha), Venus (Shukra), Mars (Mangal), Jupiter (Brihaspati), and Saturn (Shani). The Sun never retrogrades — it is a star, not an orbiting planet, and from Earth's perspective it moves steadily eastward through the zodiac all year. The Moon never retrogrades — it orbits Earth directly, not the Sun, so the relative-orbit geometry that creates retrograde simply does not arise for Chandra. Rahu and Ketu are always retrograde by convention, because their continuous westward motion through the zodiac is inherently opposite to the standard eastward direction of most planets.`,
      a_hi: `नौ वैदिक ग्रहों में से पाँच वक्री हो सकते हैं: बुध, शुक्र, मंगल, बृहस्पति और शनि। सूर्य कभी वक्री नहीं होता — यह एक तारा है, परिक्रमा करने वाला ग्रह नहीं। चंद्रमा कभी वक्री नहीं होता — यह सूर्य नहीं, सीधे पृथ्वी की परिक्रमा करता है, इसलिए वक्री गति उत्पन्न करने वाली सापेक्ष-कक्षा ज्यामिति ही नहीं बनती। राहु और केतु परिपाटी के अनुसार सदा वक्री रहते हैं, क्योंकि राशिचक्र में उनकी निरंतर पश्चिमी गति अधिकांश ग्रहों की मानक पूर्वमुखी दिशा के विपरीत है।`,
    },
    {
      q: `Is retrograde always negative in Vedic astrology?`,
      q_hi: `क्या वैदिक ज्योतिष में वक्री हमेशा नकारात्मक होता है?`,
      a: `No. Classical Vedic texts — including Parashara's Brihat Parashara Hora Shastra — classify retrograde planets as balavan, meaning strong in their significations. This is a fundamental distinction from Western popular astrology, which treats retrograde as a period of malfunction. In the Vedic framework, the retrograde condition intensifies and internalizes a planet's qualities rather than weakening them. Whether those intensified qualities produce favorable or challenging outcomes depends on the planet's house, sign dignity, aspects, and the active dasha period in the natal chart — not on the retrograde condition alone.`,
      a_hi: `नहीं। पराशर के बृहत् पाराशर होरा शास्त्र सहित शास्त्रीय वैदिक ग्रंथ वक्री ग्रहों को बलवान — अपने कारकत्व में शक्तिशाली — वर्गीकृत करते हैं। यह पाश्चात्य लोकप्रिय ज्योतिष से मूलभूत अंतर है। वैदिक ढाँचे में वक्री अवस्था किसी ग्रह के गुणों को कमज़ोर नहीं, बल्कि तीव्र और आंतरिक बनाती है। ये तीव्र गुण अनुकूल या चुनौतीपूर्ण परिणाम देते हैं — यह ग्रह की भाव स्थिति, राशि गरिमा, दृष्टियों और सक्रिय दशाकाल पर निर्भर करता है।`,
    },
    {
      q: `How do I find which planets are retrograde in my birth chart?`,
      q_hi: `मुझे कैसे पता चलेगा कि मेरी जन्मकुंडली में कौन से ग्रह वक्री हैं?`,
      a: `In a Vedic natal chart, retrograde planets are typically marked with the letter 'R' next to the planet's symbol, or with the notation 'vakri' depending on the software or chart format. If you generate a free Kundali on Jyotishasha, retrograde planets are clearly indicated. A qualified Vedic astrologer can identify all retrograde planets in your chart and interpret them within the full context of your natal picture — house placement, sign dignity, conjunctions and aspects, and the active Vimshottari dasha period.`,
      a_hi: `वैदिक जन्मकुंडली में, वक्री ग्रह आमतौर पर ग्रह के प्रतीक के बगल में 'R' अक्षर से, या 'वक्री' अंकन से — सॉफ्टवेयर के अनुसार — दर्शाए जाते हैं। ज्योतिष आशा पर मुफ्त कुंडली बनाने पर वक्री ग्रह स्पष्ट रूप से अंकित होते हैं। एक योग्य वैदिक ज्योतिषी आपकी कुंडली में सभी वक्री ग्रहों को पहचान सकते हैं और उन्हें आपकी संपूर्ण जन्मकालीन तस्वीर के संदर्भ में व्याख्यायित कर सकते हैं।`,
    },
    {
      q: `What is the difference between vakri graha in Vedic astrology and retrograde in Western astrology?`,
      q_hi: `वैदिक ज्योतिष में वक्री ग्रह और पाश्चात्य ज्योतिष में रेट्रोग्रेड में क्या अंतर है?`,
      a: `The astronomical phenomenon is identical — both traditions observe the same apparent backward motion of planets. The interpretive differences are substantial. Western popular astrology treats retrograde as a period of disruption, delay, and malfunction in the planet's domain. Vedic astrology treats retrograde planets as balavan (strong) with intensified significations. Vedic interpretation also requires the full natal chart context before drawing any conclusions, rather than applying blanket forecasts based on transit position alone. Additionally, Vedic astrology uses mean nodes for Rahu and Ketu — which are always retrograde — while Western astrology sometimes uses true nodes that can briefly appear direct.`,
      a_hi: `खगोलीय घटना समान है — दोनों परंपराएँ ग्रहों की एक ही आभासी पश्चगामी गति का प्रेक्षण करती हैं। व्याख्यात्मक अंतर महत्त्वपूर्ण हैं। पाश्चात्य लोकप्रिय ज्योतिष वक्री को व्यवधान और खराबी का काल मानता है। वैदिक ज्योतिष वक्री ग्रहों को बलवान और तीव्र कारकत्व वाला मानता है। वैदिक व्याख्या कोई निष्कर्ष निकालने से पहले पूर्ण जन्मकालीन संदर्भ की भी आवश्यकता रखती है। साथ ही, वैदिक ज्योतिष राहु-केतु के लिए मध्यम पात (mean nodes) का उपयोग करता है — जो सदा वक्री हैं।`,
    },
    {
      q: `Why do some planets retrograde more often than others?`,
      q_hi: `कुछ ग्रह दूसरों की तुलना में अधिक बार वक्री क्यों होते हैं?`,
      a: `Retrograde frequency and duration depend directly on each planet's orbital period relative to Earth's. Mercury retrogrades most frequently — three to four times per year — because its short 88-day orbit means it laps Earth frequently, creating multiple inferior conjunctions annually. Venus retrogrades once every 18 months because its 225-day orbit is longer. The outer planets (Mars, Jupiter, Saturn) retrograde when Earth passes between them and the Sun; since Earth laps each of them once per synodic period, they retrograde approximately once per synodic year. The farther a planet is from the Sun, the longer its individual retrograde lasts but the less frequently it occurs.`,
      a_hi: `वक्री आवृत्ति और अवधि प्रत्येक ग्रह की कक्षीय अवधि पर सीधे निर्भर करती है। बुध सबसे अधिक बार — वर्ष में 3–4 बार — वक्री होता है क्योंकि उसकी 88-दिन की कक्षा का अर्थ है कि वह बार-बार पृथ्वी के निकट से गुज़रता है। शुक्र 18 माह में एक बार अपनी 225-दिन की कक्षा के कारण। बाह्य ग्रह (मंगल, बृहस्पति, शनि) तब वक्री होते हैं जब पृथ्वी उनके और सूर्य के बीच से गुज़रती है। सूर्य से जितना दूर ग्रह, उतनी लंबी वक्री अवधि, परंतु उतनी ही कम आवृत्ति।`,
    },
    {
      q: `What does it mean when multiple planets are retrograde at the same time?`,
      q_hi: `जब एक साथ कई ग्रह वक्री हों तो इसका क्या अर्थ है?`,
      a: `Multiple simultaneous retrogrades are astronomically common, particularly when one or more outer planets — which spend a significant portion of the year in retrograde — overlap with an inner planet's shorter retrograde period. From a Vedic perspective, each retrograde planet affects its own domain independently. The combined picture is assessed by looking at which houses all the retrograde planets occupy and rule in the natal chart simultaneously. A period with three or four planets retrograde may create a collective pull toward review and consolidation across multiple life areas, but the personal impact still depends on the individual natal chart. It is not inherently more difficult than a single retrograde.`,
      a_hi: `एक साथ कई वक्री ग्रह खगोलशास्त्रीय रूप से सामान्य हैं — विशेषकर जब एक या अधिक बाह्य ग्रह, जो वर्ष का एक बड़ा हिस्सा वक्री बिताते हैं, किसी आंतरिक ग्रह के संक्षिप्त वक्री काल के साथ ओवरलैप करते हैं। वैदिक दृष्टिकोण से, प्रत्येक वक्री ग्रह अपने क्षेत्र को स्वतंत्र रूप से प्रभावित करता है। संयुक्त तस्वीर यह देखकर आँकी जाती है कि सभी वक्री ग्रह जन्मकुंडली में किन भावों में हैं। यह एकाकी वक्री से अंतर्निहित रूप से अधिक कठिन नहीं है।`,
    },
    {
      q: `Can a retrograde planet also be exalted or in its own sign?`,
      q_hi: `क्या वक्री ग्रह एक साथ उच्च या स्वगृही भी हो सकता है?`,
      a: `Yes. A retrograde planet can simultaneously be exalted (uchcha), in its own sign (svastha), or in any other dignity condition. The retrograde status and the sign dignity are assessed independently and can coexist. Classical texts like Parashara's Brihat Parashara Hora Shastra treat these as separate but additive conditions: a retrograde planet that is also exalted carries both the heightened significations of vakri and the peak dignification of exaltation. Conversely, a retrograde and debilitated planet (neecha) carries both conditions simultaneously. This combination is a key factor in experienced Vedic astrologers' assessment of a planet's overall strength.`,
      a_hi: `हाँ। वक्री ग्रह एक साथ उच्च, स्वगृही, या किसी भी अन्य राशि गरिमा की स्थिति में हो सकता है। वक्री स्थिति और राशि गरिमा को स्वतंत्र रूप से आँका जाता है और वे सह-अस्तित्व में हो सकते हैं। पराशर के शास्त्रीय ग्रंथ इन्हें संयोजक अवस्थाओं के रूप में मानते हैं: वक्री और उच्च ग्रह दोनों अवस्थाओं को एक साथ वहन करता है। अनुभवी वैदिक ज्योतिषी ग्रह की समग्र शक्ति का आकलन करने में इस संयोजन पर विचार करते हैं।`,
    },
    {
      q: `What is a retrograde station and is it significant in Vedic astrology?`,
      q_hi: `वक्री स्टेशन क्या है और क्या यह वैदिक ज्योतिष में महत्त्वपूर्ण है?`,
      a: `A retrograde station is the brief period when a planet appears to slow to a near-stop before changing direction — either beginning its retrograde (retrograde station) or resuming forward motion (direct station). Astronomically, the planet's apparent speed relative to the fixed stars decreases toward zero at these moments before reversing direction. In Vedic astrology, station points are considered particularly potent: the planet lingers at a specific degree of the zodiac longer than usual, intensifying its influence over that degree and any natal chart factors connected to it. Classical texts reference this condition using the term stambhana — standstill.`,
      a_hi: `वक्री स्टेशन वह संक्षिप्त काल है जब कोई ग्रह दिशा बदलने से पहले लगभग रुक जाता प्रतीत होता है — या तो वक्री होते समय (वक्री स्टेशन) या मार्गी होते समय (मार्गी स्टेशन)। खगोलशास्त्र में, इन क्षणों पर स्थिर तारों के सापेक्ष ग्रह की आभासी गति शून्य के निकट होती है। ज्योतिषशास्त्र में स्टेशन बिंदुओं को विशेष रूप से शक्तिशाली माना जाता है — ग्रह सामान्य से अधिक समय तक एक विशेष अंश पर रहता है। शास्त्रीय ग्रंथ इस अवस्था के लिए 'स्तम्भन' (ठहराव) शब्द का उपयोग करते हैं।`,
    },
    {
      q: `Are there genuinely favorable activities during a planet's retrograde?`,
      q_hi: `क्या ग्रह के वक्री काल में वास्तव में अनुकूल गतिविधियाँ होती हैं?`,
      a: `Yes — and Vedic astrology is more direct about this than Western popular retrograde culture. Since classical texts classify retrograde planets as balavan (strong), retrograde periods carry the concentrated, inward energy of the planet's significations. Mercury retrograde is particularly well-suited for research, editing, revision of prior work, and deep analytical thinking. Jupiter retrograde supports philosophical inquiry, spiritual study, and deepening of existing knowledge. Saturn retrograde supports consolidation of structures and addressing overdue responsibilities. The consistent principle: activities calling for the planet's inward, concentrated energy proceed well; activities requiring outward initiation in the planet's domain may meet more friction.`,
      a_hi: `हाँ — और वैदिक ज्योतिष इस बारे में पाश्चात्य लोकप्रिय वक्री संस्कृति से अधिक स्पष्ट है। शास्त्रीय ग्रंथ वक्री ग्रहों को बलवान मानते हैं, इसलिए वक्री काल में ग्रह के कारकत्व की केंद्रित, आंतरिक ऊर्जा होती है। वक्री बुध शोध, संपादन और गहन विश्लेषण के लिए विशेष रूप से उपयुक्त है। वक्री बृहस्पति दार्शनिक जिज्ञासा और विद्या की गहराई का समर्थन करता है। वक्री शनि संरचनाओं को सुदृढ़ करने का समय है। सतत सिद्धांत: ग्रह की आंतरिक, केंद्रित ऊर्जा के साथ संरेखित गतिविधियाँ अच्छी तरह आगे बढ़ती हैं।`,
    },
    {
      q: `Does the duration of a retrograde period affect its astrological significance?`,
      q_hi: `क्या वक्री काल की अवधि उसके ज्योतिषीय महत्त्व को प्रभावित करती है?`,
      a: `Duration affects how long the retrograde influence is sustained, not necessarily how intense it is at any given moment. A longer Saturn retrograde (approximately 135 days) means Saturn's inward, review-oriented energy sustains across a larger portion of the year and may interact with more natal chart factors through its extended transit. A shorter Mercury retrograde (approximately 21 days) is brief but occurs three to four times annually, making Mercury's retrograde energy collectively more frequent. In Vedic astrology, the more decisive factor is the natal chart's sensitivity to the retrograde planet — which house it occupies, which houses it rules, and whether any dasha periods align — rather than the raw duration.`,
      a_hi: `अवधि यह प्रभावित करती है कि वक्री प्रभाव कितने समय तक बना रहता है, न कि किसी भी क्षण यह कितना तीव्र है। लंबा शनि वक्री (~135 दिन) का अर्थ है शनि की समीक्षा-उन्मुख ऊर्जा वर्ष के एक बड़े हिस्से में बनी रहती है। संक्षिप्त बुध वक्री (~21 दिन) वर्ष में 3–4 बार होता है। वैदिक ज्योतिष में अधिक निर्णायक कारक है जन्मकुंडली की वक्री ग्रह के प्रति संवेदनशीलता — वह किस भाव में है, किन भावों का स्वामी है, और कोई दशाकाल संरेखित है या नहीं।`,
    },
  ],
  planetCards: [
    {
      planetSlug: "sun",
      planet: "Sun",
      planet_hi: "सूर्य",
      status: "never-retrograde",
      statusLabel: "Never Retrograde",
      statusLabel_hi: "कभी वक्री नहीं",
      summary: "The Sun is a star, not an orbiting planet. From Earth's perspective it moves steadily eastward through the zodiac all year — the relative-orbit geometry that produces retrograde motion never arises for Surya.",
      summary_hi: "सूर्य एक तारा है, परिक्रमा करने वाला ग्रह नहीं। पृथ्वी के दृष्टिकोण से यह वर्ष भर राशिचक्र में पूर्वमुखी चलता है — वक्री गति उत्पन्न करने वाली सापेक्ष-कक्षा ज्यामिति सूर्य के लिए बनती ही नहीं।",
      icon: "☀️",
      detailSlug: null,
    },
    {
      planetSlug: "moon",
      planet: "Moon",
      planet_hi: "चंद्र",
      status: "never-retrograde",
      statusLabel: "Never Retrograde",
      statusLabel_hi: "कभी वक्री नहीं",
      summary: "The Moon orbits Earth directly, not the Sun, completing one orbit every ~27.3 days. Its motion through the zodiac is always eastward from Earth's perspective. The geometry that creates retrograde simply does not arise for Chandra.",
      summary_hi: "चंद्रमा सूर्य की नहीं, सीधे पृथ्वी की परिक्रमा करता है — ~27.3 दिनों में एक कक्षा। पृथ्वी के दृष्टिकोण से राशिचक्र में इसकी गति सदा पूर्वमुखी है। वक्री गति उत्पन्न करने वाली ज्यामिति चंद्र के लिए उत्पन्न नहीं होती।",
      icon: "🌙",
      detailSlug: null,
    },
    {
      planetSlug: "mars",
      planet: "Mars",
      planet_hi: "मंगल",
      status: "retrograde-capable",
      statusLabel: "Retrograde Capable",
      statusLabel_hi: "वक्री होने में सक्षम",
      summary: "Mars governs drive, courage, property, and conflict. Its retrograde every ~26 months redirects assertive energy inward — often resurging past ambitions, unresolved disputes, or deferred physical goals.",
      summary_hi: "मंगल साहस, ऊर्जा, संपत्ति और संघर्ष का कारक है। ~26 माह में एक बार इसकी वक्री गति आक्रामक ऊर्जा को अंतर्मुखी करती है — प्रायः पुरानी महत्त्वाकांक्षाएँ, अनसुलझे विवाद या स्थगित लक्ष्य उभरते हैं।",
      icon: "♂",
      detailSlug: "retrograde-mars",
      avgDuration: "~60–80 days",
      avgDuration_hi: "~60–80 दिन",
      frequency: "Once every ~26 months",
      frequency_hi: "लगभग 26 माह में एक बार",
    },
    {
      planetSlug: "mercury",
      planet: "Mercury",
      planet_hi: "बुध",
      status: "retrograde-capable",
      statusLabel: "Retrograde Capable",
      statusLabel_hi: "वक्री होने में सक्षम",
      summary: "Mercury governs intellect, speech, trade, and written communication. It retrogrades 3–4 times per year — the most frequent retrograde in the Vedic system — concentrating its analytical energy inward each time.",
      summary_hi: "बुध बुद्धि, वाणी, व्यापार और लिखित संचार का कारक है। वर्ष में 3–4 बार वक्री — वैदिक प्रणाली में सबसे अधिक बार — हर बार इसकी विश्लेषणात्मक ऊर्जा अंतर्मुखी होती है।",
      icon: "☿",
      detailSlug: "retrograde-mercury",
      avgDuration: "~21 days",
      avgDuration_hi: "~21 दिन",
      frequency: "3–4 times per year",
      frequency_hi: "वर्ष में 3–4 बार",
    },
    {
      planetSlug: "jupiter",
      planet: "Jupiter",
      planet_hi: "बृहस्पति",
      status: "retrograde-capable",
      statusLabel: "Retrograde Capable",
      statusLabel_hi: "वक्री होने में सक्षम",
      summary: "Jupiter governs wisdom, dharma, children, and prosperity. Its annual ~120-day retrograde is a sustained period of inward reflection on belief systems, the quality of one's growth, and the alignment between knowledge and action.",
      summary_hi: "बृहस्पति ज्ञान, धर्म, संतान और समृद्धि का कारक है। इसका वार्षिक ~120 दिन का वक्री काल विश्वास प्रणालियों और विकास की गुणवत्ता पर गहन आत्म-चिंतन का दीर्घकालीन अवसर है।",
      icon: "♃",
      detailSlug: "retrograde-jupiter",
      avgDuration: "~120 days",
      avgDuration_hi: "~120 दिन",
      frequency: "Once per year",
      frequency_hi: "वर्ष में एक बार",
    },
    {
      planetSlug: "venus",
      planet: "Venus",
      planet_hi: "शुक्र",
      status: "retrograde-capable",
      statusLabel: "Retrograde Capable",
      statusLabel_hi: "वक्री होने में सक्षम",
      summary: "Venus governs relationships, beauty, the arts, and material comfort. Retrograding once every ~18 months for ~40 days, Venus retrograde frequently resurfaces past partnerships and prompts genuine reassessment of present values.",
      summary_hi: "शुक्र रिश्तों, सौंदर्य, कलाओं और भौतिक सुख का कारक है। ~18 माह में एक बार ~40 दिन के लिए वक्री — शुक्र वक्री प्रायः पुरानी साझेदारियाँ वापस लाता है और वर्तमान मूल्यों का पुनर्मूल्यांकन करवाता है।",
      icon: "♀",
      detailSlug: "retrograde-venus",
      avgDuration: "~40 days",
      avgDuration_hi: "~40 दिन",
      frequency: "Once every ~18 months",
      frequency_hi: "लगभग 18 माह में एक बार",
    },
    {
      planetSlug: "saturn",
      planet: "Saturn",
      planet_hi: "शनि",
      status: "retrograde-capable",
      statusLabel: "Retrograde Capable",
      statusLabel_hi: "वक्री होने में सक्षम",
      summary: "Saturn governs discipline, longevity, service, and karmic accountability. Its annual ~135-day retrograde is associated with the return of unresolved structural issues and a deepening review of long-term obligations.",
      summary_hi: "शनि अनुशासन, दीर्घायु, सेवा और कार्मिक उत्तरदायित्व का कारक है। इसका वार्षिक ~135 दिन का वक्री काल अनसुलझी संरचनात्मक समस्याओं की वापसी और दीर्घकालिक दायित्वों की गहन समीक्षा से जुड़ा है।",
      icon: "♄",
      detailSlug: "retrograde-saturn",
      avgDuration: "~135 days",
      avgDuration_hi: "~135 दिन",
      frequency: "Once per year",
      frequency_hi: "वर्ष में एक बार",
    },
    {
      planetSlug: "rahu",
      planet: "Rahu",
      planet_hi: "राहु",
      status: "always-apparent-retrograde",
      statusLabel: "Always Apparent Retrograde",
      statusLabel_hi: "सदा वक्री (आभासी)",
      summary: "Rahu is the North Lunar Node — a mathematical intersection point, not a physical body. Its continuous westward motion through the zodiac (nodal precession) makes it always vakri by convention. Rahu completes one nodal cycle in approximately 18.6 years.",
      summary_hi: "राहु उत्तर चंद्र पात है — एक गणितीय बिंदु, भौतिक पिंड नहीं। राशिचक्र में इसकी निरंतर पश्चिमी गति (पात-अग्रगमन) इसे परिपाटी के अनुसार सदा वक्री बनाती है। राहु ~18.6 वर्षों में एक पात-चक्र पूरा करता है।",
      icon: "☊",
      detailSlug: null,
    },
    {
      planetSlug: "ketu",
      planet: "Ketu",
      planet_hi: "केतु",
      status: "always-apparent-retrograde",
      statusLabel: "Always Apparent Retrograde",
      statusLabel_hi: "सदा वक्री (आभासी)",
      summary: "Ketu is the South Lunar Node, always 180° opposite Rahu. Like Rahu, it is a mathematical intersection point perpetually retrograde by the mechanics of nodal precession. Ketu represents accumulated past-life karma and the drive toward renunciation.",
      summary_hi: "केतु दक्षिण चंद्र पात है, सदा राहु से 180° विपरीत। राहु की तरह, यह एक गणितीय बिंदु है जो पात-अग्रगमन की यांत्रिकी से सदा वक्री है। केतु संचित पूर्वजन्म कर्म और वैराग्य की ओर प्रेरणा का प्रतिनिधित्व करता है।",
      icon: "☋",
      detailSlug: null,
    },
  ],
}
