import type { DomainTopic } from '@/lib/domains/_shared/domain-topic.types'

export const compatibility: DomainTopic = {

  identity: {
    id:         'marriage-astrology:compatibility',
    slug:       'compatibility',
    title:      'Compatibility in Vedic Astrology: Complete Guide',
    title_hi:   'वैदिक ज्योतिष में अनुकूलता',
    domain:     'astrology',
    subdomain:  'marriage-astrology',
    category:   'marriage',
    entityType: 'concept',
    status:     'draft',
  },

  routing: {
    canonicalPath: '/marriage-astrology/compatibility',
    breadcrumbs: [
      { label: 'Home',               label_hi: 'होम',            href: '/' },
      { label: 'Marriage Astrology', label_hi: 'विवाह ज्योतिष', href: '/marriage-astrology' },
      { label: 'Compatibility',      label_hi: 'अनुकूलता',       href: '/marriage-astrology/compatibility' },
    ],
  },

  seo: {
    metaTitle:       'Compatibility in Vedic Astrology: Complete Guide',
    metaDescription: 'Explore Vedic compatibility through Kundli matching, Ashtakoota, Navamsa, and Dasha cycles — a complete guide to karmic alignment and marital harmony.',
    robots:          'noindex,follow',
  },

  hero: {
    headline:    'Compatibility in Vedic Astrology: Your Karmic Blueprint',
    headline_hi: 'वैदिक ज्योतिष में अनुकूलता: आपका कार्मिक खाका',
    subtext:     'Vedic astrology evaluates compatibility through Kundli matching, Ashtakoota analysis, planetary karakas, and the Navamsa chart — helping you understand the karmic alignment, shared values, and long-term potential of your partnership.',
    subtext_hi:  'वैदिक ज्योतिष कुंडली मिलान, अष्टकूट विश्लेषण, ग्रह कारकों और नवांश चार्ट के माध्यम से अनुकूलता का मूल्यांकन करता है — आपको अपनी साझेदारी के कार्मिक संरेखण, साझे मूल्यों और दीर्घकालिक क्षमता को समझने में सहायता करता है।',
  },

  taxonomy: {
    tags:        ['compatibility', 'vedic-astrology', 'kundli-matching', 'ashtakoota', 'guna-milan', 'navamsa', 'mangal-dosha', 'marriage'],
    keywords:    ['compatibility vedic astrology', 'kundli matching', 'ashtakoota compatibility', 'guna milan', 'navamsa compatibility', 'marriage compatibility astrology', 'vedic astrology compatibility'],
    keywords_hi: ['वैदिक ज्योतिष में अनुकूलता', 'कुंडली मिलान', 'अष्टकूट मिलान', 'गुण मिलान'],
    hubPriority: 'featured',
  },

  content: {
    contentTemplate: 'concept',
    contentBlocks: [
      {
        id:       'introduction',
        title:    'Introduction',
        title_hi: 'परिचय',
        layout:   'list',
        items: [
          {
            id:       'karmic-union',
            label:    'Compatibility as Karmic Assessment',
            label_hi: 'कार्मिक मूल्यांकन के रूप में अनुकूलता',
            body:     'Vedic astrology, or Jyotisha Vedanga, is a profound system designed to understand the karmic blueprints of human life. Marriage is considered one of the most significant Samskaras (sacraments) — a profound karmic union rooted in Rina-anubandha, the debts and bonds carried forward from previous lifetimes. Evaluating compatibility is not merely about checking scores; it is about assessing the karmic alignment and potential harmony between two souls. Compatibility in Jyotisha is the assessment of energetic resonance and karmic synergy between two individuals — a holistic evaluation of temperaments, values, life goals, and potential for shared growth, encompassing emotional, physical, financial, and spiritual alignment.',
            body_hi:  'वैदिक ज्योतिष, या ज्योतिषा वेदांग, मानव जीवन के कार्मिक खाकों को समझने के लिए डिज़ाइन की गई एक गहन प्रणाली है। विवाह को सबसे महत्वपूर्ण संस्कारों में से एक माना जाता है — एक गहन कार्मिक मिलन जो ऋण-अनुबंध में निहित है। अनुकूलता का मूल्यांकन करना केवल अंक जांचना नहीं है; यह दो आत्माओं के बीच कार्मिक संरेखण और संभावित सद्भाव का आकलन करना है। ज्योतिषा में अनुकूलता दो व्यक्तियों के बीच ऊर्जावान अनुनाद और कार्मिक तालमेल का आकलन है।',
          },
          {
            id:       'why-it-matters',
            label:    'Why Compatibility Analysis Matters',
            label_hi: 'अनुकूलता विश्लेषण क्यों महत्वपूर्ण है',
            body:     'Analyzing compatibility is essential for informed preparation and conscious navigation of a relationship. It allows individuals to understand their specific karmic requirements in a partner, identify the nature of potential challenges early, fostering maturity, navigate periods of friction using transit and Dasha analysis rather than reacting impulsively, and appreciate the partner as a catalyst for their own spiritual growth rather than a source of frustration.',
            body_hi:  'अनुकूलता का विश्लेषण एक रिश्ते की सूचित तैयारी और सचेत नेविगेशन के लिए आवश्यक है। यह व्यक्तियों को साथी में उनकी विशिष्ट कार्मिक आवश्यकताओं को समझने, संभावित चुनौतियों की प्रकृति को जल्दी पहचानने, गोचर और दशा विश्लेषण का उपयोग करके घर्षण की अवधियों को नेविगेट करने, और साथी को अपनी आध्यात्मिक वृद्धि के लिए एक उत्प्रेरक के रूप में सराहने में सक्षम बनाता है।',
          },
          {
            id:       'promise-vs-reality',
            label:    'Astrological Promise vs. Reality',
            label_hi: 'ज्योतिषीय वादा बनाम वास्तविकता',
            body:     'A foundational pillar of Jyotisha is the distinction between the "promise" of the birth chart (potential) and the actual manifestation (probability). The birth chart delineates the potential for harmony or conflict. However, the timing, intensity, and specific manner of manifestation are governed by Vimshottari Dasha and Gochar (ongoing transits). Marriage is the union of two charts; therefore, the promise in one chart is significantly modulated by the interacting energy of the partner\'s chart. Human free will, exercised with maturity and awareness, acts as a significant modifier.',
            body_hi:  'ज्योतिषा का एक मूलभूत स्तंभ जन्म कुंडली के "वादे" (क्षमता) और वास्तविक अभिव्यक्ति (संभावना) के बीच का अंतर है। जन्म कुंडली सद्भाव या संघर्ष की क्षमता को रेखांकित करती है। हालांकि, अभिव्यक्ति का समय, तीव्रता और विशिष्ट तरीका विमशोत्तरी दशा और गोचर द्वारा शासित होता है। विवाह दो कुंडलियों का मिलन है; इसलिए एक कुंडली का वादा साथी की कुंडली की परस्पर क्रिया करने वाली ऊर्जा द्वारा महत्वपूर्ण रूप से संशोधित होता है।',
          },
        ],
      },
      {
        id:       'kundli-matching-system',
        title:    'Kundli Matching and Ashtakoota System',
        title_hi: 'कुंडली मिलान और अष्टकूट प्रणाली',
        layout:   'accordion',
        items: [
          {
            id:       'kundli-overview',
            label:    'Kundli Matching Overview',
            label_hi: 'कुंडली मिलान अवलोकन',
            body:     'Kundli matching is a multi-layered process. While Guna Milan is the most commonly known aspect, authoritative analysis requires evaluating the structural integrity of both charts, the interaction of planetary energies, and the alignment of life paths. The matching system provides a framework, not a formula — it is the starting point for a deeper investigation into shared karmic potential.',
            body_hi:  'कुंडली मिलान एक बहु-स्तरीय प्रक्रिया है। जबकि गुण मिलान सबसे अधिक जाना जाने वाला पहलू है, आधिकारिक विश्लेषण के लिए दोनों कुंडलियों की संरचनात्मक अखंडता, ग्रहीय ऊर्जाओं की परस्पर क्रिया और जीवन पथों के संरेखण का मूल्यांकन करना आवश्यक है। मिलान प्रणाली एक सूत्र नहीं, एक ढांचा प्रदान करती है।',
          },
          {
            id:       'ashtakoota',
            label:    'Ashtakoota System',
            label_hi: 'अष्टकूट प्रणाली',
            body:     'The Ashtakoota system evaluates compatibility across eight specific parameters, providing a systematic approach to assessing the quality of the union. Each of the eight Kootas carries a specific weight and examines a distinct dimension of compatibility — from physical harmony and emotional resonance to social alignment and spiritual potential.',
            body_hi:  'अष्टकूट प्रणाली आठ विशिष्ट मापदंडों पर अनुकूलता का मूल्यांकन करती है, जो मिलन की गुणवत्ता का आकलन करने के लिए एक व्यवस्थित दृष्टिकोण प्रदान करती है। आठ कूटों में से प्रत्येक एक विशिष्ट भार वहन करता है और अनुकूलता के एक अलग आयाम की जांच करता है।',
          },
          {
            id:       'guna-milan',
            label:    'Guna Milan',
            label_hi: 'गुण मिलान',
            body:     'Guna Milan is the point-based system of Ashtakoota. It provides a quantitative measure of compatibility out of a maximum of 36 points. However, in classical Jyotisha, this is only the starting point, not the definitive answer. A high score does not guarantee a successful marriage, nor does a low score automatically indicate failure — the structural analysis of both charts always takes precedence.',
            body_hi:  'गुण मिलान अष्टकूट की बिंदु-आधारित प्रणाली है। यह 36 के अधिकतम अंकों में से अनुकूलता का एक मात्रात्मक माप प्रदान करता है। हालांकि, शास्त्रीय ज्योतिषा में, यह केवल शुरुआती बिंदु है, अंतिम उत्तर नहीं। उच्च अंक सफल विवाह की गारंटी नहीं देते, और न ही कम अंक स्वतः विफलता का संकेत देते हैं।',
          },
          {
            id:       'mangal-dosha',
            label:    'Mangal Dosha Compatibility',
            label_hi: 'मंगल दोष अनुकूलता',
            body:     'Mangal Dosha indicates a specific intensity and temperament, particularly regarding energy, passion, and conflict management. Compatibility analysis assesses how the two partners\' Mars energies interact, ensuring one does not overwhelm the other, but rather supports healthy, balanced expression within the partnership.',
            body_hi:  'मंगल दोष एक विशिष्ट तीव्रता और स्वभाव को इंगित करता है, विशेष रूप से ऊर्जा, जुनून और संघर्ष प्रबंधन के संबंध में। अनुकूलता विश्लेषण यह आकलन करता है कि दो साझेदारों की मंगल ऊर्जाएं कैसे परस्पर क्रिया करती हैं, यह सुनिश्चित करते हुए कि एक दूसरे को अभिभूत न करे, बल्कि स्वस्थ, संतुलित अभिव्यक्ति का समर्थन करे।',
          },
          {
            id:       'bhakoot-dosha',
            label:    'Bhakoot Dosha',
            label_hi: 'भकूट दोष',
            body:     'Bhakoot relates to the relative positioning of the Moon signs of the two partners. It indicates the potential for emotional and life-path alignment. Certain relative positions can create friction in the flow of shared life goals, but these effects are frequently modified or cancelled by other positive factors in the charts — particularly a strong Navamsa or benefic 7th house placements.',
            body_hi:  'भकूट दो साझेदारों की चंद्र राशियों की सापेक्ष स्थिति से संबंधित है। यह भावनात्मक और जीवन-पथ संरेखण की क्षमता को इंगित करता है। कुछ सापेक्ष स्थितियां साझे जीवन लक्ष्यों के प्रवाह में घर्षण पैदा कर सकती हैं, लेकिन ये प्रभाव अक्सर कुंडली के अन्य सकारात्मक कारकों द्वारा संशोधित या रद्द किए जाते हैं।',
          },
          {
            id:       'nadi-dosha',
            label:    'Nadi Dosha',
            label_hi: 'नाड़ी दोष',
            body:     'Nadi relates to the constitution and elemental balance of the two individuals. It is considered important for health and procreative potential, and carries the highest weight in the Ashtakoota system. Nadi Dosha is significant, but it is also subject to many classical exceptions (Dosha Parihara) — a thorough reading always considers these cancellation rules before forming conclusions.',
            body_hi:  'नाड़ी दो व्यक्तियों की संरचना और तात्विक संतुलन से संबंधित है। यह स्वास्थ्य और प्रजनन क्षमता के लिए महत्वपूर्ण माना जाता है, और अष्टकूट प्रणाली में सबसे अधिक भार वहन करता है। नाड़ी दोष महत्वपूर्ण है, लेकिन यह कई शास्त्रीय अपवादों (दोष परिहार) के अधीन भी है।',
          },
          {
            id:       'yoni-matching',
            label:    'Yoni Matching',
            label_hi: 'योनि मिलान',
            body:     'Yoni matching relates to the primal nature and compatibility of instincts as revealed by the Nakshatra of the Moon. It impacts the physical and emotional harmony of the couple, indicating how naturally the two individuals\' fundamental temperaments align at the most instinctive level of the relationship.',
            body_hi:  'योनि मिलान चंद्रमा के नक्षत्र द्वारा प्रकट प्रवृत्तियों की आदिम प्रकृति और अनुकूलता से संबंधित है। यह जोड़े के शारीरिक और भावनात्मक सद्भाव को प्रभावित करता है, यह इंगित करता है कि दोनों व्यक्तियों के मौलिक स्वभाव रिश्ते के सबसे सहज स्तर पर कितनी स्वाभाविक रूप से संरेखित होते हैं।',
          },
          {
            id:       'graha-maitri',
            label:    'Graha Maitri',
            label_hi: 'ग्रह मैत्री',
            body:     'Graha Maitri assesses the natural, temporary, and compound friendship between the planetary lords of the Moon signs of the two individuals. It is crucial for understanding the foundational mental compatibility — whether the two minds naturally incline toward mutual respect, cooperation, and intellectual resonance, or require conscious effort to bridge the gap.',
            body_hi:  'ग्रह मैत्री दो व्यक्तियों की चंद्र राशियों के ग्रह स्वामियों के बीच प्राकृतिक, अस्थायी और यौगिक मित्रता का आकलन करती है। यह मूलभूत मानसिक अनुकूलता को समझने के लिए महत्वपूर्ण है — क्या दोनों मन स्वाभाविक रूप से पारस्परिक सम्मान, सहयोग और बौद्धिक अनुनाद की ओर झुकते हैं।',
          },
          {
            id:       'tara-matching',
            label:    'Tara Matching',
            label_hi: 'तारा मिलान',
            body:     'Tara matching assesses compatibility based on the Nakshatras of the individuals, focusing on health, longevity, and overall well-being of the partnership. A favorable Tara indicates that the couple\'s combined Nakshatra energies support mutual vitality and the endurance of the bond through time.',
            body_hi:  'तारा मिलान व्यक्तियों के नक्षत्रों के आधार पर अनुकूलता का आकलन करती है, साझेदारी के स्वास्थ्य, दीर्घायु और समग्र कल्याण पर ध्यान केंद्रित करती है। एक अनुकूल तारा इंगित करती है कि जोड़े की संयुक्त नक्षत्र ऊर्जाएं पारस्परिक जीवन शक्ति और बंधन की स्थायित्व का समर्थन करती हैं।',
          },
          {
            id:       'mahendra-stree',
            label:    'Mahendra and Stree Deergha',
            label_hi: 'महेंद्र और स्त्री दीर्घ',
            body:     'Mahendra promotes prosperity and longevity of the union by assessing the energetic support between the two Nakshatras, while Stree Deergha is associated with the longevity of the partner and the stability of the family structure. Together they address the durability and material foundation of the shared life.',
            body_hi:  'महेंद्र दो नक्षत्रों के बीच ऊर्जावान समर्थन का आकलन करके मिलन की समृद्धि और दीर्घायु को बढ़ावा देता है, जबकि स्त्री दीर्घ साथी की दीर्घायु और पारिवारिक संरचना की स्थिरता से जुड़ा है। साथ मिलकर वे साझे जीवन की स्थायित्व और भौतिक नींव को संबोधित करते हैं।',
          },
        ],
      },
      {
        id:       'key-house-analysis',
        title:    'Key House Analysis for Compatibility',
        title_hi: 'अनुकूलता के लिए मुख्य भाव विश्लेषण',
        layout:   'accordion',
        items: [
          {
            id:       'first-house',
            label:    'The 1st House',
            label_hi: 'प्रथम भाव',
            body:     'The 1st House represents the individuals themselves and their fundamental self-expression. In compatibility analysis, comparing the Lagna (Ascendant) and Lagna lords of both charts reveals how naturally the two individuals\' core identities and self-presentation styles relate to each other.',
            body_hi:  'प्रथम भाव व्यक्तियों और उनकी मूलभूत आत्म-अभिव्यक्ति का प्रतिनिधित्व करता है। अनुकूलता विश्लेषण में, दोनों कुंडलियों के लग्न और लग्न स्वामियों की तुलना बताती है कि दोनों व्यक्तियों की मूल पहचान और आत्म-प्रस्तुति शैलियां कितनी स्वाभाविक रूप से एक-दूसरे से संबंधित हैं।',
          },
          {
            id:       'second-house',
            label:    'The 2nd House',
            label_hi: 'द्वितीय भाव',
            body:     'The 2nd House governs family roots, shared resources, and the financial foundation of the marriage. Its strength and compatibility between the two charts indicates how well the couple will build and steward their material life together, and how naturally they integrate into each other\'s family traditions.',
            body_hi:  'द्वितीय भाव पारिवारिक जड़ों, साझा संसाधनों और विवाह की वित्तीय नींव को नियंत्रित करता है। दोनों कुंडलियों के बीच इसकी शक्ति और अनुकूलता दर्शाती है कि जोड़ा मिलकर अपना भौतिक जीवन कितनी अच्छी तरह बनाएगा और एक-दूसरे की पारिवारिक परंपराओं में कैसे एकीकृत होगा।',
          },
          {
            id:       'fourth-house',
            label:    'The 4th House',
            label_hi: 'चतुर्थ भाव',
            body:     'The 4th House reveals the domestic foundation and the emotional quality of the home environment. In compatibility analysis, the 4th house interaction between charts determines how well the couple creates a shared sanctuary — whether the home becomes a genuine place of emotional security or a source of ongoing tension.',
            body_hi:  'चतुर्थ भाव घरेलू नींव और घर के वातावरण की भावनात्मक गुणवत्ता को प्रकट करता है। अनुकूलता विश्लेषण में, कुंडलियों के बीच चतुर्थ भाव की परस्पर क्रिया यह निर्धारित करती है कि जोड़ा एक साझा आश्रय कितनी अच्छी तरह बनाता है।',
          },
          {
            id:       'fifth-house',
            label:    'The 5th House',
            label_hi: 'पंचम भाव',
            body:     'The 5th House governs shared joy, creativity, romance, and children. Strong 5th house connections between two charts indicate a relationship rich in spontaneity, shared creative expression, and the capacity for genuine romantic warmth that sustains the bond beyond the initial attraction.',
            body_hi:  'पंचम भाव साझी खुशी, रचनात्मकता, रोमांस और बच्चों को नियंत्रित करता है। दो कुंडलियों के बीच मजबूत पंचम भाव संबंध ऐसे रिश्ते को इंगित करते हैं जो स्वतःस्फूर्तता, साझी रचनात्मक अभिव्यक्ति और वास्तविक रोमांटिक गर्मजोशी की क्षमता से समृद्ध है।',
          },
          {
            id:       'seventh-house',
            label:    'The 7th House',
            label_hi: 'सप्तम भाव',
            body:     'The 7th House is the primary house of marriage and partnership. The sign, planets, and lord of the 7th house in each chart — and how they interact with the partner\'s chart — form the core of compatibility analysis. This house defines the fundamental nature of each person\'s expectation of and approach to partnership.',
            body_hi:  'सप्तम भाव विवाह और साझेदारी का प्राथमिक भाव है। प्रत्येक कुंडली में सप्तम भाव की राशि, ग्रह और स्वामी — और वे साथी की कुंडली के साथ कैसे परस्पर क्रिया करते हैं — अनुकूलता विश्लेषण का मूल बनाते हैं।',
          },
          {
            id:       'eighth-house',
            label:    'The 8th House',
            label_hi: 'अष्टम भाव',
            body:     'The 8th House governs intensity, transformation, and the couple\'s shared vulnerabilities. Its interaction between charts reveals how the two individuals navigate crisis, handle shared resources, and approach the deeper, more hidden dimensions of intimacy. A strong 8th house exchange indicates capacity for profound bonding under pressure.',
            body_hi:  'अष्टम भाव तीव्रता, परिवर्तन और जोड़े की साझी कमजोरियों को नियंत्रित करता है। कुंडलियों के बीच इसकी परस्पर क्रिया बताती है कि दोनों व्यक्ति संकट को कैसे नेविगेट करते हैं, साझा संसाधनों को कैसे संभालते हैं, और अंतरंगता के गहरे आयामों तक कैसे पहुंचते हैं।',
          },
          {
            id:       'eleventh-house',
            label:    'The 11th House',
            label_hi: 'एकादश भाव',
            body:     'The 11th House indicates shared aspirations and social orientation. Its compatibility between charts shows how well the couple functions in their larger community, whether they support each other\'s long-term goals, and whether their social networks and ambitions naturally reinforce or conflict with each other.',
            body_hi:  'एकादश भाव साझी आकांक्षाओं और सामाजिक अभिविन्यास को इंगित करता है। कुंडलियों के बीच इसकी अनुकूलता दर्शाती है कि जोड़ा अपने बड़े समुदाय में कितनी अच्छी तरह कार्य करता है, और क्या उनके सामाजिक नेटवर्क और महत्वाकांक्षाएं स्वाभाविक रूप से एक-दूसरे को मजबूत करती हैं।',
          },
          {
            id:       'twelfth-house',
            label:    'The 12th House',
            label_hi: 'द्वादश भाव',
            body:     'The 12th House highlights the potential for spiritual detachment and sacrifice within the relationship. Its engagement between charts can indicate a partnership whose deepest dimension is spiritual companionship — or one where unspoken losses and hidden costs gradually accumulate if not consciously acknowledged and addressed.',
            body_hi:  'द्वादश भाव रिश्ते के भीतर आध्यात्मिक वैराग्य और त्याग की क्षमता को उजागर करता है। कुंडलियों के बीच इसकी भागीदारी ऐसी साझेदारी का संकेत दे सकती है जिसका सबसे गहरा आयाम आध्यात्मिक साहचर्य है।',
          },
        ],
      },
      {
        id:       'planetary-influences',
        title:    'Planetary Influences and Karaka Analysis',
        title_hi: 'ग्रहीय प्रभाव और कारक विश्लेषण',
        layout:   'accordion',
        items: [
          {
            id:       'sun',
            label:    'Sun',
            label_hi: 'सूर्य',
            body:     'The Sun in compatibility analysis represents authority, integrity, and ego. When both partners\' Suns are harmoniously placed relative to each other, it creates mutual respect and shared dignity. If poorly aligned, there may be a persistent battle of wills — each person\'s need for recognition clashing with the other\'s.',
            body_hi:  'अनुकूलता विश्लेषण में सूर्य अधिकार, ईमानदारी और अहंकार का प्रतिनिधित्व करता है। जब दोनों साझेदारों के सूर्य एक-दूसरे के सापेक्ष सामंजस्यपूर्ण रूप से स्थित होते हैं, तो यह पारस्परिक सम्मान और साझी गरिमा बनाता है। यदि खराब तरीके से संरेखित हो, तो इच्छाशक्ति की लगातार लड़ाई हो सकती है।',
          },
          {
            id:       'moon',
            label:    'Moon',
            label_hi: 'चंद्रमा',
            body:     'The Moon governs emotional connectivity and nurturing capacity. Moon compatibility is among the most important factors in any partnership, as it determines the ease of emotional communication, how naturally the partners soothe each other, and the baseline rhythm of domestic life that both experience as home.',
            body_hi:  'चंद्रमा भावनात्मक संपर्क और पोषण क्षमता को नियंत्रित करता है। चंद्रमा अनुकूलता किसी भी साझेदारी में सबसे महत्वपूर्ण कारकों में से एक है, क्योंकि यह भावनात्मक संचार की आसानी, साझेदार कितनी स्वाभाविक रूप से एक-दूसरे को सांत्वना देते हैं, निर्धारित करती है।',
          },
          {
            id:       'mars',
            label:    'Mars',
            label_hi: 'मंगल',
            body:     'Mars brings passion and courage into the relationship, and its cross-chart interaction determines the quality of shared drive and conflict management. Compatible Mars energies amplify each other into productive action; incompatible Mars placements create persistent friction around assertion, pace, and decision-making.',
            body_hi:  'मंगल रिश्ते में जुनून और साहस लाता है, और इसकी क्रॉस-चार्ट परस्पर क्रिया साझी प्रेरणा और संघर्ष प्रबंधन की गुणवत्ता निर्धारित करती है। संगत मंगल ऊर्जाएं एक-दूसरे को उत्पादक क्रिया में बढ़ाती हैं; असंगत मंगल स्थितियां दृढ़ता, गति और निर्णय लेने के आसपास लगातार घर्षण पैदा करती हैं।',
          },
          {
            id:       'mercury',
            label:    'Mercury',
            label_hi: 'बुध',
            body:     'Mercury governs intellectual communication and adaptability. In compatibility, Mercury\'s cross-chart relationship determines whether the couple can think together and problem-solve as a team — or whether their communication styles create a persistent sense of being misunderstood or intellectually undervalued.',
            body_hi:  'बुध बौद्धिक संचार और अनुकूलनशीलता को नियंत्रित करता है। अनुकूलता में, बुध की क्रॉस-चार्ट संबंध यह निर्धारित करता है कि क्या जोड़ा एक साथ सोच सकता है और एक टीम के रूप में समस्या हल कर सकता है — या क्या उनकी संचार शैलियां गलत समझे जाने की भावना पैदा करती हैं।',
          },
          {
            id:       'jupiter',
            label:    'Jupiter',
            label_hi: 'बृहस्पति',
            body:     'Jupiter represents wisdom, moral guidance, and the capacity for a stable, ethically grounded union. In compatibility, Jupiter\'s interaction between charts indicates whether the couple shares a broad philosophical resonance — the degree to which they agree on what makes life meaningful, which is one of the strongest determinants of long-term harmony.',
            body_hi:  'बृहस्पति ज्ञान, नैतिक मार्गदर्शन और एक स्थिर, नैतिक रूप से आधारित मिलन की क्षमता का प्रतिनिधित्व करता है। अनुकूलता में, कुंडलियों के बीच बृहस्पति की परस्पर क्रिया इंगित करती है कि क्या जोड़ा एक व्यापक दार्शनिक अनुनाद साझा करता है।',
          },
          {
            id:       'venus',
            label:    'Venus',
            label_hi: 'शुक्र',
            body:     'Venus governs romance, beauty, and diplomacy. Its interaction across two charts determines the quality of mutual appreciation, shared aesthetic sensibility, and the capacity for affectionate, graceful relating. A strong Venus connection is one of the most reliable indicators of a marriage that feels genuinely pleasurable to both partners.',
            body_hi:  'शुक्र रोमांस, सौंदर्य और कूटनीति को नियंत्रित करता है। दो कुंडलियों में इसकी परस्पर क्रिया पारस्परिक प्रशंसा, साझी सौंदर्य संवेदनशीलता और स्नेहपूर्ण, सुशील संबंध की क्षमता की गुणवत्ता निर्धारित करती है।',
          },
          {
            id:       'saturn',
            label:    'Saturn',
            label_hi: 'शनि',
            body:     'Saturn governs maturity, duty, and long-term commitment. In compatibility, its cross-chart influence determines whether the couple develops a shared sense of responsibility — whether they build together through patient effort. A difficult Saturn interaction may create emotional distance that requires active, conscious bridging to overcome.',
            body_hi:  'शनि परिपक्वता, कर्तव्य और दीर्घकालिक प्रतिबद्धता को नियंत्रित करता है। अनुकूलता में, इसका क्रॉस-चार्ट प्रभाव यह निर्धारित करता है कि क्या जोड़ा जिम्मेदारी की एक साझी भावना विकसित करता है — क्या वे धैर्यपूर्ण प्रयास के माध्यम से मिलकर निर्माण करते हैं।',
          },
          {
            id:       'rahu',
            label:    'Rahu',
            label_hi: 'राहु',
            body:     'Rahu brings an unconventional, intense, or transformative quality to the relationship dynamic. In compatibility, Rahu connections across charts can create a magnetic, compelling attraction that draws two people together with a sense of destiny — but also an inherent volatility that requires maturity to channel constructively.',
            body_hi:  'राहु रिश्ते की गतिशीलता में एक अपरंपरागत, तीव्र या परिवर्तनकारी गुण लाता है। अनुकूलता में, कुंडलियों में राहु संबंध एक चुंबकीय, आकर्षक आकर्षण बना सकते हैं जो दो लोगों को नियति की भावना के साथ एक साथ खींचता है।',
          },
          {
            id:       'ketu',
            label:    'Ketu',
            label_hi: 'केतु',
            body:     'Ketu brings a spiritual, intuitive, and often enigmatic quality. In compatibility, strong Ketu connections indicate partners whose relationship carries a deeply karmic, soul-recognition quality — a sense of having known each other before. The challenge is that this same quality can produce emotional detachment if not balanced by warmer planetary influences.',
            body_hi:  'केतु एक आध्यात्मिक, सहज ज्ञान युक्त और अक्सर रहस्यमय गुण लाता है। अनुकूलता में, मजबूत केतु संबंध ऐसे साझेदारों को इंगित करते हैं जिनके रिश्ते में गहरी कार्मिक, आत्मा-पहचान की गुणवत्ता होती है — पहले एक-दूसरे को जानने की भावना।',
          },
          {
            id:       'seventh-lord',
            label:    'Seventh Lord Analysis',
            label_hi: 'सप्तम स्वामी विश्लेषण',
            body:     'The 7th Lord is the executive power of the 7th house and the single most important indicator in compatibility analysis. Its placement in both charts, its dignity, and its interaction with the partner\'s chart determine whether the partnership brings stability, mutual growth, or significant karmic lessons that require sustained conscious effort to integrate.',
            body_hi:  'सप्तम स्वामी सप्तम भाव की कार्यकारी शक्ति है और अनुकूलता विश्लेषण में सबसे महत्वपूर्ण संकेतक है। दोनों कुंडलियों में इसकी स्थिति, गरिमा और साथी की कुंडली के साथ इसकी परस्पर क्रिया यह निर्धारित करती है कि साझेदारी स्थिरता, पारस्परिक विकास या महत्वपूर्ण कार्मिक पाठ लाती है।',
          },
          {
            id:       'venus-jupiter-karakas',
            label:    'Venus and Jupiter as Compatibility Karakas',
            label_hi: 'अनुकूलता कारकों के रूप में शुक्र और बृहस्पति',
            body:     'Venus (Shukra) represents the capacity for romance and affection, while Jupiter (Guru) represents the capacity for traditional union and ethical structure. Their strength and house placement in both charts are critical indicators of marital quality — when both are strong in both charts, the marriage tends toward both affection and wisdom.',
            body_hi:  'शुक्र रोमांस और स्नेह की क्षमता का प्रतिनिधित्व करता है, जबकि बृहस्पति पारंपरिक मिलन और नैतिक संरचना की क्षमता का प्रतिनिधित्व करता है। दोनों कुंडलियों में उनकी शक्ति और भाव स्थान वैवाहिक गुणवत्ता के महत्वपूर्ण संकेतक हैं।',
          },
        ],
      },
      {
        id:       'advanced-tools',
        title:    'Advanced Tools for Compatibility',
        title_hi: 'अनुकूलता के लिए उन्नत उपकरण',
        layout:   'cards',
        items: [
          {
            id:       'navamsa-d9',
            label:    'Navamsa (D9)',
            label_hi: 'नवांश (D9)',
            body:     'The Navamsa chart is indispensable in compatibility analysis. While the Rashi chart shows the external promise of the partnership, the Navamsa reveals the internal reality and the underlying strength of the marital union. Two strong Navamsa charts, with well-placed 7th houses and lords, confirm that the inner layer of the relationship will support the couple through the inevitable demands of long-term life together.',
            body_hi:  'नवांश चार्ट अनुकूलता विश्लेषण में अपरिहार्य है। जबकि राशि चार्ट साझेदारी का बाहरी वादा दिखाता है, नवांश आंतरिक वास्तविकता और वैवाहिक मिलन की अंतर्निहित शक्ति को प्रकट करता है। दोनों मजबूत नवांश चार्ट, अच्छी तरह से स्थित सप्तम भावों और स्वामियों के साथ, पुष्टि करते हैं कि रिश्ते की आंतरिक परत जोड़े का समर्थन करेगी।',
          },
          {
            id:       'darakaraka',
            label:    'Darakaraka',
            label_hi: 'दारकारक',
            body:     'The Darakaraka — the planet with the lowest degree in the Jaimini system — represents the soul-level archetype of the partner. In compatibility, comparing each person\'s Darakaraka with the partner\'s actual chart reveals how well the partner fulfills the deep, karmic expectation that each person carries of what their spouse should ultimately represent.',
            body_hi:  'दारकारक — जैमिनी प्रणाली में सबसे कम डिग्री वाला ग्रह — साथी के आत्मा-स्तरीय आदर्श का प्रतिनिधित्व करता है। अनुकूलता में, प्रत्येक व्यक्ति के दारकारक को साथी की वास्तविक कुंडली से तुलना करने से पता चलता है कि साथी उस गहरी, कार्मिक अपेक्षा को कितनी अच्छी तरह पूरा करता है।',
          },
          {
            id:       'upapada-lagna',
            label:    'Upapada Lagna',
            label_hi: 'उपपद लग्न',
            body:     'The Upapada Lagna represents the marital union as viewed by society and reveals the karmic implications of the partnership in the public realm. In compatibility analysis, examining both partners\' Upapada Lagna and how they interact provides insight into whether the union enhances or complicates both individuals\' standing and reputation in the world.',
            body_hi:  'उपपद लग्न समाज द्वारा देखे जाने वाले वैवाहिक मिलन का प्रतिनिधित्व करता है और सार्वजनिक क्षेत्र में साझेदारी के कार्मिक निहितार्थों को प्रकट करता है। अनुकूलता विश्लेषण में, दोनों साझेदारों के उपपद लग्न और वे कैसे परस्पर क्रिया करते हैं, इसकी जांच अंतर्दृष्टि प्रदान करती है।',
          },
          {
            id:       'dasha-compatibility',
            label:    'Dasha Compatibility',
            label_hi: 'दशा अनुकूलता',
            body:     'The Dasha cycles of both partners at the time of marriage determine the tone of the union during its formative period. Synchronicity in Dasha cycles often indicates a shared karmic window — a period where both individuals are karmically aligned to make and sustain a significant partnership. Divergent Dashas may create initial tension in pace and readiness.',
            body_hi:  'विवाह के समय दोनों साझेदारों के दशा चक्र अपने निर्माणकारी दौर के दौरान मिलन के स्वर को निर्धारित करते हैं। दशा चक्रों में तालमेल अक्सर एक साझे कार्मिक खिड़की को इंगित करता है — एक ऐसी अवधि जहाँ दोनों व्यक्ति एक महत्वपूर्ण साझेदारी बनाने और बनाए रखने के लिए कार्मिक रूप से संरेखित हैं।',
          },
          {
            id:       'transit-influence',
            label:    'Transit Influence',
            label_hi: 'गोचर प्रभाव',
            body:     'Transits of slow-moving planets trigger major relationship events and periods of testing in both charts simultaneously. Jupiter brings growth and dharmic stabilization; Saturn tests the structural integrity of the bond; Rahu and Ketu bring unexpected karmic turns. Reading transits across both charts together reveals the shared timing of pivotal relationship chapters.',
            body_hi:  'धीमी गति से चलने वाले ग्रहों का गोचर एक साथ दोनों कुंडलियों में प्रमुख संबंध घटनाओं और परीक्षण की अवधियों को ट्रिगर करता है। बृहस्पति विकास और धार्मिक स्थिरीकरण लाता है; शनि बंधन की संरचनात्मक अखंडता की परीक्षा लेता है; राहु और केतु अप्रत्याशित कार्मिक मोड़ लाते हैं।',
          },
        ],
      },
      {
        id:       'compatibility-dimensions',
        title:    'Dimensions of Compatibility',
        title_hi: 'अनुकूलता के आयाम',
        layout:   'checklist',
        items: [
          {
            id:       'emotional-compatibility',
            label:    'Emotional Compatibility',
            label_hi: 'भावनात्मक अनुकूलता',
            body:     'Compatibility beyond Guna Milan requires understanding communication and emotional styles, revealed primarily by Mercury and the Moon in both charts. Partners with harmonious Moon connections tend to feel understood at the emotional level without having to explain themselves — one of the most reliable markers of ease in a long-term relationship.',
            body_hi:  'गुण मिलान से परे अनुकूलता के लिए संचार और भावनात्मक शैलियों को समझना आवश्यक है, जो मुख्यतः दोनों कुंडलियों में बुध और चंद्रमा द्वारा प्रकट होती हैं। सामंजस्यपूर्ण चंद्रमा संबंधों वाले साथी भावनात्मक स्तर पर बिना खुद को समझाए समझे हुए महसूस करते हैं।',
          },
          {
            id:       'physical-compatibility',
            label:    'Physical Compatibility',
            label_hi: 'शारीरिक अनुकूलता',
            body:     'Physical harmony is evaluated through Yoni matching, the interaction of Mars energies across both charts, and the placement and strength of Venus in each chart. These factors together determine the natural alignment of physical temperaments and the quality of the shared energy at the most fundamental, instinctive level of the relationship.',
            body_hi:  'शारीरिक सद्भाव का मूल्यांकन योनि मिलान, दोनों कुंडलियों में मंगल ऊर्जाओं की परस्पर क्रिया और प्रत्येक कुंडली में शुक्र की स्थिति और शक्ति के माध्यम से किया जाता है। ये कारक मिलकर भौतिक स्वभावों के प्राकृतिक संरेखण को निर्धारित करते हैं।',
          },
          {
            id:       'financial-compatibility',
            label:    'Financial Compatibility',
            label_hi: 'वित्तीय अनुकूलता',
            body:     'Financial compatibility is assessed by analyzing the 2nd, 8th, and 11th houses in both charts, reflecting how the couple manages shared resources. Harmonious interactions between these houses in the two charts suggest partners who naturally approach money, security, and shared investment with compatible values and complementary strategies.',
            body_hi:  'वित्तीय अनुकूलता का आकलन दोनों कुंडलियों में 2वें, 8वें और 11वें भावों का विश्लेषण करके किया जाता है, जो दर्शाता है कि जोड़ा साझा संसाधनों का प्रबंधन कैसे करता है। दो कुंडलियों में इन भावों के बीच सामंजस्यपूर्ण परस्पर क्रिया ऐसे साझेदारों का सुझाव देती है जो धन के प्रति संगत मूल्यों के साथ पहुंचते हैं।',
          },
          {
            id:       'family-compatibility',
            label:    'Family Compatibility',
            label_hi: 'पारिवारिक अनुकूलता',
            body:     'Family compatibility is seen in the 2nd and 4th house interactions between charts, indicating how well the couple integrates into each other\'s family structures. Strong connections here suggest partners whose family values and domestic expectations are naturally complementary, reducing the friction that extended-family dynamics often introduce into a marriage.',
            body_hi:  'पारिवारिक अनुकूलता कुंडलियों के बीच 2वें और 4वें भाव की परस्पर क्रिया में दिखाई देती है, जो यह इंगित करती है कि जोड़ा एक-दूसरे की पारिवारिक संरचनाओं में कितनी अच्छी तरह एकीकृत होता है। यहाँ मजबूत संबंध ऐसे साझेदारों का सुझाव देते हैं जिनके पारिवारिक मूल्य और घरेलू अपेक्षाएं स्वाभाविक रूप से पूरक हैं।',
          },
          {
            id:       'long-term-potential',
            label:    'Long-Term Marriage Potential',
            label_hi: 'दीर्घकालिक विवाह क्षमता',
            body:     'Longevity is evaluated by the overall structural strength of the 7th house, 8th house, and the Navamsa in both charts. It requires a balance of duty, affection, and shared values — reflected in the complementary strengths of both charts together. The most durable marriages combine Jupiter\'s ethical depth, Venus\'s affection, and Saturn\'s patient endurance.',
            body_hi:  'दीर्घायु का मूल्यांकन दोनों कुंडलियों में सप्तम भाव, अष्टम भाव और नवांश की समग्र संरचनात्मक शक्ति द्वारा किया जाता है। इसके लिए कर्तव्य, स्नेह और साझे मूल्यों के संतुलन की आवश्यकता होती है। सबसे टिकाऊ विवाह बृहस्पति की नैतिक गहराई, शुक्र के स्नेह और शनि की धैर्यपूर्ण सहनशक्ति को जोड़ते हैं।',
          },
        ],
      },
      {
        id:       'myths-remedies-ethics',
        title:    'Myths, Remedies and Ethical Use',
        title_hi: 'भ्रांतियां, उपाय और नैतिक उपयोग',
        layout:   'list',
        items: [
          {
            id:       'myth-guna-absolute',
            label:    '"Guna Milan is Absolute"',
            label_hi: '"गुण मिलान पूर्ण है"',
            body:     'Guna Milan is a starting point, not the definitive answer to compatibility. A high Guna score without structural chart integrity can still produce a challenging marriage, while a low score combined with strong planetary placements and complementary Navamsa charts can support a highly fulfilling union. Always assess the whole picture.',
            body_hi:  'गुण मिलान एक शुरुआती बिंदु है, अनुकूलता का अंतिम उत्तर नहीं। संरचनात्मक कुंडली अखंडता के बिना उच्च गुण अंक अभी भी एक चुनौतीपूर्ण विवाह पैदा कर सकते हैं, जबकि मजबूत ग्रहीय स्थितियों और पूरक नवांश चार्टों के साथ कम अंक एक अत्यधिक संतोषजनक मिलन का समर्थन कर सकते हैं।',
          },
          {
            id:       'myth-perfect-charts',
            label:    '"Perfect Charts Exist"',
            label_hi: '"परफेक्ट कुंडलियां मौजूद हैं"',
            body:     'All charts carry challenges; compatibility analysis is fundamentally about understanding how two individuals\' specific challenges interact — whether they amplify friction or provide complementary support. The goal is not to find a chart without difficulty but to find one whose difficulties are navigable and whose strengths are genuinely complementary.',
            body_hi:  'सभी कुंडलियों में चुनौतियां होती हैं; अनुकूलता विश्लेषण मूलतः यह समझने के बारे में है कि दो व्यक्तियों की विशिष्ट चुनौतियां कैसे परस्पर क्रिया करती हैं — क्या वे घर्षण को बढ़ाती हैं या पूरक समर्थन प्रदान करती हैं। लक्ष्य बिना कठिनाई के कुंडली खोजना नहीं है।',
          },
          {
            id:       'myth-hard-aspects',
            label:    '"Hard Aspects Equal Failure"',
            label_hi: '"कठिन पहलू विफलता के बराबर हैं"',
            body:     'Challenging planetary connections in a compatibility reading often indicate the most intense areas for karmic growth in the relationship. These are not verdicts of failure but invitations — when navigated with maturity and conscious effort, they frequently produce the most profound bonds and the greatest sense of shared achievement.',
            body_hi:  'अनुकूलता पाठन में चुनौतीपूर्ण ग्रहीय संबंध अक्सर रिश्ते में कार्मिक विकास के लिए सबसे तीव्र क्षेत्रों को इंगित करते हैं। ये विफलता के फैसले नहीं हैं, बल्कि निमंत्रण हैं — जब परिपक्वता और सचेत प्रयास के साथ नेविगेट किया जाता है, तो वे अक्सर सबसे गहरे बंधन उत्पन्न करते हैं।',
          },
          {
            id:       'vedic-remedies',
            label:    'Traditional Vedic Remedies',
            label_hi: 'पारंपरिक वैदिक उपाय',
            body:     'Traditional remedies aim to align consciousness with higher Graha archetypes, fostering a state of mind that naturally supports harmony. This includes cultivating a Sattvic (harmonious) lifestyle, acts of service and charity to balance planetary energies, and meditative focus using traditional planetary mantras. Remedies refine the individual\'s inner state — they do not override the chart but improve the person\'s capacity to meet it with greater wisdom.',
            body_hi:  'पारंपरिक उपाय चेतना को उच्च ग्रह आदर्शों के साथ संरेखित करने का लक्ष्य रखते हैं, जो स्वाभाविक रूप से सद्भाव का समर्थन करने वाली मन की स्थिति को बढ़ावा देता है। इसमें सात्विक जीवनशैली विकसित करना, ग्रहीय ऊर्जाओं को संतुलित करने के लिए सेवा के कार्य और पारंपरिक ग्रह मंत्रों का उपयोग करके ध्यानात्मक फोकस शामिल है।',
          },
          {
            id:       'ethical-interpretation',
            label:    'Ethical Interpretation',
            label_hi: 'नैतिक व्याख्या',
            body:     'An ethical interpretation of compatibility requires empathy and humility. Astrological knowledge is used to foster self-improvement and informed navigation, never to manipulate, control, or prejudge another person. The purpose of compatibility analysis is to approach the relationship with greater wisdom and realistic expectations — not to find reasons to reject a partner or justify predetermined conclusions.',
            body_hi:  'अनुकूलता की नैतिक व्याख्या के लिए सहानुभूति और विनम्रता की आवश्यकता होती है। ज्योतिषीय ज्ञान आत्म-सुधार और सूचित नेविगेशन को बढ़ावा देने के लिए उपयोग किया जाता है, कभी भी किसी अन्य व्यक्ति को नियंत्रित करने, हेरफेर करने या पूर्व-निर्णय करने के लिए नहीं।',
          },
          {
            id:       'summary',
            label:    'Summary',
            label_hi: 'सारांश',
            body:     'Assessing compatibility through Jyotisha is a journey into understanding karmic blueprints. By integrating houses, planetary Karakas, divisional charts like the Navamsa, and Dasha cycles, Jyotisha provides a structured framework for navigating partnership. The chart is not a constraint but a roadmap — a tool for developing the maturity, compassion, and self-knowledge required to build a genuinely fulfilling union.',
            body_hi:  'ज्योतिषा के माध्यम से अनुकूलता का आकलन करना कार्मिक खाकों को समझने की एक यात्रा है। भावों, ग्रह कारकों, नवांश जैसे विभागीय चार्टों और दशा चक्रों को एकीकृत करके, ज्योतिषा साझेदारी को नेविगेट करने के लिए एक संरचित ढांचा प्रदान करता है। कुंडली एक बाधा नहीं बल्कि एक रोडमैप है — परिपक्वता, करुणा और आत्म-ज्ञान विकसित करने के लिए एक उपकरण।',
          },
        ],
      },
      {
        id:       'faqs',
        title:    'Frequently Asked Questions',
        title_hi: 'अक्सर पूछे जाने वाले प्रश्न',
        layout:   'faq',
        items: [
          {
            id:       'faq-1',
            label:    'Can Vedic astrology predict the success of my marriage?',
            label_hi: 'क्या वैदिक ज्योतिष मेरे विवाह की सफलता की भविष्यवाणी कर सकता है?',
            body:     'No. Vedic astrology indicates karmic tendencies and the nature of potential challenges, but the success of a marriage depends on the conscious efforts and maturity of both partners. Compatibility analysis provides a map of potential — how that potential is realized depends entirely on the daily choices and sustained effort both individuals bring.',
            body_hi:  'नहीं। वैदिक ज्योतिष कार्मिक प्रवृत्तियों और संभावित चुनौतियों की प्रकृति को इंगित करता है, लेकिन विवाह की सफलता दोनों साझेदारों के सचेत प्रयासों और परिपक्वता पर निर्भर करती है। अनुकूलता विश्लेषण क्षमता का नक्शा प्रदान करता है।',
          },
          {
            id:       'faq-2',
            label:    'What if my Guna Milan score is low?',
            label_hi: 'क्या होगा यदि मेरा गुण मिलान अंक कम है?',
            body:     'Guna Milan is only one part of the compatibility process. A low score does not automatically indicate an incompatible match — the structural analysis of both charts, the strength of the 7th house, the Navamsa, and the planetary interactions are all more decisive indicators of long-term compatibility than the Guna score alone.',
            body_hi:  'गुण मिलान अनुकूलता प्रक्रिया का केवल एक हिस्सा है। कम अंक स्वतः असंगत मिलान का संकेत नहीं देते — दोनों कुंडलियों का संरचनात्मक विश्लेषण, सप्तम भाव की शक्ति, नवांश और ग्रहीय परस्पर क्रियाएं सभी गुण अंक से अधिक निर्णायक संकेतक हैं।',
          },
          {
            id:       'faq-3',
            label:    'Does the Navamsa reveal my partner\'s nature?',
            label_hi: 'क्या नवांश मेरे साथी की प्रकृति को प्रकट करता है?',
            body:     'Yes. The Navamsa reveals the inner nature of the partner and the underlying strength and health of the union itself — the qualities and dynamics that emerge in the intimacy and sustained reality of marriage, which the Rashi chart alone cannot fully predict.',
            body_hi:  'हां। नवांश साथी की आंतरिक प्रकृति और मिलन की अंतर्निहित शक्ति और स्वास्थ्य को प्रकट करता है — वे गुण और गतिशीलता जो विवाह की अंतरंगता और निरंतर वास्तविकता में उभरती हैं, जिसे राशि चार्ट अकेले पूरी तरह से भविष्यवाणी नहीं कर सकता।',
          },
          {
            id:       'faq-4',
            label:    'Can remedies fix compatibility issues?',
            label_hi: 'क्या उपाय अनुकूलता की समस्याओं को ठीक कर सकते हैं?',
            body:     'Remedies are designed to align your own consciousness, which shifts the dynamics and quality of interaction within the relationship. They do not change the partner or override the chart — they refine the individual\'s inner state, which in turn influences the relationship\'s overall environment and quality.',
            body_hi:  'उपाय आपकी अपनी चेतना को संरेखित करने के लिए डिज़ाइन किए गए हैं, जो रिश्ते के भीतर बातचीत की गतिशीलता और गुणवत्ता को बदलता है। वे साथी को नहीं बदलते या कुंडली को ओवरराइड नहीं करते — वे व्यक्ति की आंतरिक स्थिति को परिष्कृत करते हैं।',
          },
          {
            id:       'faq-5',
            label:    'How important is Dasha in compatibility?',
            label_hi: 'अनुकूलता में दशा कितनी महत्वपूर्ण है?',
            body:     'Dasha analysis is crucial. It defines the dominant karmic themes the couple navigates at any given time, and the Dasha periods active at the time of meeting and marriage significantly shape the tone of the relationship\'s formative phases. Synchronicity in both partners\' Dashas often indicates a shared karmic readiness for the union.',
            body_hi:  'दशा विश्लेषण महत्वपूर्ण है। यह उन प्रमुख कार्मिक विषयों को परिभाषित करता है जिन्हें जोड़ा किसी भी समय नेविगेट करता है, और मिलने और विवाह के समय सक्रिय दशा अवधियां रिश्ते के निर्माणकारी चरणों के स्वर को महत्वपूर्ण रूप से आकार देती हैं।',
          },
          {
            id:       'faq-6',
            label:    'What is the significance of the 8th house in compatibility?',
            label_hi: 'अनुकूलता में 8वें भाव का क्या महत्व है?',
            body:     'The 8th house governs intensity, shared assets, and the transformative dimension of the union — how the couple navigates major crises and the deeper, more vulnerable aspects of intimacy. Strong 8th house connections between two charts indicate capacity for profound bonding under pressure and a relationship that deepens through difficulty rather than fracturing under it.',
            body_hi:  'अष्टम भाव तीव्रता, साझा संपत्ति और मिलन के परिवर्तनकारी आयाम को नियंत्रित करता है — जोड़ा प्रमुख संकटों और अंतरंगता के गहरे, अधिक कमजोर पहलुओं को कैसे नेविगेट करता है। दो कुंडलियों के बीच मजबूत अष्टम भाव संबंध दबाव में गहरे बंधन की क्षमता को इंगित करते हैं।',
          },
          {
            id:       'faq-7',
            label:    'Is Rahu in the 7th house always negative for compatibility?',
            label_hi: 'क्या सप्तम भाव में राहु अनुकूलता के लिए हमेशा नकारात्मक है?',
            body:     'No. Rahu in the 7th house indicates an unconventional, intense, or karmically charged relationship rather than a straightforwardly negative one. The outcome depends on the overall dignity of the 7th Lord and the support from benefic aspects. Such partnerships often carry an unusual magnetism and can bring significant growth when navigated consciously.',
            body_hi:  'नहीं। सप्तम भाव में राहु एक सरल नकारात्मक के बजाय एक अपरंपरागत, तीव्र या कार्मिक रूप से आवेशित संबंध को इंगित करता है। परिणाम सप्तम स्वामी की समग्र गरिमा और शुभ पहलुओं के समर्थन पर निर्भर करता है।',
          },
          {
            id:       'faq-8',
            label:    'Can astrology tell if I will have a love or arranged marriage?',
            label_hi: 'क्या ज्योतिष बता सकता है कि मेरा प्रेम विवाह होगा या व्यवस्थित?',
            body:     'Astrology can show the nature of the partnership and the likely circumstances of meeting — a strong 5th house suggests romance-driven connection, while a strong 9th house suggests a family-mediated process — but not with absolute certainty. The individual\'s own choices and the timing of Dashas ultimately shape which pathway the union takes.',
            body_hi:  'ज्योतिष साझेदारी की प्रकृति और मिलने की संभावित परिस्थितियों को दिखा सकता है — एक मजबूत पंचम भाव रोमांस-चालित संबंध का सुझाव देता है, जबकि एक मजबूत नवम भाव परिवार-मध्यस्थ प्रक्रिया का — लेकिन पूर्ण निश्चितता के साथ नहीं।',
          },
          {
            id:       'faq-9',
            label:    'How do I use this knowledge ethically?',
            label_hi: 'मैं इस ज्ञान का नैतिक रूप से उपयोग कैसे करूं?',
            body:     'Use astrological compatibility knowledge to foster empathy and informed decision-making — to better understand yourself and approach a potential partnership with realistic expectations and genuine openness. Never use it to control, prejudge, or dismiss a partner, or to justify a decision that was made on other, non-astrological grounds.',
            body_hi:  'ज्योतिषीय अनुकूलता ज्ञान का उपयोग सहानुभूति और सूचित निर्णय लेने को बढ़ावा देने के लिए करें — स्वयं को बेहतर समझने और यथार्थवादी अपेक्षाओं और वास्तविक खुलेपन के साथ संभावित साझेदारी के पास पहुंचने के लिए। इसे कभी भी साथी को नियंत्रित करने, पूर्व-निर्णय करने या खारिज करने के लिए उपयोग न करें।',
          },
          {
            id:       'faq-10',
            label:    'Is compatibility analysis the same as predicting marriage success?',
            label_hi: 'क्या अनुकूलता विश्लेषण विवाह सफलता की भविष्यवाणी के समान है?',
            body:     'No. Compatibility analysis is a snapshot of current karmic alignment between two charts, whereas predicting success requires a deep understanding of ongoing karmic evolution — how both partners grow, adapt, and choose over time. Compatibility creates the conditions for success; the partners\' conscious, sustained effort builds it day by day.',
            body_hi:  'नहीं। अनुकूलता विश्लेषण दो कुंडलियों के बीच वर्तमान कार्मिक संरेखण का एक स्नैपशॉट है, जबकि सफलता की भविष्यवाणी के लिए निरंतर कार्मिक विकास की गहरी समझ की आवश्यकता होती है। अनुकूलता सफलता की स्थितियां बनाती है; साझेदारों का सचेत, निरंतर प्रयास इसे दिन-प्रतिदिन बनाता है।',
          },
        ],
      },
    ],
    ctas: [],
  },

  aiMetadata: {
    searchIntent:   'commercial',   // reader evaluating match before marriage
    difficulty:     'beginner',
    authorityLevel: 'standard',
  },

  schemaSignals: {
    expertise: 'Authored by Vedic astrologers specializing in compatibility, Kundli matching, Ashtakoota, and Navamsa analysis.',
  },

  authority: {
    reviewStatus:   'not-reviewed',
    contentVersion: 1,
  },

  publishing: {
    isIndexable:     false,
    isSearchEnabled: false,
    visibility:      'private',
  },

}
