import type { DomainTopic } from '@/lib/domains/_shared/domain-topic.types'

export const divorcePossibility: DomainTopic = {

  identity: {
    id:         'marriage-astrology:divorce-possibility',
    slug:       'divorce-possibility',
    title:      'Divorce Possibility in Vedic Astrology: A Guide',
    title_hi:   'वैदिक ज्योतिष में तलाक की संभावना',
    domain:     'astrology',
    subdomain:  'marriage-astrology',
    category:   'marriage',
    entityType: 'concept',
    status:     'draft',
  },

  routing: {
    canonicalPath: '/marriage-astrology/divorce-possibility',
    breadcrumbs: [
      { label: 'Home',                label_hi: 'होम',              href: '/' },
      { label: 'Marriage Astrology',  label_hi: 'विवाह ज्योतिष',   href: '/marriage-astrology' },
      { label: 'Divorce Possibility', label_hi: 'तलाक की संभावना', href: '/marriage-astrology/divorce-possibility' },
    ],
  },

  seo: {
    metaTitle:       'Divorce Possibility in Vedic Astrology: A Guide',
    metaDescription: 'Learn how Vedic astrology identifies divorce possibility through the 7th house, Navamsa, and Dasha cycles — a guide to karmic patterns and marital resilience.',
    robots:          'noindex,follow',
  },

  hero: {
    headline:    'Divorce Possibility in Vedic Astrology: Understanding Karmic Patterns',
    headline_hi: 'वैदिक ज्योतिष में तलाक की संभावना: कार्मिक पैटर्न को समझना',
    subtext:     'Vedic astrology approaches divorce possibility not as a fixed fate but as a karmic probability — a map of potential friction and cyclical challenges that can be navigated with maturity, conscious effort, and deeper self-understanding.',
    subtext_hi:  'वैदिक ज्योतिष तलाक की संभावना को एक निश्चित भाग्य के रूप में नहीं बल्कि एक कार्मिक संभावना के रूप में देखता है — संभावित घर्षण और चक्रीय चुनौतियों का एक नक्शा जिसे परिपक्वता, सचेत प्रयास और गहरी आत्म-समझ से नेविगेट किया जा सकता है।',
  },

  taxonomy: {
    tags:        ['divorce-possibility', 'vedic-astrology', 'marriage-stability', 'separation-yoga', 'navamsa', '7th-house', 'dasha-analysis', 'marital-karma'],
    keywords:    ['divorce possibility vedic astrology', 'marriage separation astrology', 'vedic astrology divorce', '7th house divorce', 'navamsa marriage stability', 'separation yoga astrology', 'dasha divorce timing'],
    keywords_hi: ['वैदिक ज्योतिष में तलाक', 'विवाह विच्छेद ज्योतिष', 'तलाक योग ज्योतिष'],
    hubPriority: 'standard',
  },

  content: {
    contentTemplate: 'concept',
    contentBlocks: [
      {
        id:       'introduction',
        title:    'Introduction',
        title_hi: 'परिचय',
        layout:   'list',
        items: [
          {
            id:       'karmic-union',
            label:    'Marriage as a Sacred Karmic Union',
            label_hi: 'एक पवित्र कार्मिक मिलन के रूप में विवाह',
            body:     'In Vedic astrology, or Jyotisha, marriage is viewed as a significant Samskara — a sacred sacrament and a profound karmic union. It is governed by Rina-anubandha, the complex web of debts and relationships carried forward from previous lifetimes. As a limb of the Vedas, Jyotisha is used not to predict outcomes with certainty, but to understand the karmic landscape, challenges, and potentials within a relationship. The inquiry into marital separation or divorce is a search for understanding karmic patterns that may lead to the dissolution of this union.',
            body_hi:  'वैदिक ज्योतिष, या ज्योतिषा में, विवाह को एक महत्वपूर्ण संस्कार के रूप में देखा जाता है — एक पवित्र संस्कार और एक गहन कार्मिक मिलन। यह ऋण-अनुबंध द्वारा शासित है, पिछले जीवनकाल से आगे ले जाए गए ऋणों और संबंधों का जटिल जाल। वेदों के एक अंग के रूप में, ज्योतिषा का उपयोग निश्चितता के साथ परिणामों की भविष्यवाणी करने के लिए नहीं, बल्कि एक रिश्ते के भीतर कार्मिक परिदृश्य, चुनौतियों और क्षमताओं को समझने के लिए किया जाता है।',
          },
          {
            id:       'what-divorce-means',
            label:    'What Divorce Possibility Means — and Why It Cannot Be Predicted with Certainty',
            label_hi: 'तलाक की संभावना का क्या अर्थ है — और इसकी निश्चितता से भविष्यवाणी क्यों नहीं की जा सकती',
            body:     'In Jyotisha, "divorce possibility" is not a deterministic outcome. It refers to the presence of specific karmic tendencies, planetary configurations, and cyclical influences that indicate potential friction, detachment, or irreconcilable differences in a marital partnership — a reflection of the challenges the native must navigate within the marital union, based on their Prarabdha Karma. The complexity of human relationships defies absolute prediction. The interplay between two individual birth charts, the degree of maturity of both partners, their ability to communicate consciously, and the influence of current Dasha cycles are all variables that can significantly alter the trajectory of a relationship.',
            body_hi:  'ज्योतिषा में, "तलाक की संभावना" एक नियतात्मक परिणाम नहीं है। यह वैवाहिक साझेदारी में संभावित घर्षण, वैराग्य या अपरिवर्तनीय मतभेदों का संकेत देने वाली विशिष्ट कार्मिक प्रवृत्तियों, ग्रहीय विन्यासों और चक्रीय प्रभावों की उपस्थिति को संदर्भित करता है। मानवीय संबंधों की जटिलता पूर्ण भविष्यवाणी को नकारती है। दो व्यक्तिगत जन्म कुंडलियों के बीच परस्पर क्रिया, दोनों साझेदारों की परिपक्वता की डिग्री और वर्तमान दशा चक्रों का प्रभाव सभी ऐसे चर हैं जो एक रिश्ते की दिशा को महत्वपूर्ण रूप से बदल सकते हैं।',
          },
          {
            id:       'promise-vs-reality',
            label:    'Astrological Promise vs. Reality',
            label_hi: 'ज्योतिषीय वादा बनाम वास्तविकता',
            body:     'A foundational pillar of Jyotisha is the distinction between the "promise" of the birth chart (potential) and the actual manifestation (probability). The birth chart delineates the potential for marital harmony or conflict. However, the timing, intensity, and specific manner of manifestation are governed by Vimshottari Dasha and Gochar (ongoing planetary transits). The "promise" in a chart is a starting point, modulated by the interaction of the partner\'s chart and the conscious effort brought into the relationship.',
            body_hi:  'ज्योतिषा का एक मूलभूत स्तंभ जन्म कुंडली के "वादे" (क्षमता) और वास्तविक अभिव्यक्ति (संभावना) के बीच का अंतर है। जन्म कुंडली वैवाहिक सद्भाव या संघर्ष की क्षमता को रेखांकित करती है। हालांकि, अभिव्यक्ति का समय, तीव्रता और विशिष्ट तरीका विमशोत्तरी दशा और गोचर द्वारा शासित होता है। कुंडली में "वादा" एक शुरुआती बिंदु है, जो साथी की कुंडली की परस्पर क्रिया और रिश्ते में लाए गए सचेत प्रयास द्वारा संशोधित होता है।',
          },
        ],
      },
      {
        id:       'key-house-analysis',
        title:    'Key House Analysis for Marital Stability',
        title_hi: 'वैवाहिक स्थिरता के लिए मुख्य भाव विश्लेषण',
        layout:   'accordion',
        items: [
          {
            id:       'second-house',
            label:    'The 2nd House',
            label_hi: 'द्वितीय भाव',
            body:     'The 2nd House governs family roots and resource stability. Significant affliction here can lead to friction regarding family expectations or financial stress within the union. When malefics occupy or heavily aspect the 2nd house without benefic support, the material and familial foundation of the marriage faces persistent strain.',
            body_hi:  'द्वितीय भाव पारिवारिक जड़ों और संसाधन स्थिरता को नियंत्रित करता है। यहाँ महत्वपूर्ण पीड़ा पारिवारिक अपेक्षाओं या मिलन के भीतर वित्तीय तनाव के संबंध में घर्षण का कारण बन सकती है। जब पापग्रह बिना शुभ समर्थन के द्वितीय भाव में बैठते हैं या उसे दृष्टि देते हैं, तो विवाह की भौतिक और पारिवारिक नींव को लगातार तनाव का सामना करना पड़ता है।',
          },
          {
            id:       'fourth-house',
            label:    'The 4th House',
            label_hi: 'चतुर्थ भाव',
            body:     'The 4th House reveals the domestic foundation and emotional tranquility of the home. Afflictions here can indicate a turbulent domestic environment, contributing to marital dissatisfaction. An afflicted 4th house often manifests as a home that lacks peace — a place where emotional security is chronically undermined rather than nurtured.',
            body_hi:  'चतुर्थ भाव घर की घरेलू नींव और भावनात्मक शांति को प्रकट करता है। यहाँ पीड़ा एक अशांत घरेलू वातावरण का संकेत दे सकती है, जो वैवाहिक असंतोष में योगदान करती है। एक पीड़ित चतुर्थ भाव अक्सर ऐसे घर के रूप में प्रकट होता है जहाँ शांति का अभाव है — एक ऐसी जगह जहाँ भावनात्मक सुरक्षा लगातार कमजोर होती है।',
          },
          {
            id:       'sixth-house',
            label:    'The 6th House',
            label_hi: 'षष्ठ भाव',
            body:     'The 6th House is the house of conflict, litigation, and imbalance. It is the 12th from the 7th house, making it a house of separation from marriage. Strong 6th house influence often indicates conflicts, misunderstandings, or legal disputes within marriage. When the 6th Lord or malefics from the 6th house aspect or afflict the 7th house and its lord, marital discord is likely to surface repeatedly.',
            body_hi:  'षष्ठ भाव संघर्ष, मुकदमेबाजी और असंतुलन का भाव है। यह सप्तम भाव से 12वां है, जो इसे विवाह से अलगाव का भाव बनाता है। षष्ठ भाव का मजबूत प्रभाव अक्सर विवाह के भीतर संघर्षों, गलतफहमियों या कानूनी विवादों को इंगित करता है। जब षष्ठ स्वामी या षष्ठ भाव से पापग्रह सप्तम भाव और उसके स्वामी को प्रभावित करते हैं, तो वैवाहिक कलह बार-बार उभरती है।',
          },
          {
            id:       'seventh-house',
            label:    'The 7th House',
            label_hi: 'सप्तम भाव',
            body:     'The 7th House is the primary house of marriage. Its condition, the planets residing within, and the disposition of its Lord are central to assessing the stability of the union. A strong, unafflicted 7th house with benefic influence indicates a stable and fulfilling partnership, while a heavily afflicted 7th house points to persistent challenges in sustaining the marital bond.',
            body_hi:  'सप्तम भाव विवाह का प्राथमिक भाव है। इसकी स्थिति, इसमें निवास करने वाले ग्रह और इसके स्वामी की स्थिति मिलन की स्थिरता का आकलन करने के लिए केंद्रीय हैं। शुभ प्रभाव के साथ एक मजबूत, निर्विरोध सप्तम भाव एक स्थिर और पूर्ण साझेदारी का संकेत देता है, जबकि एक अत्यधिक पीड़ित सप्तम भाव वैवाहिक बंधन को बनाए रखने में लगातार चुनौतियों की ओर इशारा करता है।',
          },
          {
            id:       'eighth-house',
            label:    'The 8th House',
            label_hi: 'अष्टम भाव',
            body:     'The 8th House governs intensity, shared assets, and deep vulnerabilities. It is the 2nd from the 7th house, indicating the sustenance of the marriage. Afflictions here can indicate hidden secrets, crises, or sudden upheavals that test the foundation of the union. A strong 8th house exchange can deepen intimacy under pressure; a severely afflicted one can bring sudden, destabilizing shocks.',
            body_hi:  'अष्टम भाव तीव्रता, साझा संपत्ति और गहरी कमजोरियों को नियंत्रित करता है। यह सप्तम भाव से दूसरा है, जो विवाह की जीविका को इंगित करता है। यहाँ पीड़ा छिपे रहस्यों, संकटों या अचानक उथल-पुथल का संकेत दे सकती है जो मिलन की नींव की परीक्षा लेती है। एक मजबूत अष्टम भाव आदान-प्रदान दबाव में अंतरंगता को गहरा कर सकता है; एक गंभीर रूप से पीड़ित भाव अचानक, अस्थिर करने वाले झटके ला सकता है।',
          },
          {
            id:       'twelfth-house',
            label:    'The 12th House',
            label_hi: 'द्वादश भाव',
            body:     'The 12th House is the house of detachment, loss, and spiritual transcendence. It is the 6th from the 7th house, indicating the potential for loss, separation, or withdrawal from the partnership. Strong 12th house influence on the 7th house or its lord can manifest as emotional withdrawal, physical distance, or an eventual departure from the marital union.',
            body_hi:  'द्वादश भाव वैराग्य, हानि और आध्यात्मिक अतिक्रमण का भाव है। यह सप्तम भाव से छठा है, जो साझेदारी से हानि, अलगाव या वापसी की क्षमता को इंगित करता है। सप्तम भाव या उसके स्वामी पर द्वादश भाव का मजबूत प्रभाव भावनात्मक वापसी, शारीरिक दूरी या वैवाहिक मिलन से अंततः प्रस्थान के रूप में प्रकट हो सकता है।',
          },
        ],
      },
      {
        id:       'planetary-influences',
        title:    'Planetary Influences and Karaka Analysis',
        title_hi: 'ग्रहीय प्रभाव और कारक विश्लेषण',
        layout:   'accordion',
        items: [
          {
            id:       'sun',
            label:    'Sun',
            label_hi: 'सूर्य',
            body:     'The Sun represents authority and integrity in the relationship. When well-placed, it brings mutual respect and a stable sense of shared dignity. When afflicted, it can manifest as ego-driven conflict — each partner\'s need for recognition competing rather than complementing the other\'s, creating persistent power struggles within the marriage.',
            body_hi:  'सूर्य रिश्ते में अधिकार और ईमानदारी का प्रतिनिधित्व करता है। जब अच्छी तरह से स्थित हो, यह पारस्परिक सम्मान और साझी गरिमा की एक स्थिर भावना लाता है। जब पीड़ित हो, यह अहंकार-चालित संघर्ष के रूप में प्रकट हो सकता है — प्रत्येक साथी की मान्यता की जरूरत एक-दूसरे के पूरक के बजाय प्रतिस्पर्धी बन जाती है।',
          },
          {
            id:       'moon',
            label:    'Moon',
            label_hi: 'चंद्रमा',
            body:     'The Moon governs emotional connection and nurturing capacity. When strong and well-supported, it creates a deeply empathic domestic bond. When afflicted, it brings emotional instability and mood-driven discord — the home becomes a place of unpredictable emotional weather rather than a consistent sanctuary, steadily eroding the sense of safety in the union.',
            body_hi:  'चंद्रमा भावनात्मक संपर्क और पोषण क्षमता को नियंत्रित करता है। जब मजबूत और अच्छी तरह से समर्थित हो, यह एक गहराई से सहानुभूतिपूर्ण घरेलू बंधन बनाता है। जब पीड़ित हो, यह भावनात्मक अस्थिरता और मूड-चालित कलह लाता है — घर अप्रत्याशित भावनात्मक मौसम की जगह बन जाता है।',
          },
          {
            id:       'mars',
            label:    'Mars',
            label_hi: 'मंगल',
            body:     'Mars brings passion and courage into the relationship. When well-channeled, these qualities drive shared ambition and physical vitality. When afflicted, Mars generates aggression and impulsivity — a volatility in conflict management that can escalate minor disagreements into serious ruptures if both partners lack the tools to de-escalate effectively.',
            body_hi:  'मंगल रिश्ते में जुनून और साहस लाता है। जब अच्छी तरह से निर्देशित हो, ये गुण साझी महत्वाकांक्षा और शारीरिक जीवन शक्ति को प्रेरित करते हैं। जब पीड़ित हो, मंगल आक्रामकता और आवेग उत्पन्न करता है — संघर्ष प्रबंधन में एक अस्थिरता जो मामूली असहमति को गंभीर दरारों में बदल सकती है।',
          },
          {
            id:       'mercury',
            label:    'Mercury',
            label_hi: 'बुध',
            body:     'Mercury governs intellectual communication and adaptability. A strong Mercury in both charts enables clear, constructive dialogue. An afflicted Mercury produces critical and restless tendencies — partners talk past each other, struggle to find common ground intellectually, and may fall into patterns of petty criticism that steadily undermine goodwill.',
            body_hi:  'बुध बौद्धिक संचार और अनुकूलनशीलता को नियंत्रित करता है। दोनों कुंडलियों में एक मजबूत बुध स्पष्ट, रचनात्मक संवाद को सक्षम बनाता है। एक पीड़ित बुध आलोचनात्मक और बेचैन प्रवृत्तियां उत्पन्न करता है — साथी एक-दूसरे से बात करते हैं, बौद्धिक रूप से सामान्य आधार खोजने में संघर्ष करते हैं।',
          },
          {
            id:       'jupiter',
            label:    'Jupiter',
            label_hi: 'बृहस्पति',
            body:     'Jupiter brings wisdom, moral guidance, and stability to the marital union. Its benefic aspect is universally protective — a Jupiter aspect on the 7th house or its lord significantly reduces the intensity of whatever afflictions are present. A strong Jupiter in both charts is one of the most reliable indicators of a marriage that endures through difficulty.',
            body_hi:  'बृहस्पति वैवाहिक मिलन में ज्ञान, नैतिक मार्गदर्शन और स्थिरता लाता है। इसकी शुभ दृष्टि सार्वभौमिक रूप से सुरक्षात्मक है — सप्तम भाव या उसके स्वामी पर बृहस्पति की दृष्टि मौजूद पीड़ाओं की तीव्रता को महत्वपूर्ण रूप से कम करती है।',
          },
          {
            id:       'venus',
            label:    'Venus',
            label_hi: 'शुक्र',
            body:     'Venus governs romance, beauty, and diplomacy within the partnership. When well-placed, it creates a relationship rich in affection and grace. When afflicted, it produces self-indulgence and disharmony — one or both partners prioritize personal pleasure over the health of the union, gradually depleting the shared reservoir of goodwill and trust.',
            body_hi:  'शुक्र साझेदारी के भीतर रोमांस, सौंदर्य और कूटनीति को नियंत्रित करता है। जब अच्छी तरह से स्थित हो, यह स्नेह और अनुग्रह से समृद्ध एक रिश्ता बनाता है। जब पीड़ित हो, यह आत्म-भोग और कलह उत्पन्न करता है — एक या दोनों साथी मिलन के स्वास्थ्य से अधिक व्यक्तिगत आनंद को प्राथमिकता देते हैं।',
          },
          {
            id:       'saturn',
            label:    'Saturn',
            label_hi: 'शनि',
            body:     'Saturn brings maturity and duty to the relationship, and when well-placed, it creates a bond with genuine staying power. When afflicted, it manifests as coldness, pessimism, and emotional detachment — a chronic emotional distance that, left unaddressed, can erode the warmth of the union over years until there is little left to sustain it.',
            body_hi:  'शनि रिश्ते में परिपक्वता और कर्तव्य लाता है, और जब अच्छी तरह से स्थित हो, यह वास्तविक स्थायित्व के साथ एक बंधन बनाता है। जब पीड़ित हो, यह ठंडेपन, निराशावाद और भावनात्मक वैराग्य के रूप में प्रकट होता है — एक पुरानी भावनात्मक दूरी जो अनसंबोधित रहने पर, वर्षों में मिलन की गर्मजोशी को नष्ट कर सकती है।',
          },
          {
            id:       'rahu',
            label:    'Rahu',
            label_hi: 'राहु',
            body:     'Rahu brings unconventional, intense, or transformative connections into the relationship. When afflicting the 7th house or its lord, it can cause instability, obsession, or deceit — a partnership marked by unusual intensity that, without high levels of self-awareness, can swing between magnetic attraction and destructive volatility.',
            body_hi:  'राहु रिश्ते में अपरंपरागत, तीव्र या परिवर्तनकारी संबंध लाता है। जब सप्तम भाव या उसके स्वामी को पीड़ित करता है, यह अस्थिरता, जुनून या छल का कारण बन सकता है — एक असामान्य तीव्रता से चिह्नित साझेदारी जो आत्म-जागरूकता के उच्च स्तर के बिना चुंबकीय आकर्षण और विनाशकारी अस्थिरता के बीच झूल सकती है।',
          },
          {
            id:       'ketu',
            label:    'Ketu',
            label_hi: 'केतु',
            body:     'Ketu brings a spiritual and intuitive quality to the relationship. When afflicting the 7th house, it can produce crypticism, sudden disconnection, or isolation — a partner who is emotionally present one moment and inexplicably withdrawn the next, creating a persistent sense of instability and emotional unavailability within the marriage.',
            body_hi:  'केतु रिश्ते में एक आध्यात्मिक और सहज ज्ञान युक्त गुण लाता है। जब सप्तम भाव को पीड़ित करता है, यह रहस्यमयता, अचानक विच्छेद या अलगाव उत्पन्न कर सकता है — एक साथी जो एक पल भावनात्मक रूप से उपस्थित हो और अगले अस्पष्ट रूप से वापस हट जाए।',
          },
          {
            id:       'seventh-lord',
            label:    'Seventh Lord Analysis',
            label_hi: 'सप्तम स्वामी विश्लेषण',
            body:     'The 7th Lord is the executive power of the 7th house and the most decisive single indicator in any marital analysis. Its placement in a Dusthana house (6, 8, or 12) or its severe affliction by malefics can indicate significant karmic lessons that challenge the endurance of the marriage. When the 7th Lord is strong, well-aspected, and placed in a favorable house, even other afflictions to the 7th house are often substantially mitigated.',
            body_hi:  'सप्तम स्वामी सप्तम भाव की कार्यकारी शक्ति है और किसी भी वैवाहिक विश्लेषण में सबसे निर्णायक एकल संकेतक है। दुस्थान भाव (6, 8 या 12) में इसकी स्थिति या पापग्रहों द्वारा इसकी गंभीर पीड़ा महत्वपूर्ण कार्मिक पाठों का संकेत दे सकती है जो विवाह की स्थायित्व को चुनौती देती है।',
          },
          {
            id:       'venus-jupiter-karakas',
            label:    'Venus and Jupiter as Marital Karakas',
            label_hi: 'वैवाहिक कारकों के रूप में शुक्र और बृहस्पति',
            body:     'Venus (Shukra) represents the capacity for affection and romance, while Jupiter (Guru) represents the capacity for traditional stability and wisdom. Their strength and house placement in both charts are critical indicators of the union\'s overall quality and capacity for endurance. When both are dignified and supportive in both charts, the marriage carries a natural resilience that helps it weather even difficult Dasha periods.',
            body_hi:  'शुक्र स्नेह और रोमांस की क्षमता का प्रतिनिधित्व करता है, जबकि बृहस्पति पारंपरिक स्थिरता और ज्ञान की क्षमता का प्रतिनिधित्व करता है। दोनों कुंडलियों में उनकी शक्ति और भाव स्थान मिलन की समग्र गुणवत्ता और स्थायित्व की क्षमता के महत्वपूर्ण संकेतक हैं।',
          },
        ],
      },
      {
        id:       'advanced-tools',
        title:    'Advanced Tools for Marital Assessment',
        title_hi: 'वैवाहिक मूल्यांकन के लिए उन्नत उपकरण',
        layout:   'cards',
        items: [
          {
            id:       'navamsa-d9',
            label:    'Navamsa (D9)',
            label_hi: 'नवांश (D9)',
            body:     'The Navamsa (D9) chart is the indispensable tool for marital assessment. Analysis of the 7th House and 7th Lord in the Navamsa provides conclusive insight into the internal reality of the marital union. A weak Navamsa can contradict a strong Rashi promise — the Navamsa reveals what actually lives beneath the surface of the partnership, independent of the image the Rashi chart projects.',
            body_hi:  'नवांश (D9) चार्ट वैवाहिक मूल्यांकन के लिए अपरिहार्य उपकरण है। नवांश में सप्तम भाव और सप्तम स्वामी का विश्लेषण वैवाहिक मिलन की आंतरिक वास्तविकता में निर्णायक अंतर्दृष्टि प्रदान करता है। एक कमजोर नवांश एक मजबूत राशि वादे का खंडन कर सकता है — नवांश वह प्रकट करता है जो वास्तव में साझेदारी की सतह के नीचे है।',
          },
          {
            id:       'darakaraka',
            label:    'Darakaraka',
            label_hi: 'दारकारक',
            body:     'In Jaimini astrology, the Darakaraka — the planet with the lowest degree — represents the soul-level archetype of the partner. Its placement and aspects offer insight into the karmic function and potential challenges the partner brings to the union. Understanding the Darakaraka helps clarify whether the native\'s karmic expectation of a partner is realistically aligned with the actual partnership they have entered.',
            body_hi:  'जैमिनी ज्योतिष में, दारकारक — सबसे कम डिग्री वाला ग्रह — साथी के आत्मा-स्तरीय आदर्श का प्रतिनिधित्व करता है। इसकी स्थिति और पहलू साझेदार के मिलन में लाने वाले कार्मिक कार्य और संभावित चुनौतियों में अंतर्दृष्टि प्रदान करते हैं।',
          },
          {
            id:       'upapada-lagna',
            label:    'Upapada Lagna',
            label_hi: 'उपपद लग्न',
            body:     'The Upapada Lagna represents the marital union as viewed by society and is crucial for understanding how the union is perceived and the karmic implications of the partnership in the social realm. Afflictions to the Upapada Lagna or its lord indicate challenges that may manifest visibly in the social or public dimension of the marriage, affecting reputation and how the union is understood by others.',
            body_hi:  'उपपद लग्न समाज द्वारा देखे जाने वाले वैवाहिक मिलन का प्रतिनिधित्व करता है और यह समझने के लिए महत्वपूर्ण है कि मिलन को कैसे माना जाता है और सामाजिक क्षेत्र में साझेदारी के कार्मिक निहितार्थ क्या हैं। उपपद लग्न या उसके स्वामी को पीड़ा विवाह के सामाजिक या सार्वजनिक आयाम में दिखाई देने वाली चुनौतियों का संकेत देती है।',
          },
        ],
      },
      {
        id:       'yogas-and-protection',
        title:    'Separation Yogas, Divorce Yogas, and Protective Combinations',
        title_hi: 'अलगाव योग, तलाक योग और सुरक्षात्मक संयोजन',
        layout:   'list',
        items: [
          {
            id:       'separation-yogas',
            label:    'Separation Yogas',
            label_hi: 'अलगाव योग',
            body:     'Specific configurations indicate tendencies toward separation, such as the 7th Lord being afflicted by malefics in Dusthana houses, or planets of separation (Saturn or Rahu) strongly influencing the 7th house, 7th Lord, or Navamsa 7th house. These Yogas indicate karmic friction, not inevitable outcomes — they are patterns that require heightened awareness and conscious effort to navigate constructively.',
            body_hi:  'विशिष्ट विन्यास अलगाव की प्रवृत्तियों को इंगित करते हैं, जैसे दुस्थान भावों में पापग्रहों द्वारा सप्तम स्वामी की पीड़ा, या अलगाव के ग्रह (शनि या राहु) का सप्तम भाव, सप्तम स्वामी या नवांश सप्तम भाव पर मजबूत प्रभाव। ये योग कार्मिक घर्षण इंगित करते हैं, अपरिहार्य परिणाम नहीं।',
          },
          {
            id:       'divorce-yogas',
            label:    'Divorce Yogas',
            label_hi: 'तलाक योग',
            body:     'Divorce Yogas are configurations indicating high potential for the dissolution of the union. These typically involve severe affliction to the 7th house, 7th Lord, and Navamsa indicators, often exacerbated during challenging Dasha cycles. They represent intense karmic tests — the most demanding growth opportunities the soul has taken on in this lifetime — requiring very high levels of maturity and consistent, sustained effort to resolve constructively rather than through separation.',
            body_hi:  'तलाक योग ऐसे विन्यास हैं जो मिलन के विघटन की उच्च क्षमता को इंगित करते हैं। इनमें आमतौर पर सप्तम भाव, सप्तम स्वामी और नवांश संकेतकों की गंभीर पीड़ा शामिल होती है, जो अक्सर चुनौतीपूर्ण दशा चक्रों के दौरान बढ़ जाती है। वे तीव्र कार्मिक परीक्षाओं का प्रतिनिधित्व करते हैं।',
          },
          {
            id:       'protective-combinations',
            label:    'Protective Combinations',
            label_hi: 'सुरक्षात्मक संयोजन',
            body:     'Protective combinations, or Arishta Bhanga, include benefic aspects — especially from Jupiter — on the 7th house or 7th Lord, and the 7th Lord being strong in the Navamsa. These indicate the capacity to overcome karmic challenges and preserve the union. When protective combinations are present, even severe afflictions to the 7th house rarely lead to complete marital breakdown, as the chart carries a natural resilience that mitigates the worst outcomes.',
            body_hi:  'सुरक्षात्मक संयोजन, या अरिष्ट भंग, में शुभ पहलू शामिल हैं — विशेष रूप से बृहस्पति से — सप्तम भाव या सप्तम स्वामी पर, और नवांश में मजबूत सप्तम स्वामी। ये कार्मिक चुनौतियों को दूर करने और मिलन को संरक्षित करने की क्षमता इंगित करते हैं।',
          },
          {
            id:       'reconciliation-indicators',
            label:    'Reconciliation Indicators',
            label_hi: 'सुलह के संकेतक',
            body:     'Indicators for reconciliation include strong benefic influence on the 7th house or Lord in the Navamsa, and positive transit or Dasha influences that occur after a period of separation — suggesting a renewal of the karmic bond. When Jupiter or Venus transits trigger the 7th house positively during a supportive Dasha, the conditions for reconciliation and renewed commitment are at their most favorable.',
            body_hi:  'सुलह के संकेतकों में नवांश में सप्तम भाव या स्वामी पर मजबूत शुभ प्रभाव, और अलगाव की अवधि के बाद होने वाले सकारात्मक गोचर या दशा प्रभाव शामिल हैं — जो कार्मिक बंधन के नवीनीकरण का सुझाव देते हैं।',
          },
        ],
      },
      {
        id:       'timing-and-factors',
        title:    'Timing, Transits, and Contributing Factors',
        title_hi: 'समय, गोचर और योगदान करने वाले कारक',
        layout:   'checklist',
        items: [
          {
            id:       'dasha-analysis',
            label:    'Dasha Analysis',
            label_hi: 'दशा विश्लेषण',
            body:     'The Mahadasha and Antardasha lords at any given time define the dominant karmic themes. Challenging periods — such as the Dasha of planets afflicting the 7th house — often highlight existing friction and bring latent tensions to the surface. Supportive Dasha periods, conversely, offer genuine opportunities to heal, rebuild, and reestablish the foundation of the union.',
            body_hi:  'किसी भी समय महादशा और अंतर्दशा स्वामी प्रमुख कार्मिक विषयों को परिभाषित करते हैं। चुनौतीपूर्ण अवधि — जैसे सप्तम भाव को पीड़ित करने वाले ग्रहों की दशा — अक्सर मौजूदा घर्षण को उजागर करती है और अव्यक्त तनावों को सतह पर लाती है। सहायक दशा अवधियां, इसके विपरीत, उपचार, पुनर्निर्माण के लिए वास्तविक अवसर प्रदान करती हैं।',
          },
          {
            id:       'transit-influence',
            label:    'Transit Influence',
            label_hi: 'गोचर प्रभाव',
            body:     'Transits of slow-moving planets — Jupiter, Saturn, and Rahu/Ketu — through the 7th house or over the 7th Lord act as powerful triggers for marital events, whether they manifest as tests, periods of growth, or separation. Jupiter transits bring expansion and opportunity for reconciliation; Saturn transits test the structural integrity of the bond; Rahu and Ketu bring sudden karmic turns.',
            body_hi:  'धीमी गति से चलने वाले ग्रहों — बृहस्पति, शनि और राहु/केतु — का सप्तम भाव से या सप्तम स्वामी पर गोचर वैवाहिक घटनाओं के लिए शक्तिशाली ट्रिगर के रूप में कार्य करता है। बृहस्पति गोचर सुलह के लिए विस्तार और अवसर लाता है; शनि गोचर बंधन की संरचनात्मक अखंडता की परीक्षा लेता है; राहु और केतु अचानक कार्मिक मोड़ लाते हैं।',
          },
          {
            id:       'emotional-communication',
            label:    'Emotional and Communication Factors',
            label_hi: 'भावनात्मक और संचार कारक',
            body:     'Compatibility requires understanding communication styles, revealed primarily by Mercury and the Moon in both charts. Many marital challenges stem from poor communication and unmet emotional needs — not from planetary malevolence — and these are the most fundamental areas where conscious effort can produce the most significant positive change in the trajectory of the relationship.',
            body_hi:  'अनुकूलता के लिए संचार शैलियों को समझना आवश्यक है, जो मुख्य रूप से दोनों कुंडलियों में बुध और चंद्रमा द्वारा प्रकट होती हैं। कई वैवाहिक चुनौतियां खराब संचार और अपूर्ण भावनात्मक जरूरतों से उत्पन्न होती हैं — ग्रहीय दुर्भावना से नहीं।',
          },
          {
            id:       'misconceptions',
            label:    'Common Misconceptions',
            label_hi: 'सामान्य भ्रांतियां',
            body:     'Two misconceptions distort how people approach this topic: the belief that "hard aspects equal a failed marriage" — when in reality challenges often indicate intense areas for karmic growth — and the belief that "the chart is absolute" — when in reality the chart is the karmic baseline, not the final word. Daily actions, deliberate choices, and sustained conscious effort are the most powerful modifiers of any karmic tendency shown in a birth chart.',
            body_hi:  'दो भ्रांतियां इस विषय के प्रति लोगों के दृष्टिकोण को विकृत करती हैं: यह विश्वास कि "कठिन पहलू विफल विवाह के बराबर हैं" — जबकि वास्तव में चुनौतियां अक्सर कार्मिक विकास के लिए तीव्र क्षेत्रों को इंगित करती हैं — और यह विश्वास कि "कुंडली पूर्ण है" — जबकि वास्तव में कुंडली कार्मिक आधार है, अंतिम शब्द नहीं।',
          },
        ],
      },
      {
        id:       'remedies-ethics-summary',
        title:    'Remedies, Ethics, and Summary',
        title_hi: 'उपाय, नैतिकता और सारांश',
        layout:   'list',
        items: [
          {
            id:       'vedic-remedies',
            label:    'Traditional Vedic Remedies',
            label_hi: 'पारंपरिक वैदिक उपाय',
            body:     'Traditional Jyotisha remedies aim to align the native\'s consciousness with higher Graha archetypes, fostering a state of mind conducive to harmony, patience, and maturity. These include Sattvic lifestyle practices, acts of service and charity to balance planetary energies, and meditative focus using traditional planetary mantras. Remedies work by refining the individual from within — they do not override the chart but improve the person\'s capacity to meet it with greater clarity and compassion.',
            body_hi:  'पारंपरिक ज्योतिषा उपाय जातक की चेतना को उच्च ग्रह आदर्शों के साथ संरेखित करने का लक्ष्य रखते हैं, सद्भाव, धैर्य और परिपक्वता के लिए अनुकूल मन की स्थिति को बढ़ावा देते हैं। इनमें सात्विक जीवनशैली प्रथाएं, ग्रहीय ऊर्जाओं को संतुलित करने के लिए सेवा और दान के कार्य, और पारंपरिक ग्रह मंत्रों का उपयोग करके ध्यानात्मक फोकस शामिल हैं।',
          },
          {
            id:       'ethical-interpretation',
            label:    'Ethical Interpretation',
            label_hi: 'नैतिक व्याख्या',
            body:     'An ethical interpretation of marital astrology requires balance and empathy. It is used to foster self-improvement and informed navigation, never to manipulate, control, or prejudge partners. The goal is always to support the native\'s growth and the health of the union — to help the individual understand their own patterns more clearly so they can meet their partner and their relationship with greater maturity and wisdom.',
            body_hi:  'वैवाहिक ज्योतिष की नैतिक व्याख्या के लिए संतुलन और सहानुभूति की आवश्यकता होती है। इसका उपयोग आत्म-सुधार और सूचित नेविगेशन को बढ़ावा देने के लिए किया जाता है, साझेदारों को नियंत्रित करने, हेरफेर करने या पूर्व-निर्णय करने के लिए कभी नहीं। लक्ष्य हमेशा जातक के विकास और मिलन के स्वास्थ्य का समर्थन करना है।',
          },
          {
            id:       'summary',
            label:    'Summary',
            label_hi: 'सारांश',
            body:     'Assessing the possibility of separation or divorce through Vedic astrology is an exercise in understanding one\'s own karmic blueprint. By integrating the analysis of houses, planetary Karakas, divisional charts, and Dasha cycles, Jyotisha provides a structured framework for navigating partnership — viewing the chart not as a constraint but as a roadmap for developing the maturity, compassion, and insight necessary to transform a karmic bond into a supportive partnership, or to navigate its dissolution with wisdom.',
            body_hi:  'वैदिक ज्योतिष के माध्यम से अलगाव या तलाक की संभावना का आकलन करना अपने स्वयं के कार्मिक खाके को समझने का एक अभ्यास है। भावों, ग्रह कारकों, विभागीय चार्टों और दशा चक्रों के विश्लेषण को एकीकृत करके, ज्योतिषा साझेदारी को नेविगेट करने के लिए एक संरचित ढांचा प्रदान करता है — कुंडली को एक बाधा के रूप में नहीं बल्कि एक रोडमैप के रूप में देखता है।',
          },
        ],
      },
      {
        id:       'faqs',
        title:    'Frequently Asked Questions',
        title_hi: 'अक्सर पूछे जाने वाले प्रश्न',
        layout:   'faq',
        items: [
          {
            id:       'faq-1',
            label:    'Can Vedic astrology predict divorce with certainty?',
            label_hi: 'क्या वैदिक ज्योतिष निश्चितता के साथ तलाक की भविष्यवाणी कर सकता है?',
            body:     'No. Vedic astrology indicates karmic tendencies and challenges, but the ultimate outcome depends on the efforts and maturity of both partners. The chart maps the probability space, not the predetermined destination — conscious, sustained effort can navigate even the most challenging configurations toward a constructive outcome.',
            body_hi:  'नहीं। वैदिक ज्योतिष कार्मिक प्रवृत्तियों और चुनौतियों को इंगित करता है, लेकिन अंतिम परिणाम दोनों साझेदारों के प्रयासों और परिपक्वता पर निर्भर करता है। कुंडली संभावना स्थान को मैप करती है, पूर्वनिर्धारित गंतव्य को नहीं।',
          },
          {
            id:       'faq-2',
            label:    'What if my horoscope shows divorce possibilities?',
            label_hi: 'क्या होगा यदि मेरी जन्म कुंडली तलाक की संभावनाएं दिखाती है?',
            body:     'Challenges are karmic opportunities for growth. Understanding them allows the native to cultivate the maturity to navigate them successfully. A chart that shows divorce possibilities is a chart that is asking for a higher level of self-awareness, communication, and emotional maturity — qualities that, when developed, can transform the challenge into a source of profound personal and relational growth.',
            body_hi:  'चुनौतियां विकास के लिए कार्मिक अवसर हैं। उन्हें समझने से जातक को उन्हें सफलतापूर्वक नेविगेट करने की परिपक्वता विकसित करने की अनुमति मिलती है। तलाक की संभावनाएं दिखाने वाली कुंडली एक उच्च स्तर की आत्म-जागरूकता, संचार और भावनात्मक परिपक्वता की मांग कर रही है।',
          },
          {
            id:       'faq-3',
            label:    'Does the Navamsa chart reveal the stability of my marriage?',
            label_hi: 'क्या नवांश चार्ट मेरे विवाह की स्थिरता को प्रकट करता है?',
            body:     'Yes. The Navamsa is the indispensable tool for understanding the inner reality and structural strength of the marital union. It reveals the qualities and patterns that emerge in the intimacy and sustained reality of marriage — what the Rashi chart alone cannot fully predict. A strong Navamsa is one of the most reliable indicators of a marriage with genuine endurance.',
            body_hi:  'हां। नवांश वैवाहिक मिलन की आंतरिक वास्तविकता और संरचनात्मक शक्ति को समझने के लिए अपरिहार्य उपकरण है। यह विवाह की अंतरंगता और निरंतर वास्तविकता में उभरने वाले गुणों और पैटर्न को प्रकट करता है — जो राशि चार्ट अकेले पूरी तरह से भविष्यवाणी नहीं कर सकता।',
          },
          {
            id:       'faq-4',
            label:    'Can remedies prevent divorce?',
            label_hi: 'क्या उपाय तलाक को रोक सकते हैं?',
            body:     'Remedies are designed to align your own consciousness, which shifts the dynamics of the union toward harmony and growth. They work on the individual\'s inner state — refining the quality of awareness, patience, and empathy brought into the relationship — rather than overriding the partner or the karmic configuration of the charts.',
            body_hi:  'उपाय आपकी अपनी चेतना को संरेखित करने के लिए डिज़ाइन किए गए हैं, जो मिलन की गतिशीलता को सद्भाव और विकास की ओर स्थानांतरित करता है। वे व्यक्ति की आंतरिक स्थिति पर काम करते हैं — जागरूकता, धैर्य और सहानुभूति की गुणवत्ता को परिष्कृत करते हुए।',
          },
          {
            id:       'faq-5',
            label:    'How important is Dasha in analyzing marriage stability?',
            label_hi: 'विवाह स्थिरता के विश्लेषण में दशा कितनी महत्वपूर्ण है?',
            body:     'Dasha is crucial — it defines the karmic themes the couple navigates at any given time and the timing of significant marital events. A difficult Dasha period does not seal the fate of a marriage; it highlights the areas where the greatest conscious effort is currently required. Understanding the Dasha can help partners approach a challenging period with greater awareness rather than reactive conflict.',
            body_hi:  'दशा महत्वपूर्ण है — यह उन कार्मिक विषयों को परिभाषित करती है जिन्हें जोड़ा किसी भी समय नेविगेट करता है और महत्वपूर्ण वैवाहिक घटनाओं का समय निर्धारित करती है। एक कठिन दशा अवधि विवाह का भाग्य नहीं तय करती; यह उन क्षेत्रों को उजागर करती है जहाँ वर्तमान में सबसे बड़े सचेत प्रयास की आवश्यकता है।',
          },
          {
            id:       'faq-6',
            label:    'What is the significance of the 8th house in marriage stability?',
            label_hi: 'विवाह स्थिरता में 8वें भाव का क्या महत्व है?',
            body:     'The 8th house governs shared assets, deep vulnerabilities, and how the couple handles crises. It is the 2nd from the 7th house, indicating the sustenance of the marriage. A strong 8th house exchange in both charts suggests the capacity to deepen and transform the bond through difficulty; an afflicted 8th house warns of potential hidden crises or sudden upheavals that can destabilize the foundation.',
            body_hi:  'अष्टम भाव साझा संपत्ति, गहरी कमजोरियों और जोड़े के संकटों को संभालने के तरीके को नियंत्रित करता है। यह सप्तम भाव से दूसरा है, जो विवाह की जीविका को इंगित करता है। दोनों कुंडलियों में एक मजबूत अष्टम भाव आदान-प्रदान कठिनाई के माध्यम से बंधन को गहरा और परिवर्तित करने की क्षमता का सुझाव देता है।',
          },
          {
            id:       'faq-7',
            label:    'Is Rahu in the 7th house always negative for stability?',
            label_hi: 'क्या सप्तम भाव में राहु स्थिरता के लिए हमेशा नकारात्मक है?',
            body:     'No. Rahu in the 7th house indicates an intense or unconventional relationship that requires high levels of maturity and trust to navigate — not a partnership that is automatically destined to fail. Such relationships often carry an unusual magnetism and can be highly transformative when both partners commit to understanding the deeper karmic purpose of the union.',
            body_hi:  'नहीं। सप्तम भाव में राहु एक तीव्र या अपरंपरागत संबंध को इंगित करता है जिसे नेविगेट करने के लिए उच्च स्तर की परिपक्वता और विश्वास की आवश्यकता होती है — न कि एक साझेदारी जो स्वतः विफल होने के लिए नियत है। ऐसे रिश्ते अक्सर असामान्य चुंबकत्व वहन करते हैं।',
          },
          {
            id:       'faq-8',
            label:    'Can astrology tell if a divorce is final?',
            label_hi: 'क्या ज्योतिष बता सकता है कि तलाक अंतिम है?',
            body:     'Astrology can show the karmic indicators for separation and the periods during which those indicators are most strongly activated. However, reconciliation is always a possibility based on the conscious effort of both partners. No configuration in the chart removes the possibility of renewal — it can only indicate the intensity of the karmic test being navigated.',
            body_hi:  'ज्योतिष अलगाव के कार्मिक संकेतकों और उन अवधियों को दिखा सकता है जिनमें वे संकेतक सबसे मजबूती से सक्रिय होते हैं। हालांकि, दोनों साझेदारों के सचेत प्रयास के आधार पर सुलह हमेशा एक संभावना है। कुंडली में कोई भी विन्यास नवीकरण की संभावना को नहीं हटाता।',
          },
          {
            id:       'faq-9',
            label:    'How do I use this knowledge ethically?',
            label_hi: 'मैं इस ज्ञान का नैतिक रूप से उपयोग कैसे करूं?',
            body:     'Use this knowledge to foster self-improvement, empathy, and informed decision-making. Astrological insights into marital challenges are tools for developing greater understanding of your own patterns and greater compassion for your partner\'s — never for judging, manipulating, or prejudging another person based on their chart or yours.',
            body_hi:  'इस ज्ञान का उपयोग आत्म-सुधार, सहानुभूति और सूचित निर्णय लेने को बढ़ावा देने के लिए करें। वैवाहिक चुनौतियों में ज्योतिषीय अंतर्दृष्टि आपके अपने पैटर्न की गहरी समझ विकसित करने के उपकरण हैं — किसी अन्य व्यक्ति को उनकी या आपकी कुंडली के आधार पर आंकने, हेरफेर करने या पूर्व-निर्णय करने के लिए कभी नहीं।',
          },
          {
            id:       'faq-10',
            label:    'Is stability analysis the same as predicting the future?',
            label_hi: 'क्या स्थिरता विश्लेषण भविष्य की भविष्यवाणी के समान है?',
            body:     'No. Stability analysis is a snapshot of current karmic trends and the structural strengths and challenges present in both charts. Predicting the future requires a deep, ongoing understanding of karmic evolution — how both partners grow, adapt, and choose over time. The chart creates the conditions; the partners\' choices determine the outcome.',
            body_hi:  'नहीं। स्थिरता विश्लेषण वर्तमान कार्मिक प्रवृत्तियों और दोनों कुंडलियों में मौजूद संरचनात्मक शक्तियों और चुनौतियों का एक स्नैपशॉट है। भविष्य की भविष्यवाणी के लिए कार्मिक विकास की गहरी, निरंतर समझ की आवश्यकता होती है। कुंडली स्थितियां बनाती है; साझेदारों के विकल्प परिणाम निर्धारित करते हैं।',
          },
        ],
      },
    ],
    ctas: [],
  },

  aiMetadata: {
    searchIntent:  'informational',
    difficulty:    'beginner',
    authorityLevel: 'standard',
  },

  schemaSignals: {
    expertise: 'Authored by Vedic astrologers specializing in marital stability, separation Yogas, and Navamsa analysis.',
  },

  authority: {
    reviewStatus:   'not-reviewed',
    contentVersion: 1,
  },

  publishing: {
    isIndexable:     false,
    isSearchEnabled: false,
    visibility:      'private',
  },

}
