import type { DomainTopic } from '@/lib/domains/_shared/domain-topic.types'

export const divorcePossibility: DomainTopic = {

  identity: {
    id:         'marriage-astrology:divorce-possibility',
    slug:       'divorce-possibility',
    title:      'Divorce Possibility in Vedic Astrology: A Guide',
    title_hi:   'वैदिक ज्योतिष में तलाक की संभावना',
    domain:     'astrology',
    subdomain:  'marriage-astrology',
    category:   'marriage',
    entityType: 'concept',
    status:     'draft',
  },

  routing: {
    canonicalPath: '/marriage-astrology/divorce-possibility',
    breadcrumbs: [
      { label: 'Home',                label_hi: 'होम',              href: '/' },
      { label: 'Marriage Astrology',  label_hi: 'विवाह ज्योतिष',   href: '/marriage-astrology' },
      { label: 'Divorce Possibility', label_hi: 'तलाक की संभावना', href: '/marriage-astrology/divorce-possibility' },
    ],
  },

  seo: {
    metaTitle:       'Divorce Possibility in Vedic Astrology: A Guide',
    metaDescription: 'Learn how Vedic astrology identifies divorce possibility through the 7th house, Navamsa, and Dasha cycles — a guide to karmic patterns and marital resilience.',
    metaDescription_hi: 'कुंडली में तलाक के योग और वैवाहिक तनाव के संकेत कैसे देखे जाते हैं — सप्तम, षष्ठ, अष्टम और द्वादश भाव, शुक्र-गुरु, दशा, नवांश और सुरक्षात्मक योग। जानें विवाह की स्थिरता के संकेत, और क्यों कोई योग तलाक को निश्चित नहीं करता।',
    robots:          'noindex,follow',
  },

  hero: {
    headline:    'Divorce Possibility in Vedic Astrology: Understanding Karmic Patterns',
    headline_hi: 'वैदिक ज्योतिष में तलाक की संभावना: कार्मिक पैटर्न को समझना',
    subtext:     'Vedic astrology approaches divorce possibility not as a fixed fate but as a karmic probability — a map of potential friction and cyclical challenges that can be navigated with maturity, conscious effort, and deeper self-understanding.',
    subtext_hi:  'वैदिक ज्योतिष तलाक की संभावना को एक निश्चित भाग्य के रूप में नहीं बल्कि एक कार्मिक संभावना के रूप में देखता है — संभावित टकराव और समय-समय पर आने वाली चुनौतियों का एक नक्शा, जिन्हें परिपक्वता, सचेत प्रयास और गहरी आत्म-समझ से संभाला जा सकता है।',
  },

  taxonomy: {
    tags:        ['divorce-possibility', 'vedic-astrology', 'marriage-stability', 'separation-yoga', 'navamsa', '7th-house', 'dasha-analysis', 'marital-karma'],
    keywords:    ['divorce possibility vedic astrology', 'marriage separation astrology', 'vedic astrology divorce', '7th house divorce', 'navamsa marriage stability', 'separation yoga astrology', 'dasha divorce timing'],
    keywords_hi: ['वैदिक ज्योतिष में तलाक', 'विवाह विच्छेद ज्योतिष', 'तलाक योग ज्योतिष'],
    hubPriority: 'standard',
  },

  content: {
    contentTemplate: 'concept',
    contentBlocks: [
      {
        id:       'introduction',
        title:    'Introduction',
        title_hi: 'परिचय',
        layout:   'list',
        items: [
          {
            id:       'karmic-union',
            label:    'Marriage as a Sacred Karmic Union',
            label_hi: 'एक पवित्र कार्मिक मिलन के रूप में विवाह',
            body:     'In Vedic astrology, or Jyotisha, marriage is viewed as a significant Samskara — a sacred sacrament and a profound karmic union. It is governed by Rina-anubandha, the complex web of debts and relationships carried forward from previous lifetimes. As a limb of the Vedas, Jyotisha is used not to predict outcomes with certainty, but to understand the karmic landscape, challenges, and potentials within a relationship. The inquiry into marital separation or divorce is a search for understanding karmic patterns that may lead to the dissolution of this union.',
            body_hi:  'वैदिक ज्योतिष में विवाह को एक महत्वपूर्ण संस्कार माना जाता है — एक पवित्र संस्कार और गहरा कार्मिक बंधन। इसे ऋणानुबंध से जोड़ा जाता है, यानी पिछले जन्मों से चले आ रहे ऋणों और संबंधों का जटिल जाल। वेद का अंग होने के नाते ज्योतिष का उपयोग परिणामों की निश्चित भविष्यवाणी के लिए नहीं, बल्कि किसी रिश्ते की कार्मिक स्थिति, चुनौतियों और संभावनाओं को समझने के लिए किया जाता है।',
          },
          {
            id:       'what-divorce-means',
            label:    'What Divorce Possibility Means — and Why It Cannot Be Predicted with Certainty',
            label_hi: 'तलाक की संभावना का क्या अर्थ है — और इसकी निश्चितता से भविष्यवाणी क्यों नहीं की जा सकती',
            body:     'In Jyotisha, "divorce possibility" is not a deterministic outcome. It refers to the presence of specific karmic tendencies, planetary configurations, and cyclical influences that indicate potential friction, detachment, or irreconcilable differences in a marital partnership — a reflection of the challenges the native must navigate within the marital union, based on their Prarabdha Karma. The complexity of human relationships defies absolute prediction. The interplay between two individual birth charts, the degree of maturity of both partners, their ability to communicate consciously, and the influence of current Dasha cycles are all variables that can significantly alter the trajectory of a relationship.',
            body_hi:  'ज्योतिष में "तलाक की संभावना" कोई तय परिणाम नहीं है। इसका अर्थ है ऐसी कार्मिक प्रवृत्तियाँ, ग्रह योग और समय-चक्र के प्रभाव, जो वैवाहिक संबंध में संभावित टकराव, दूरी या गहरे मतभेदों का संकेत देते हैं। मानवीय संबंध इतने जटिल हैं कि उनकी पूर्ण भविष्यवाणी नहीं की जा सकती। दोनों कुंडलियों का आपसी प्रभाव, दोनों साथियों की परिपक्वता, सचेत संवाद की क्षमता और चल रही दशाएँ — ये सभी किसी रिश्ते की दिशा को काफ़ी हद तक बदल सकते हैं।',
          },
          {
            id:       'promise-vs-reality',
            label:    'Astrological Promise vs. Reality',
            label_hi: 'कुंडली के संकेत बनाम वास्तविकता',
            body:     'A foundational pillar of Jyotisha is the distinction between the "promise" of the birth chart (potential) and the actual manifestation (probability). The birth chart delineates the potential for marital harmony or conflict. However, the timing, intensity, and specific manner of manifestation are governed by Vimshottari Dasha and Gochar (ongoing planetary transits). The "promise" in a chart is a starting point, modulated by the interaction of the partner\'s chart and the conscious effort brought into the relationship.',
            body_hi:  'ज्योतिष का एक मूल सिद्धांत जन्मकुंडली में दिखने वाली संभावना और उसके वास्तव में घटित होने के बीच का अंतर है। जन्मकुंडली वैवाहिक सामंजस्य या टकराव की संभावना दिखाती है, लेकिन यह कब, कितनी तीव्रता से और किस रूप में फलित होगी, यह विंशोत्तरी दशा और गोचर से देखा जाता है। कुंडली के संकेत केवल शुरुआती बिंदु हैं, जिन्हें साथी की कुंडली और रिश्ते में किया गया सचेत प्रयास बदल सकता है।',
          },
        ],
      },
      {
        id:       'key-house-analysis',
        title:    'Key House Analysis for Marital Stability',
        title_hi: 'वैवाहिक स्थिरता के लिए मुख्य भाव विश्लेषण',
        layout:   'accordion',
        items: [
          {
            id:       'second-house',
            label:    'The 2nd House',
            label_hi: 'द्वितीय भाव',
            body:     'The 2nd House governs family roots and resource stability. Significant affliction here can lead to friction regarding family expectations or financial stress within the union. When malefics occupy or heavily aspect the 2nd house without benefic support, the material and familial foundation of the marriage faces persistent strain.',
            body_hi:  'द्वितीय भाव पारिवारिक जड़ों और संसाधन स्थिरता को नियंत्रित करता है। यहाँ महत्वपूर्ण पीड़ा पारिवारिक अपेक्षाओं या मिलन के भीतर वित्तीय तनाव के संबंध में घर्षण का कारण बन सकती है। जब पापग्रह बिना शुभ समर्थन के द्वितीय भाव में बैठते हैं या उसे दृष्टि देते हैं, तो विवाह की भौतिक और पारिवारिक नींव को लगातार तनाव का सामना करना पड़ता है।',
          },
          {
            id:       'fourth-house',
            label:    'The 4th House',
            label_hi: 'चतुर्थ भाव',
            body:     'The 4th House reveals the domestic foundation and emotional tranquility of the home. Afflictions here can indicate a turbulent domestic environment, contributing to marital dissatisfaction. An afflicted 4th house often manifests as a home that lacks peace — a place where emotional security is chronically undermined rather than nurtured.',
            body_hi:  'चतुर्थ भाव घर की घरेलू नींव और भावनात्मक शांति को प्रकट करता है। यहाँ पीड़ा एक अशांत घरेलू वातावरण का संकेत दे सकती है, जो वैवाहिक असंतोष में योगदान करती है। एक पीड़ित चतुर्थ भाव अक्सर ऐसे घर के रूप में प्रकट होता है जहाँ शांति का अभाव है — एक ऐसी जगह जहाँ भावनात्मक सुरक्षा लगातार कमजोर होती है।',
          },
          {
            id:       'sixth-house',
            label:    'The 6th House',
            label_hi: 'षष्ठ भाव',
            body:     'The 6th House is the house of conflict, litigation, and imbalance. It is the 12th from the 7th house, which is why it is traditionally read as a house of separation from marriage. Strong 6th house influence often indicates conflicts, misunderstandings, or legal disputes within marriage. When the 6th Lord or malefics from the 6th house aspect or afflict the 7th house and its lord, the chart may show discord that tends to recur — a pattern to be understood and worked with, not a fixed outcome.',
            body_hi:  'षष्ठ भाव संघर्ष, मुकदमे और असंतुलन का भाव है। यह सप्तम भाव से बारहवाँ है, इसलिए इसे परंपरागत रूप से विवाह से अलगाव का भाव माना जाता है। षष्ठ भाव का प्रबल प्रभाव अक्सर विवाह में टकराव, गलतफहमियों या कानूनी विवादों का संकेत देता है। जब षष्ठेश या षष्ठ भाव के पाप ग्रह सप्तम भाव और सप्तमेश को प्रभावित करें, तो कुंडली बार-बार उभरने वाले मतभेद दिखा सकती है — एक पैटर्न जिसे समझकर संभाला जा सकता है, कोई तय परिणाम नहीं।',
          },
          {
            id:       'seventh-house',
            label:    'The 7th House',
            label_hi: 'सप्तम भाव',
            body:     'The 7th House is the primary house of marriage. Its condition, the planets residing within, and the disposition of its Lord are central to assessing the stability of the union. Even when no planet occupies the 7th house, its sign, its lord and the lord’s placement still describe the marriage — an empty 7th house is never unreadable. A strong, unafflicted 7th house with benefic influence indicates a stable and fulfilling partnership, while a heavily afflicted 7th house is traditionally associated with persistent challenges in sustaining the marital bond.',
            body_hi:  'सप्तम भाव विवाह का मुख्य भाव है। इसकी स्थिति, इसमें स्थित ग्रह और सप्तमेश की स्थिति विवाह की स्थिरता के आकलन के केंद्र में हैं। सप्तम भाव में कोई ग्रह न हो, तब भी उसकी राशि, सप्तमेश और सप्तमेश की स्थिति विवाह के बारे में बताती है — खाली सप्तम भाव कभी पढ़ने योग्य न हो, ऐसा नहीं है। शुभ प्रभाव वाला मज़बूत और पीड़ा-रहित सप्तम भाव स्थिर और संतोषपूर्ण साझेदारी का संकेत देता है, जबकि बहुत पीड़ित सप्तम भाव को परंपरागत रूप से वैवाहिक बंधन बनाए रखने में लगातार चुनौतियों से जोड़ा जाता है।',
          },
          {
            id:       'eighth-house',
            label:    'The 8th House',
            label_hi: 'अष्टम भाव',
            body:     'The 8th House governs intensity, shared assets, and deep vulnerabilities. It is the 2nd from the 7th house, indicating the sustenance of the marriage. Afflictions here can indicate hidden secrets, crises, or sudden upheavals that test the foundation of the union. A strong 8th house exchange can deepen intimacy under pressure; a severely afflicted one can bring sudden, destabilizing shocks.',
            body_hi:  'अष्टम भाव तीव्रता, साझा संपत्ति और गहरी कमजोरियों को नियंत्रित करता है। यह सप्तम भाव से दूसरा है, जो विवाह की जीविका को इंगित करता है। यहाँ पीड़ा छिपे रहस्यों, संकटों या अचानक उथल-पुथल का संकेत दे सकती है जो मिलन की नींव की परीक्षा लेती है। एक मजबूत अष्टम भाव आदान-प्रदान दबाव में अंतरंगता को गहरा कर सकता है; एक गंभीर रूप से पीड़ित भाव अचानक, अस्थिर करने वाले झटके ला सकता है।',
          },
          {
            id:       'twelfth-house',
            label:    'The 12th House',
            label_hi: 'द्वादश भाव',
            body:     'The 12th House is the house of detachment, loss, and spiritual transcendence. It is the 6th from the 7th house, indicating the potential for loss, separation, or withdrawal from the partnership. Strong 12th house influence on the 7th house or its lord can manifest as emotional withdrawal, physical distance, or in some charts an eventual parting — always read alongside the protective factors in the chart.',
            body_hi:  'द्वादश भाव वैराग्य, हानि और आध्यात्मिक मुक्ति का भाव है। यह सप्तम भाव से छठा है, इसलिए यह साझेदारी में हानि, अलगाव या दूरी की संभावना दिखाता है। सप्तम भाव या सप्तमेश पर द्वादश भाव का प्रबल प्रभाव भावनात्मक दूरी, शारीरिक दूरी या कुछ कुंडलियों में आगे चलकर अलग होने के रूप में दिख सकता है — जिसे हमेशा सुरक्षात्मक कारकों के साथ पढ़ा जाता है।',
          },
        ],
      },
      {
        id:       'planetary-influences',
        title:    'Planetary Influences and Karaka Analysis',
        title_hi: 'ग्रहीय प्रभाव और कारक विश्लेषण',
        layout:   'accordion',
        items: [
          {
            id:       'sun',
            label:    'Sun',
            label_hi: 'सूर्य',
            body:     'The Sun represents authority and integrity in the relationship. When well-placed, it brings mutual respect and a stable sense of shared dignity. When afflicted, it can manifest as ego-driven conflict — each partner\'s need for recognition competing rather than complementing the other\'s, creating persistent power struggles within the marriage.',
            body_hi:  'सूर्य रिश्ते में अधिकार और ईमानदारी का प्रतिनिधित्व करता है। जब अच्छी तरह से स्थित हो, यह पारस्परिक सम्मान और साझी गरिमा की एक स्थिर भावना लाता है। जब पीड़ित हो, यह अहंकार-चालित संघर्ष के रूप में प्रकट हो सकता है — प्रत्येक साथी की मान्यता की जरूरत एक-दूसरे के पूरक के बजाय प्रतिस्पर्धी बन जाती है।',
          },
          {
            id:       'moon',
            label:    'Moon',
            label_hi: 'चंद्रमा',
            body:     'The Moon governs emotional connection and nurturing capacity. When strong and well-supported, it creates a deeply empathic domestic bond. When afflicted, it brings emotional instability and mood-driven discord — the home becomes a place of unpredictable emotional weather rather than a consistent sanctuary, steadily eroding the sense of safety in the union.',
            body_hi:  'चंद्रमा भावनात्मक संपर्क और पोषण क्षमता को नियंत्रित करता है। जब मजबूत और अच्छी तरह से समर्थित हो, यह एक गहराई से सहानुभूतिपूर्ण घरेलू बंधन बनाता है। जब पीड़ित हो, यह भावनात्मक अस्थिरता और मूड-चालित कलह लाता है — घर अप्रत्याशित भावनात्मक मौसम की जगह बन जाता है।',
          },
          {
            id:       'mars',
            label:    'Mars',
            label_hi: 'मंगल',
            body:     'Mars brings passion and courage into the relationship. When well-channeled, these qualities drive shared ambition and physical vitality. When afflicted, Mars generates aggression and impulsivity — a volatility in conflict management that can escalate minor disagreements into serious ruptures if both partners lack the tools to de-escalate effectively.',
            body_hi:  'मंगल रिश्ते में जुनून और साहस लाता है। जब अच्छी तरह से निर्देशित हो, ये गुण साझी महत्वाकांक्षा और शारीरिक जीवन शक्ति को प्रेरित करते हैं। जब पीड़ित हो, मंगल आक्रामकता और आवेग उत्पन्न करता है — संघर्ष प्रबंधन में एक अस्थिरता जो मामूली असहमति को गंभीर दरारों में बदल सकती है।',
          },
          {
            id:       'mercury',
            label:    'Mercury',
            label_hi: 'बुध',
            body:     'Mercury governs intellectual communication and adaptability. A strong Mercury in both charts enables clear, constructive dialogue. An afflicted Mercury produces critical and restless tendencies — partners talk past each other, struggle to find common ground intellectually, and may fall into patterns of petty criticism that steadily undermine goodwill.',
            body_hi:  'बुध बौद्धिक संचार और अनुकूलनशीलता को नियंत्रित करता है। दोनों कुंडलियों में एक मजबूत बुध स्पष्ट, रचनात्मक संवाद को सक्षम बनाता है। एक पीड़ित बुध आलोचनात्मक और बेचैन प्रवृत्तियां उत्पन्न करता है — साथी एक-दूसरे से बात करते हैं, बौद्धिक रूप से सामान्य आधार खोजने में संघर्ष करते हैं।',
          },
          {
            id:       'jupiter',
            label:    'Jupiter',
            label_hi: 'बृहस्पति',
            body:     'Jupiter brings wisdom, moral guidance, and stability to the marital union. Its benefic aspect is traditionally regarded as strongly protective — a Jupiter aspect on the 7th house or its lord is read as reducing the intensity of whatever afflictions are present. A strong Jupiter in both charts is one of the strongest supportive indicators of a marriage that endures through difficulty.',
            body_hi:  'गुरु वैवाहिक जीवन में ज्ञान, नैतिक मार्गदर्शन और स्थिरता लाता है। इसकी शुभ दृष्टि को परंपरागत रूप से अत्यंत सुरक्षात्मक माना जाता है — सप्तम भाव या सप्तमेश पर गुरु की दृष्टि मौजूद पीड़ाओं की तीव्रता को कम करने वाली मानी जाती है। दोनों कुंडलियों में मज़बूत गुरु कठिनाइयों में भी टिके रहने वाले विवाह के सबसे प्रबल सहायक संकेतों में से एक है।',
          },
          {
            id:       'venus',
            label:    'Venus',
            label_hi: 'शुक्र',
            body:     'Venus governs romance, beauty, and diplomacy within the partnership. When well-placed, it creates a relationship rich in affection and grace. When afflicted, it produces self-indulgence and disharmony — one or both partners prioritize personal pleasure over the health of the union, gradually depleting the shared reservoir of goodwill and trust.',
            body_hi:  'शुक्र साझेदारी के भीतर रोमांस, सौंदर्य और कूटनीति को नियंत्रित करता है। जब अच्छी तरह से स्थित हो, यह स्नेह और अनुग्रह से समृद्ध एक रिश्ता बनाता है। जब पीड़ित हो, यह आत्म-भोग और कलह उत्पन्न करता है — एक या दोनों साथी मिलन के स्वास्थ्य से अधिक व्यक्तिगत आनंद को प्राथमिकता देते हैं।',
          },
          {
            id:       'saturn',
            label:    'Saturn',
            label_hi: 'शनि',
            body:     'Saturn brings maturity and duty to the relationship, and when well-placed, it creates a bond with genuine staying power. When afflicted, it manifests as coldness, pessimism, and emotional detachment — a chronic emotional distance that, left unaddressed, can erode the warmth of the union over years until there is little left to sustain it.',
            body_hi:  'शनि रिश्ते में परिपक्वता और कर्तव्य लाता है, और जब अच्छी तरह से स्थित हो, यह वास्तविक स्थायित्व के साथ एक बंधन बनाता है। जब पीड़ित हो, यह ठंडेपन, निराशावाद और भावनात्मक वैराग्य के रूप में प्रकट होता है — एक पुरानी भावनात्मक दूरी जो अनसंबोधित रहने पर, वर्षों में मिलन की गर्मजोशी को नष्ट कर सकती है।',
          },
          {
            id:       'rahu',
            label:    'Rahu',
            label_hi: 'राहु',
            body:     'Rahu brings unconventional, intense, or transformative connections into the relationship. When afflicting the 7th house or its lord, it can cause instability, obsession, or deceit — a partnership marked by unusual intensity that, without high levels of self-awareness, can swing between magnetic attraction and destructive volatility.',
            body_hi:  'राहु रिश्ते में अपरंपरागत, तीव्र या परिवर्तनकारी संबंध लाता है। जब सप्तम भाव या उसके स्वामी को पीड़ित करता है, यह अस्थिरता, जुनून या छल का कारण बन सकता है — एक असामान्य तीव्रता से चिह्नित साझेदारी जो आत्म-जागरूकता के उच्च स्तर के बिना चुंबकीय आकर्षण और विनाशकारी अस्थिरता के बीच झूल सकती है।',
          },
          {
            id:       'ketu',
            label:    'Ketu',
            label_hi: 'केतु',
            body:     'Ketu brings a spiritual and intuitive quality to the relationship. When afflicting the 7th house, it can produce crypticism, sudden disconnection, or isolation — a partner who is emotionally present one moment and inexplicably withdrawn the next, creating a persistent sense of instability and emotional unavailability within the marriage.',
            body_hi:  'केतु रिश्ते में एक आध्यात्मिक और सहज ज्ञान युक्त गुण लाता है। जब सप्तम भाव को पीड़ित करता है, यह रहस्यमयता, अचानक विच्छेद या अलगाव उत्पन्न कर सकता है — एक साथी जो एक पल भावनात्मक रूप से उपस्थित हो और अगले अस्पष्ट रूप से वापस हट जाए।',
          },
          {
            id:       'seventh-lord',
            label:    'Seventh Lord Analysis',
            label_hi: 'सप्तम स्वामी विश्लेषण',
            body:     'The 7th Lord is the executive power of the 7th house and one of the most important indicators in any marital analysis. Its placement in a Dusthana house (6, 8, or 12) or its severe affliction by malefics can indicate significant karmic lessons that challenge the endurance of the marriage. When the 7th Lord is strong, well-aspected, and placed in a favorable house, even other afflictions to the 7th house are often substantially mitigated.',
            body_hi:  'सप्तमेश सप्तम भाव की कार्यकारी शक्ति है और किसी भी वैवाहिक विश्लेषण के सबसे महत्वपूर्ण संकेतों में से एक है। दुःस्थान भाव (6, 8 या 12) में इसकी स्थिति या पाप ग्रहों से गंभीर पीड़ा ऐसे कार्मिक पाठों का संकेत दे सकती है जो विवाह की स्थिरता की परीक्षा लेते हैं। जब सप्तमेश मज़बूत, शुभ दृष्टि वाला और अनुकूल भाव में हो, तो सप्तम भाव की अन्य पीड़ाएँ भी अक्सर काफ़ी हद तक कम हो जाती हैं।',
          },
          {
            id:       'venus-jupiter-karakas',
            label:    'Venus and Jupiter as Marital Karakas',
            label_hi: 'वैवाहिक कारकों के रूप में शुक्र और बृहस्पति',
            body:     'Venus (Shukra) represents the capacity for affection and romance, while Jupiter (Guru) represents the capacity for traditional stability and wisdom. Their strength and house placement in both charts are critical indicators of the union\'s overall quality and capacity for endurance. When both are dignified and supportive in both charts, the marriage carries a natural resilience that helps it weather even difficult Dasha periods.',
            body_hi:  'शुक्र स्नेह और रोमांस की क्षमता का प्रतिनिधित्व करता है, जबकि बृहस्पति पारंपरिक स्थिरता और ज्ञान की क्षमता का प्रतिनिधित्व करता है। दोनों कुंडलियों में उनकी शक्ति और भाव स्थान मिलन की समग्र गुणवत्ता और स्थायित्व की क्षमता के महत्वपूर्ण संकेतक हैं।',
          },
        ],
      },
      {
        id:       'advanced-tools',
        title:    'Advanced Tools for Marital Assessment',
        title_hi: 'वैवाहिक मूल्यांकन के लिए उन्नत उपकरण',
        layout:   'cards',
        items: [
          {
            id:       'navamsa-d9',
            label:    'Navamsa (D9)',
            label_hi: 'नवांश (D9)',
            body:     'The Navamsa (D9) chart is an essential tool for marital assessment. Analysis of the 7th House and 7th Lord in the Navamsa provides deeper insight into the internal reality of the marital union. A weak Navamsa can contradict a strong Rashi promise — the Navamsa is read as showing what lies beneath the surface of the partnership, beyond the image the Rashi chart projects.',
            body_hi:  'नवांश (D9) कुंडली वैवाहिक आकलन का एक आवश्यक साधन है। नवांश में सप्तम भाव और सप्तमेश का विश्लेषण वैवाहिक संबंध की आंतरिक वास्तविकता की गहरी समझ देता है। कमज़ोर नवांश राशि कुंडली के मज़बूत संकेतों से अलग तस्वीर दिखा सकता है — नवांश को साझेदारी की सतह के नीचे की स्थिति दिखाने वाला माना जाता है।',
          },
          {
            id:       'darakaraka',
            label:    'Darakaraka',
            label_hi: 'दारकारक',
            body:     'In Jaimini astrology, the Darakaraka — the planet with the lowest degree — represents the soul-level archetype of the partner. Its placement and aspects offer insight into the karmic function and potential challenges the partner brings to the union. Understanding the Darakaraka helps clarify whether the native\'s karmic expectation of a partner is realistically aligned with the actual partnership they have entered.',
            body_hi:  'जैमिनी ज्योतिष में दारकारक — सबसे कम अंश वाला ग्रह — जीवनसाथी के आत्मिक स्वरूप का प्रतिनिधित्व करता है। इसकी स्थिति और इस पर पड़ने वाली दृष्टियाँ बताती हैं कि जीवनसाथी विवाह में कौन-सी कार्मिक भूमिका और संभावित चुनौतियाँ लेकर आता है।',
          },
          {
            id:       'upapada-lagna',
            label:    'Upapada Lagna',
            label_hi: 'उपपद लग्न',
            body:     'The Upapada Lagna represents the marital union as viewed by society and is crucial for understanding how the union is perceived and the karmic implications of the partnership in the social realm. Afflictions to the Upapada Lagna or its lord indicate challenges that may manifest visibly in the social or public dimension of the marriage, affecting reputation and how the union is understood by others.',
            body_hi:  'उपपद लग्न समाज द्वारा देखे जाने वाले वैवाहिक मिलन का प्रतिनिधित्व करता है और यह समझने के लिए महत्वपूर्ण है कि मिलन को कैसे माना जाता है और सामाजिक क्षेत्र में साझेदारी के कार्मिक निहितार्थ क्या हैं। उपपद लग्न या उसके स्वामी को पीड़ा विवाह के सामाजिक या सार्वजनिक आयाम में दिखाई देने वाली चुनौतियों का संकेत देती है।',
          },
        ],
      },
      {
        id:       'yogas-and-protection',
        title:    'Separation Yogas, Divorce Yogas, and Protective Combinations',
        title_hi: 'अलगाव योग, तलाक योग और सुरक्षात्मक संयोजन',
        layout:   'list',
        items: [
          {
            id:       'separation-yogas',
            label:    'Separation Yogas',
            label_hi: 'अलगाव योग',
            body:     'Specific configurations indicate tendencies toward separation, such as the 7th Lord being afflicted by malefics in Dusthana houses, or planets of separation (Saturn or Rahu) strongly influencing the 7th house, 7th Lord, or Navamsa 7th house. These Yogas indicate karmic friction, not inevitable outcomes — they are patterns that require heightened awareness and conscious effort to navigate constructively.',
            body_hi:  'विशिष्ट विन्यास अलगाव की प्रवृत्तियों को इंगित करते हैं, जैसे दुस्थान भावों में पापग्रहों द्वारा सप्तम स्वामी की पीड़ा, या अलगाव के ग्रह (शनि या राहु) का सप्तम भाव, सप्तम स्वामी या नवांश सप्तम भाव पर मजबूत प्रभाव। ये योग कार्मिक घर्षण इंगित करते हैं, अपरिहार्य परिणाम नहीं।',
          },
          {
            id:       'divorce-yogas',
            label:    'Divorce Yogas',
            label_hi: 'तलाक योग',
            body:     'Divorce Yogas are configurations traditionally associated with a higher potential for the dissolution of the union — not a certain outcome. These typically involve severe affliction to the 7th house, 7th Lord, and Navamsa indicators, often intensified during challenging Dasha cycles. They represent intense karmic tests that call for maturity and sustained effort; how a couple responds — including, in some cases, a decision to separate — remains a human choice, not a chart verdict.',
            body_hi:  'तलाक योग ऐसे ग्रह योग हैं जिन्हें परंपरागत रूप से विवाह टूटने की अधिक संभावना से जोड़ा जाता है — कोई निश्चित परिणाम नहीं। इनमें आमतौर पर सप्तम भाव, सप्तमेश और नवांश के संकेतों पर गंभीर पीड़ा होती है, जो कठिन दशाओं में बढ़ सकती है। ये गहरी कार्मिक परीक्षाएँ हैं जो परिपक्वता और निरंतर प्रयास माँगती हैं; दंपति इनका सामना कैसे करता है — जिसमें कुछ मामलों में अलग होने का निर्णय भी शामिल हो सकता है — यह मानवीय निर्णय है, कुंडली का फैसला नहीं।',
          },
          {
            id:       'protective-combinations',
            label:    'Protective Combinations',
            label_hi: 'सुरक्षात्मक संयोजन',
            body:     'Protective combinations, or Arishta Bhanga, include benefic aspects — especially from Jupiter — on the 7th house or 7th Lord, and the 7th Lord being strong in the Navamsa. These indicate the capacity to overcome karmic challenges and preserve the union. When protective combinations are present, they are traditionally read as moderating even severe afflictions to the 7th house, giving the chart a natural resilience.',
            body_hi:  'सुरक्षात्मक योग, या अरिष्ट भंग, में सप्तम भाव या सप्तमेश पर शुभ ग्रहों — विशेषकर गुरु — की दृष्टि और नवांश में मज़बूत सप्तमेश शामिल हैं। ये कार्मिक चुनौतियों से उबरने और विवाह को बचाए रखने की क्षमता दिखाते हैं। जब सुरक्षात्मक योग मौजूद हों, तो उन्हें परंपरागत रूप से सप्तम भाव की गंभीर पीड़ा को भी कम करने वाला माना जाता है, जिससे कुंडली में स्वाभाविक लचीलापन आता है।',
          },
          {
            id:       'reconciliation-indicators',
            label:    'Reconciliation Indicators',
            label_hi: 'सुलह के संकेतक',
            body:     'Indicators for reconciliation include strong benefic influence on the 7th house or Lord in the Navamsa, and positive transit or Dasha influences that occur after a period of separation — suggesting a renewal of the karmic bond. When Jupiter or Venus transits activate the 7th house positively during a supportive Dasha, the conditions for reconciliation are traditionally considered most favorable — though whether to reconcile remains the partners’ own decision.',
            body_hi:  'सुलह के संकेतों में नवांश में सप्तम भाव या सप्तमेश पर प्रबल शुभ प्रभाव, और अलगाव की अवधि के बाद आने वाले अनुकूल गोचर या दशा प्रभाव शामिल हैं — जो कार्मिक बंधन के नवीनीकरण का संकेत देते हैं। सहायक दशा में गुरु या शुक्र के गोचर से सप्तम भाव सक्रिय हो, तो सुलह की परिस्थितियाँ परंपरागत रूप से सबसे अनुकूल मानी जाती हैं — हालांकि सुलह करनी है या नहीं, यह दोनों साथियों का अपना निर्णय है।',
          },
        ],
      },
      {
        id:       'timing-and-factors',
        title:    'Timing, Transits, and Contributing Factors',
        title_hi: 'समय, गोचर और योगदान करने वाले कारक',
        layout:   'checklist',
        items: [
          {
            id:       'dasha-analysis',
            label:    'Dasha Analysis',
            label_hi: 'दशा विश्लेषण',
            body:     'The Mahadasha and Antardasha lords at any given time define the dominant karmic themes. Challenging periods — such as the Dasha of planets afflicting the 7th house — often highlight existing friction and bring latent tensions to the surface. Supportive Dasha periods, conversely, offer genuine opportunities to heal, rebuild, and reestablish the foundation of the union.',
            body_hi:  'किसी भी समय चल रही महादशा और अंतर्दशा के स्वामी प्रमुख कार्मिक विषय तय करते हैं। कठिन दशाएँ — जैसे सप्तम भाव को पीड़ित करने वाले ग्रहों की दशा — अक्सर मौजूदा टकराव को उजागर करती हैं और दबे हुए तनाव सामने लाती हैं। इसके विपरीत, सहायक दशाएँ रिश्ते को सुधारने और उसकी नींव फिर से मज़बूत करने के वास्तविक अवसर देती हैं।',
          },
          {
            id:       'transit-influence',
            label:    'Transit Influence',
            label_hi: 'गोचर प्रभाव',
            body:     'Transits of slow-moving planets — Jupiter, Saturn, and Rahu/Ketu — through the 7th house or over the 7th Lord are traditionally read as triggers that can coincide with marital tests, periods of growth or, in some cases, separation. Jupiter transits bring expansion and opportunity for reconciliation; Saturn transits test the structural integrity of the bond; Rahu and Ketu bring sudden karmic turns.',
            body_hi:  'धीमी गति वाले ग्रहों — गुरु, शनि और राहु/केतु — का सप्तम भाव या सप्तमेश पर गोचर परंपरागत रूप से ऐसे सक्रिय कारक माने जाते हैं जो वैवाहिक परीक्षाओं, विकास के दौर या कुछ मामलों में अलगाव के समय से मेल खा सकते हैं। गुरु का गोचर विस्तार और सुलह के अवसर लाता है; शनि का गोचर रिश्ते की मज़बूती की परीक्षा लेता है; राहु और केतु अचानक कार्मिक मोड़ लाते हैं।',
          },
          {
            id:       'emotional-communication',
            label:    'Emotional and Communication Factors',
            label_hi: 'भावनात्मक और संचार कारक',
            body:     'Compatibility requires understanding communication styles, revealed primarily by Mercury and the Moon in both charts. Many marital challenges stem from poor communication and unmet emotional needs — not from planetary malevolence — and these are the most fundamental areas where conscious effort can produce the most significant positive change in the trajectory of the relationship.',
            body_hi:  'अनुकूलता के लिए संचार शैलियों को समझना आवश्यक है, जो मुख्य रूप से दोनों कुंडलियों में बुध और चंद्रमा द्वारा प्रकट होती हैं। कई वैवाहिक चुनौतियां खराब संचार और अपूर्ण भावनात्मक जरूरतों से उत्पन्न होती हैं — ग्रहीय दुर्भावना से नहीं।',
          },
          {
            id:       'misconceptions',
            label:    'Common Misconceptions',
            label_hi: 'सामान्य भ्रांतियां',
            body:     'Two misconceptions distort how people approach this topic: the belief that "hard aspects equal a failed marriage" — when in reality challenges often indicate intense areas for karmic growth — and the belief that "the chart is absolute" — when in reality the chart is the karmic baseline, not the final word. Daily actions, deliberate choices, and sustained conscious effort are the most powerful modifiers of any karmic tendency shown in a birth chart.',
            body_hi:  'दो भ्रांतियाँ इस विषय को समझने के तरीके को बिगाड़ती हैं: यह धारणा कि "कठिन ग्रह-योग का अर्थ विफल विवाह है" — जबकि वास्तव में चुनौतियाँ अक्सर कार्मिक विकास के गहरे क्षेत्र दिखाती हैं — और यह धारणा कि "कुंडली अंतिम है" — जबकि कुंडली कार्मिक आधार है, अंतिम निर्णय नहीं।',
          },
        ],
      },
      {
        id:       'remedies-ethics-summary',
        title:    'Remedies, Ethics, and Summary',
        title_hi: 'उपाय, नैतिकता और सारांश',
        layout:   'list',
        items: [
          {
            id:       'vedic-remedies',
            label:    'Traditional Vedic Remedies',
            label_hi: 'पारंपरिक वैदिक उपाय',
            body:     'Traditional Jyotisha remedies aim to align the native’s consciousness with higher Graha archetypes, fostering a state of mind conducive to harmony, patience, and maturity. These include Sattvic lifestyle practices, acts of service and charity to balance planetary energies, and meditative focus using traditional planetary mantras. Remedies work by refining the individual from within — they do not override the chart, and they are not a substitute for counselling, legal advice or safety support when these are needed.',
            body_hi:  'पारंपरिक ज्योतिषीय उपायों का उद्देश्य जातक की चेतना को ग्रहों के उच्च आदर्शों के अनुरूप ढालना है, ताकि मन में सामंजस्य, धैर्य और परिपक्वता बढ़े। इनमें सात्विक जीवनशैली, ग्रह ऊर्जाओं को संतुलित करने के लिए सेवा और दान, और पारंपरिक ग्रह मंत्रों के साथ ध्यान शामिल हैं। उपाय व्यक्ति को भीतर से निखारते हैं — वे कुंडली को नहीं बदलते, और ज़रूरत होने पर परामर्श, कानूनी सलाह या सुरक्षा सहायता का विकल्प नहीं हैं।',
          },
          {
            id:       'ethical-interpretation',
            label:    'Ethical Interpretation',
            label_hi: 'नैतिक व्याख्या',
            body:     'An ethical interpretation of marital astrology requires balance and empathy. It is used to foster self-improvement and informed decisions, never to manipulate, control, or prejudge partners — and never to keep anyone in an unsafe or abusive relationship. Personal safety and each partner’s autonomy come first. The goal is to help the individual understand their own patterns more clearly so they can meet their partner and their relationship with greater maturity and wisdom.',
            body_hi:  'वैवाहिक ज्योतिष की नैतिक व्याख्या के लिए संतुलन और सहानुभूति ज़रूरी है। इसका उपयोग आत्म-सुधार और सोच-समझकर निर्णय लेने के लिए होता है, साथी को नियंत्रित करने, बहकाने या पहले से आँकने के लिए कभी नहीं — और किसी को असुरक्षित या हिंसक रिश्ते में बनाए रखने के लिए भी कभी नहीं। व्यक्तिगत सुरक्षा और हर साथी की स्वतंत्रता सबसे पहले है। उद्देश्य व्यक्ति को अपने पैटर्न बेहतर समझने में मदद करना है, ताकि वह अपने साथी और रिश्ते का अधिक परिपक्वता और समझदारी से सामना कर सके।',
          },
          {
            id:       'summary',
            label:    'Summary',
            label_hi: 'सारांश',
            body:     'Assessing the possibility of separation or divorce through Vedic astrology is an exercise in understanding one\'s own karmic blueprint. By integrating the analysis of houses, planetary Karakas, divisional charts, and Dasha cycles, Jyotisha provides a structured framework for navigating partnership — viewing the chart not as a constraint but as a roadmap for developing the maturity, compassion, and insight necessary to transform a karmic bond into a supportive partnership, or to navigate its dissolution with wisdom.',
            body_hi:  'वैदिक ज्योतिष के माध्यम से अलगाव या तलाक की संभावना का आकलन अपने कार्मिक खाके को समझने का अभ्यास है। भावों, ग्रह कारकों, वर्ग कुंडलियों और दशाओं के विश्लेषण को साथ जोड़कर ज्योतिष साझेदारी को समझने और संभालने का एक व्यवस्थित ढांचा देता है — कुंडली को बंधन के रूप में नहीं, बल्कि एक मार्गदर्शक नक्शे के रूप में देखते हुए।',
          },
        ],
      },
      {
        id:       'faqs',
        title:    'Frequently Asked Questions',
        title_hi: 'अक्सर पूछे जाने वाले प्रश्न',
        layout:   'faq',
        items: [
          {
            id:       'faq-1',
            label:    'Can Vedic astrology predict divorce with certainty?',
            label_hi: 'क्या वैदिक ज्योतिष निश्चितता के साथ तलाक की भविष्यवाणी कर सकता है?',
            body:     'No. Vedic astrology indicates karmic tendencies and challenges, but the ultimate outcome depends on the efforts and maturity of both partners. The chart maps the probability space, not the predetermined destination — conscious, sustained effort can navigate even the most challenging configurations toward a constructive outcome.',
            body_hi:  'नहीं। वैदिक ज्योतिष कार्मिक प्रवृत्तियाँ और चुनौतियाँ दिखाता है, लेकिन अंतिम परिणाम दोनों साथियों के प्रयासों और परिपक्वता पर निर्भर करता है। कुंडली संभावनाओं का दायरा दिखाती है, पहले से तय मंज़िल नहीं।',
          },
          {
            id:       'faq-2',
            label:    'What if my horoscope shows divorce possibilities?',
            label_hi: 'क्या होगा यदि मेरी जन्म कुंडली तलाक की संभावनाएं दिखाती है?',
            body:     'It shows tendencies toward strain, not a verdict. Understanding them can help you work on communication, maturity and mutual support where the relationship is healthy and both partners want to strengthen it. A chart is never a reason to stay in a relationship that is unsafe — personal safety and your own choices come first.',
            body_hi:  'यह तनाव की प्रवृत्तियाँ दिखाता है, कोई फैसला नहीं। इन्हें समझकर आप संवाद, परिपक्वता और आपसी सहयोग पर काम कर सकते हैं, जहाँ रिश्ता स्वस्थ हो और दोनों साथी उसे मज़बूत करना चाहें। कुंडली कभी भी किसी असुरक्षित रिश्ते में बने रहने का कारण नहीं है — व्यक्तिगत सुरक्षा और आपके अपने निर्णय सबसे पहले हैं।',
          },
          {
            id:       'faq-3',
            label:    'Does the Navamsa chart reveal the stability of my marriage?',
            label_hi: 'क्या नवांश चार्ट मेरे विवाह की स्थिरता को प्रकट करता है?',
            body:     'Yes, as an important layer. The Navamsa is an essential tool for understanding the inner reality and structural strength of the marital union. It reveals the qualities and patterns that emerge in the intimacy and sustained reality of marriage — what the Rashi chart alone cannot fully show. A strong Navamsa is one of the strongest supportive indicators of a marriage with genuine endurance, read together with the rest of the chart.',
            body_hi:  'हाँ, एक महत्वपूर्ण स्तर के रूप में। नवांश वैवाहिक संबंध की आंतरिक वास्तविकता और उसकी मज़बूती समझने का आवश्यक साधन है। यह विवाह की निकटता और लंबे साथ में उभरने वाले गुण और पैटर्न दिखाता है — जो अकेली राशि कुंडली पूरी तरह नहीं दिखा सकती। मज़बूत नवांश टिकाऊ विवाह के सबसे प्रबल सहायक संकेतों में से एक है, जिसे बाकी कुंडली के साथ पढ़ा जाता है।',
          },
          {
            id:       'faq-4',
            label:    'Can remedies prevent divorce?',
            label_hi: 'क्या उपाय तलाक को रोक सकते हैं?',
            body:     'Remedies are designed to align your own consciousness, which can shift the dynamics of the union toward harmony and growth. They work on the individual’s inner state — refining the quality of awareness, patience, and empathy brought into the relationship — rather than overriding the partner or the karmic configuration of the charts. They are not a substitute for counselling, legal or safety support.',
            body_hi:  'उपायों का उद्देश्य आपकी अपनी चेतना को संतुलित करना है, जिससे रिश्ते में सामंजस्य और विकास की दिशा में बदलाव आ सकता है। वे व्यक्ति की आंतरिक स्थिति पर काम करते हैं — जागरूकता, धैर्य और सहानुभूति को निखारते हुए — साथी या कुंडली के योगों को बदलकर नहीं। वे परामर्श, कानूनी या सुरक्षा सहायता का विकल्प नहीं हैं।',
          },
          {
            id:       'faq-5',
            label:    'How important is Dasha in analyzing marriage stability?',
            label_hi: 'विवाह स्थिरता के विश्लेषण में दशा कितनी महत्वपूर्ण है?',
            body:     'Dasha is crucial — it defines the karmic themes a couple faces at any given time and the periods when significant marital events are more likely. A difficult Dasha period does not seal the fate of a marriage; it highlights the areas where the greatest conscious effort is currently required. Understanding the Dasha can help partners approach a challenging period with greater awareness rather than reactive conflict.',
            body_hi:  'दशा बहुत महत्वपूर्ण है — यह बताती है कि किसी समय दंपति किन कार्मिक विषयों से गुज़र रहा है और किन अवधियों में महत्वपूर्ण वैवाहिक घटनाओं की संभावना अधिक है। कठिन दशा विवाह का भाग्य तय नहीं करती; यह दिखाती है कि अभी किन क्षेत्रों में सबसे अधिक सचेत प्रयास की ज़रूरत है।',
          },
          {
            id:       'faq-6',
            label:    'What is the significance of the 8th house in marriage stability?',
            label_hi: 'विवाह स्थिरता में 8वें भाव का क्या महत्व है?',
            body:     'The 8th house governs shared assets, deep vulnerabilities, and how the couple handles crises. It is the 2nd from the 7th house, indicating the sustenance of the marriage. A strong 8th house exchange in both charts suggests the capacity to deepen and transform the bond through difficulty; an afflicted 8th house warns of potential hidden crises or sudden upheavals that can destabilize the foundation.',
            body_hi:  'अष्टम भाव साझा संपत्ति, गहरी कमजोरियों और जोड़े के संकटों को संभालने के तरीके को नियंत्रित करता है। यह सप्तम भाव से दूसरा है, जो विवाह की जीविका को इंगित करता है। दोनों कुंडलियों में एक मजबूत अष्टम भाव आदान-प्रदान कठिनाई के माध्यम से बंधन को गहरा और परिवर्तित करने की क्षमता का सुझाव देता है।',
          },
          {
            id:       'faq-7',
            label:    'Is Rahu in the 7th house always negative for stability?',
            label_hi: 'क्या सप्तम भाव में राहु स्थिरता के लिए हमेशा नकारात्मक है?',
            body:     'No. Rahu in the 7th house indicates an intense or unconventional relationship that requires high levels of maturity and trust to navigate — not a partnership that is automatically destined to fail. Such relationships often carry an unusual magnetism and can be highly transformative when both partners commit to understanding the deeper karmic purpose of the union.',
            body_hi:  'नहीं। सप्तम भाव में राहु एक तीव्र या अपरंपरागत संबंध का संकेत देता है, जिसे संभालने के लिए उच्च स्तर की परिपक्वता और विश्वास चाहिए — यह कोई ऐसी साझेदारी नहीं जो अपने आप विफल होने के लिए तय हो। ऐसे रिश्तों में अक्सर असामान्य आकर्षण होता है।',
          },
          {
            id:       'faq-8',
            label:    'Can astrology tell if a divorce is final?',
            label_hi: 'क्या ज्योतिष बता सकता है कि तलाक अंतिम है?',
            body:     'Astrology can show indicators for separation and the periods when they are more active, but it cannot decide whether a separation is final or what a court will decide. Reconciliation can happen when both partners want it and it is safe — but it is a personal choice, not something a chart can require.',
            body_hi:  'ज्योतिष अलगाव के संकेत और वे अवधियाँ दिखा सकता है जब ये संकेत अधिक सक्रिय हों, लेकिन यह तय नहीं कर सकता कि अलगाव अंतिम है या अदालत क्या निर्णय देगी। सुलह तब हो सकती है जब दोनों साथी ऐसा चाहें और यह सुरक्षित हो — लेकिन यह व्यक्तिगत निर्णय है, ऐसा कुछ नहीं जिसे कुंडली अनिवार्य कर सके।',
          },
          {
            id:       'faq-9',
            label:    'How do I use this knowledge ethically?',
            label_hi: 'मैं इस ज्ञान का नैतिक रूप से उपयोग कैसे करूं?',
            body:     'Use this knowledge to foster self-improvement, empathy, and informed decision-making. Astrological insights into marital challenges are tools for developing greater understanding of your own patterns and greater compassion for your partner\'s — never for judging, manipulating, or prejudging another person based on their chart or yours.',
            body_hi:  'इस ज्ञान का उपयोग आत्म-सुधार, सहानुभूति और सूचित निर्णय लेने को बढ़ावा देने के लिए करें। वैवाहिक चुनौतियों में ज्योतिषीय अंतर्दृष्टि आपके अपने पैटर्न की गहरी समझ विकसित करने के उपकरण हैं — किसी अन्य व्यक्ति को उनकी या आपकी कुंडली के आधार पर आंकने, हेरफेर करने या पूर्व-निर्णय करने के लिए कभी नहीं।',
          },
          {
            id:       'faq-10',
            label:    'What is the difference between marital stress and a legal divorce?',
            label_hi: 'वैवाहिक तनाव और कानूनी तलाक में क्या अंतर है?',
            body:     'Marital stress is the friction, distance or conflict a couple experiences — and it is what astrological indicators describe, as tendencies. A legal divorce is a formal decision made by people and courts under the law. A chart can point to periods of strain; it cannot determine whether a divorce will be filed or granted, or what its terms will be.',
            body_hi:  'वैवाहिक तनाव वह टकराव, दूरी या मतभेद है जिसे दंपति अनुभव करता है — और ज्योतिषीय संकेत इसी को प्रवृत्तियों के रूप में बताते हैं। कानूनी तलाक कानून के तहत व्यक्तियों और अदालतों द्वारा लिया गया औपचारिक निर्णय है। कुंडली तनाव की अवधियाँ दिखा सकती है; यह तय नहीं कर सकती कि तलाक का मामला दायर होगा या स्वीकार होगा, या उसकी शर्तें क्या होंगी।',
          },
        ],
      },
    ],
    // The Divorce Possibility Report is the landing's primary card (_landing.ts); no duplicate bottom report CTA.
    ctas: [],
  },

  aiMetadata: {
    searchIntent:  'informational',
    difficulty:    'beginner',
    authorityLevel: 'standard',
  },

  schemaSignals: {
    expertise: 'Authored by Vedic astrologers specializing in marital stability, separation Yogas, and Navamsa analysis.',
  },

  authority: {
    reviewStatus:   'not-reviewed',
    contentVersion: 1,
  },

  publishing: {
    isIndexable:     false,
    isSearchEnabled: false,
    visibility:      'private',
  },

}
