import type { DomainTopic } from '@/lib/domains/_shared/domain-topic.types'

export const marriedLife: DomainTopic = {

  identity: {
    id:         'marriage-astrology:married-life',
    slug:       'married-life',
    title:      'Married Life in Vedic Astrology: A Complete Guide',
    title_hi:   'वैदिक ज्योतिष में वैवाहिक जीवन',
    domain:     'astrology',
    subdomain:  'marriage-astrology',
    category:   'marriage',
    entityType: 'concept',
    status:     'draft',
  },

  routing: {
    canonicalPath: '/marriage-astrology/married-life',
    breadcrumbs: [
      { label: 'Home',               label_hi: 'होम',             href: '/' },
      { label: 'Marriage Astrology', label_hi: 'विवाह ज्योतिष',  href: '/marriage-astrology' },
      { label: 'Married Life',       label_hi: 'वैवाहिक जीवन',   href: '/marriage-astrology/married-life' },
    ],
  },

  seo: {
    metaTitle:       'Married Life in Vedic Astrology: Houses & Timing',
    metaDescription: 'Explore how Vedic astrology assesses married life through the 7th house, Navamsa, and Dasha cycles — a guide to harmony, challenges, and karmic growth.',
    robots:          'noindex,follow',
  },

  hero: {
    headline:    'Married Life in Vedic Astrology: Your Karmic Roadmap',
    headline_hi: 'वैदिक ज्योतिष में वैवाहिक जीवन: आपका कार्मिक रोडमैप',
    subtext:     'Vedic astrology views married life as a profound karmic union. Discover how houses, planetary karakas, the Navamsa chart, and Dasha cycles reveal the harmony, challenges, and spiritual evolution within your marriage.',
    subtext_hi:  'वैदिक ज्योतिष वैवाहिक जीवन को एक गहन कार्मिक मिलन के रूप में देखता है। जानिए कैसे भाव, ग्रह कारक, नवांश चार्ट और दशा चक्र आपके विवाह में सद्भाव, चुनौतियों और आध्यात्मिक विकास को प्रकट करते हैं।',
  },

  taxonomy: {
    tags:        ['married-life', 'vedic-astrology', '7th-house', 'navamsa', 'darakaraka', 'dasha', 'marital-harmony', 'marriage-yogas'],
    keywords:    ['married life vedic astrology', 'married life astrology', 'marital harmony astrology', '7th house marriage', 'navamsa married life', 'dasha marriage', 'marriage yogas'],
    keywords_hi: ['वैदिक ज्योतिष में वैवाहिक जीवन', 'वैवाहिक जीवन ज्योतिष', 'विवाह योग', 'सप्तम भाव विवाह'],
    hubPriority: 'standard',
  },

  content: {
    contentTemplate: 'concept',
    contentBlocks: [
      {
        id:       'introduction',
        title:    'Introduction',
        title_hi: 'परिचय',
        layout:   'list',
        items: [
          {
            id:       'karmic-foundation',
            label:    'Marriage as a Karmic Sacrament',
            label_hi: 'एक कार्मिक संस्कार के रूप में विवाह',
            body:     'In Vedic astrology, or Jyotisha Vedanga, marriage is regarded as one of the most significant Samskaras (sacraments) of life. It is not merely a social contract but a profound karmic union, deeply rooted in the concept of Rina-anubandha — the debts and bonds carried forward from previous lifetimes. As a limb of the Vedas, Jyotisha serves as a map to understand these karmic blueprints. Assessing the quality, harmony, and evolution of married life is ultimately a search for understanding the mirror that will reflect one\'s own karmic patterns.',
            body_hi:  'वैदिक ज्योतिष, या ज्योतिषा वेदांग में, विवाह को जीवन के सबसे महत्वपूर्ण संस्कारों में से एक माना जाता है। यह केवल एक सामाजिक अनुबंध नहीं है, बल्कि एक गहन कार्मिक मिलन है, जो ऋण-अनुबंध की अवधारणा में गहराई से निहित है — पिछले जन्मों से आगे ले जाए गए ऋण और बंधन। वेदों के एक अंग के रूप में, ज्योतिषा इन कार्मिक खाकों को समझने के लिए एक नक्शे के रूप में कार्य करता है।',
          },
          {
            id:       'what-married-life-means',
            label:    'What Married Life Means in Jyotisha',
            label_hi: 'ज्योतिषा में वैवाहिक जीवन का अर्थ',
            body:     'Married life in Jyotisha is a dynamic process — a transformative journey where two souls converge to navigate their individual and shared Prarabdha Karma (past karma). It is defined not by the static event of marriage but by the ongoing evolution of the relationship. It encompasses harmony — the degree of alignment between the temperaments of the partners; challenges — the karmic friction points designed for personal and collective growth; evolution — the capacity of the union to foster spiritual maturity; and longevity and stability — the durability of the bond over time.',
            body_hi:  'ज्योतिषा में वैवाहिक जीवन एक गतिशील प्रक्रिया है — एक परिवर्तनकारी यात्रा जहाँ दो आत्माएं अपने व्यक्तिगत और साझा प्रारब्ध कर्म को नेविगेट करने के लिए एकत्रित होती हैं। यह विवाह की स्थिर घटना से नहीं, बल्कि रिश्ते के निरंतर विकास द्वारा परिभाषित होता है। इसमें सद्भाव, चुनौतियां, विकास और दीर्घायु — ये सभी पहलू समाहित हैं।',
          },
          {
            id:       'promise-vs-reality',
            label:    'Astrological Promise vs. Reality',
            label_hi: 'ज्योतिषीय वादा बनाम वास्तविकता',
            body:     'A foundational pillar of Jyotisha is the distinction between Prarabdha Karma (the "promise" of the birth chart) and the actual manifestation (the "probability"). The birth chart delineates the potential for harmony or conflict. However, the timing, intensity, and specific manner of manifestation are governed by Vimshottari Dasha and Gochar (transits). Marriage is the union of two charts, where the promise in one chart is significantly modulated by the interacting energy of the partner\'s chart. Human free will, exercised with maturity and awareness, acts as a significant modifier.',
            body_hi:  'ज्योतिषा का एक मूलभूत स्तंभ प्रारब्ध कर्म (जन्म कुंडली का "वादा") और वास्तविक अभिव्यक्ति ("संभावना") के बीच का अंतर है। जन्म कुंडली सद्भाव या संघर्ष की क्षमता को रेखांकित करती है। हालांकि, अभिव्यक्ति का समय, तीव्रता और विशिष्ट तरीका विमशोत्तरी दशा और गोचर द्वारा शासित होता है। साथी की कुंडली की परस्पर क्रिया करने वाली ऊर्जा एक कुंडली के वादे को महत्वपूर्ण रूप से संशोधित करती है।',
          },
        ],
      },
      {
        id:       'key-house-analysis',
        title:    'Key House Analysis for Married Life',
        title_hi: 'वैवाहिक जीवन के लिए मुख्य भाव विश्लेषण',
        layout:   'accordion',
        items: [
          {
            id:       'second-house',
            label:    'The 2nd House',
            label_hi: 'द्वितीय भाव',
            body:     'The 2nd House governs the stability of the family lineage and the shared resources of the marriage. A strong 2nd house indicates a stable, family-oriented marital foundation where material security and familial values form the bedrock of the partnership.',
            body_hi:  'द्वितीय भाव पारिवारिक वंश की स्थिरता और विवाह के साझा संसाधनों को नियंत्रित करता है। एक मजबूत द्वितीय भाव एक स्थिर, परिवार-उन्मुख वैवाहिक नींव को इंगित करता है जहाँ भौतिक सुरक्षा और पारिवारिक मूल्य साझेदारी की आधारशिला बनाते हैं।',
          },
          {
            id:       'fourth-house',
            label:    'The 4th House',
            label_hi: 'चतुर्थ भाव',
            body:     'The 4th House reveals the spouse\'s domestic nature and the emotional foundation of the home. It indicates the level of tranquility within the domestic sphere and how well the couple creates a nurturing, secure home environment together.',
            body_hi:  'चतुर्थ भाव जीवनसाथी की घरेलू प्रकृति और घर की भावनात्मक नींव को प्रकट करता है। यह घरेलू क्षेत्र के भीतर शांति के स्तर को इंगित करता है और यह भी कि जोड़ा मिलकर कितनी अच्छी तरह एक पोषणकारी, सुरक्षित घर बनाता है।',
          },
          {
            id:       'fifth-house',
            label:    'The 5th House',
            label_hi: 'पंचम भाव',
            body:     'The 5th House reflects the capacity for romance, creativity, and the shared joy within the marriage, including the aspect of progeny. A well-placed 5th house sustains the spontaneity and warmth that keep the emotional bond alive through the long arc of married life.',
            body_hi:  'पंचम भाव विवाह के भीतर रोमांस, रचनात्मकता और साझी खुशी की क्षमता को दर्शाता है, जिसमें संतान का पहलू भी शामिल है। एक अच्छी तरह से स्थित पंचम भाव उस स्वतःस्फूर्तता और गर्मजोशी को बनाए रखता है जो वैवाहिक जीवन के लंबे चाप में भावनात्मक बंधन को जीवित रखती है।',
          },
          {
            id:       'seventh-house',
            label:    'The 7th House',
            label_hi: 'सप्तम भाव',
            body:     'The 7th House is the direct house of the spouse and the primary house of marriage. It constitutes the primary data point for assessing the nature of the partnership — the sign placed here, its lord, and any planets within it define the foundational quality of the marital bond.',
            body_hi:  'सप्तम भाव जीवनसाथी का प्रत्यक्ष भाव और विवाह का प्राथमिक भाव है। यह साझेदारी की प्रकृति का आकलन करने के लिए प्राथमिक डेटा बिंदु है — यहाँ स्थित राशि, उसका स्वामी और इसमें कोई भी ग्रह वैवाहिक बंधन की मूलभूत गुणवत्ता को परिभाषित करते हैं।',
          },
          {
            id:       'eighth-house',
            label:    'The 8th House',
            label_hi: 'अष्टम भाव',
            body:     'The 8th House governs the intensity of the relationship, shared assets, and the capacity for deep, transformative intimacy. It reveals how the couple handles crisis, navigates major transitions, and whether the bond deepens or fractures under the pressure of life\'s inevitable upheavals.',
            body_hi:  'अष्टम भाव रिश्ते की तीव्रता, साझा संपत्ति और गहरी, परिवर्तनकारी अंतरंगता की क्षमता को नियंत्रित करता है। यह बताता है कि जोड़ा संकट से कैसे निपटता है, प्रमुख परिवर्तनों से कैसे गुजरता है, और जीवन के अपरिहार्य उथल-पुथल के दबाव में बंधन गहरा होता है या टूटता है।',
          },
          {
            id:       'ninth-house',
            label:    'The 9th House',
            label_hi: 'नवम भाव',
            body:     'The 9th House reflects the couple\'s shared philosophical inclinations, belief systems, and overall moral compass, providing a structure for the union. A strong 9th house indicates partners who share a broad ethical and spiritual framework — a powerful stabilizing force in long-term marriage.',
            body_hi:  'नवम भाव जोड़े की साझी दार्शनिक प्रवृत्तियों, विश्वास प्रणालियों और समग्र नैतिक दिशासूचक को दर्शाता है, जो मिलन के लिए एक संरचना प्रदान करता है। एक मजबूत नवम भाव उन साझेदारों को इंगित करता है जो एक व्यापक नैतिक और आध्यात्मिक ढांचा साझा करते हैं — दीर्घकालिक विवाह में एक शक्तिशाली स्थिरीकरण बल।',
          },
          {
            id:       'eleventh-house',
            label:    'The 11th House',
            label_hi: 'एकादश भाव',
            body:     'The 11th House indicates the couple\'s social orientation, shared aspirations, and how they function in their larger community. A well-supported 11th house suggests partners who amplify each other\'s social reach, support mutual goals, and maintain strong networks of friendship and shared purpose.',
            body_hi:  'एकादश भाव जोड़े के सामाजिक अभिविन्यास, साझी आकांक्षाओं और वे अपने बड़े समुदाय में कैसे कार्य करते हैं, इसे इंगित करता है। एक अच्छी तरह से समर्थित एकादश भाव उन साझेदारों का सुझाव देता है जो एक-दूसरे की सामाजिक पहुंच को बढ़ाते हैं और साझे लक्ष्यों का समर्थन करते हैं।',
          },
          {
            id:       'twelfth-house',
            label:    'The 12th House',
            label_hi: 'द्वादश भाव',
            body:     'The 12th House highlights the potential for spiritual evolution, detachment, and sacrifice within the marriage. It can indicate a need for solitude within the partnership, or a relationship whose greatest gift is the gradual dissolution of the ego in the service of something larger than personal desire.',
            body_hi:  'द्वादश भाव विवाह के भीतर आध्यात्मिक विकास, वैराग्य और त्याग की क्षमता पर प्रकाश डालता है। यह साझेदारी के भीतर एकांत की आवश्यकता का संकेत दे सकता है, या एक ऐसे रिश्ते का जिसका सबसे बड़ा उपहार व्यक्तिगत इच्छा से बड़ी किसी चीज की सेवा में अहंकार का क्रमिक विघटन है।',
          },
        ],
      },
      {
        id:       'planetary-analysis',
        title:    'Planetary Influences on Married Life',
        title_hi: 'वैवाहिक जीवन पर ग्रहीय प्रभाव',
        layout:   'accordion',
        items: [
          {
            id:       'sun',
            label:    'Sun',
            label_hi: 'सूर्य',
            body:     'The Sun brings authority and integrity to the marital dynamic. A well-placed Sun creates a sense of dignity and strong moral backbone within the partnership. If afflicted, it may introduce ego-centered tendencies — a need for dominance or recognition that, left unaddressed, creates persistent friction in the relationship.',
            body_hi:  'सूर्य वैवाहिक गतिशीलता में अधिकार और ईमानदारी लाता है। एक अच्छी तरह से स्थित सूर्य साझेदारी के भीतर गरिमा और मजबूत नैतिक रीढ़ की भावना बनाता है। यदि पीड़ित हो, तो यह अहंकार-केंद्रित प्रवृत्तियां पेश कर सकता है — प्रभुत्व या मान्यता की आवश्यकता जो संबोधित न होने पर रिश्ते में लगातार घर्षण पैदा करती है।',
          },
          {
            id:       'moon',
            label:    'Moon',
            label_hi: 'चंद्रमा',
            body:     'The Moon governs emotional connectivity and the nurturing dimension of married life. A strong Moon supports an empathetic, caring bond. A weak or afflicted Moon can introduce moodiness, emotional dependency, or shifting needs that require the partner to develop exceptional patience and attunement.',
            body_hi:  'चंद्रमा भावनात्मक संपर्क और वैवाहिक जीवन के पोषण आयाम को नियंत्रित करता है। एक मजबूत चंद्रमा एक सहानुभूतिपूर्ण, देखभाल करने वाले बंधन का समर्थन करता है। एक कमजोर या पीड़ित चंद्रमा मनोदशा में बदलाव, भावनात्मक निर्भरता या बदलती जरूरतें पेश कर सकता है।',
          },
          {
            id:       'mars',
            label:    'Mars',
            label_hi: 'मंगल',
            body:     'Mars brings passion and courage into the marriage but also the potential for argument or domineering behavior if poorly placed. A strong Mars creates a protective, energetic partner; an afflicted Mars demands conscious work on impulse control and respectful communication to prevent recurring conflict.',
            body_hi:  'मंगल विवाह में जुनून और साहस लाता है, लेकिन यदि खराब स्थित हो तो बहस या दबदबे वाले व्यवहार की संभावना भी। एक मजबूत मंगल एक रक्षात्मक, ऊर्जावान साथी बनाता है; एक पीड़ित मंगल आवेग नियंत्रण पर सचेत कार्य की मांग करता है।',
          },
          {
            id:       'mercury',
            label:    'Mercury',
            label_hi: 'बुध',
            body:     'Mercury shapes the intellectual and communicative quality of the marriage. A well-placed Mercury fosters clear, adaptable communication and intellectual companionship. If weakened, it may manifest as an overly critical or restless partner, creating a climate where misunderstandings accumulate faster than they are resolved.',
            body_hi:  'बुध विवाह की बौद्धिक और संचार गुणवत्ता को आकार देता है। एक अच्छी तरह से स्थित बुध स्पष्ट, अनुकूलनीय संचार और बौद्धिक साहचर्य को बढ़ावा देता है। यदि कमजोर हो, तो यह अत्यधिक आलोचनात्मक या बेचैन साथी के रूप में प्रकट हो सकता है।',
          },
          {
            id:       'jupiter',
            label:    'Jupiter',
            label_hi: 'बृहस्पति',
            body:     'Jupiter is the planet of wisdom, moral guidance, and stability in married life. Its influence on the 7th house or the marital significators tends to bestow a sense of righteousness, generosity, and spiritual depth on the partnership. Jupiter\'s presence is widely regarded as the most benevolent force for sustained marital harmony.',
            body_hi:  'बृहस्पति वैवाहिक जीवन में ज्ञान, नैतिक मार्गदर्शन और स्थिरता का ग्रह है। सप्तम भाव या वैवाहिक संकेतकों पर इसका प्रभाव साझेदारी पर धार्मिकता, उदारता और आध्यात्मिक गहराई की भावना देता है। निरंतर वैवाहिक सद्भाव के लिए बृहस्पति की उपस्थिति को सबसे परोपकारी बल के रूप में व्यापक रूप से माना जाता है।',
          },
          {
            id:       'venus',
            label:    'Venus',
            label_hi: 'शुक्र',
            body:     'Venus represents the romantic and diplomatic dimension of the marital bond. Its strength determines the quality of affection, shared pleasure, and aesthetic harmony within the relationship. An afflicted Venus may introduce self-indulgence, shallow values, or an over-attachment to comfort that eventually strains the deeper bond.',
            body_hi:  'शुक्र वैवाहिक बंधन के रोमांटिक और राजनयिक आयाम का प्रतिनिधित्व करता है। इसकी शक्ति रिश्ते के भीतर स्नेह, साझा आनंद और सौंदर्य सद्भाव की गुणवत्ता निर्धारित करती है। एक पीड़ित शुक्र आत्म-भोग, उथले मूल्यों या आराम के प्रति अत्यधिक आसक्ति पेश कर सकता है।',
          },
          {
            id:       'saturn',
            label:    'Saturn',
            label_hi: 'शनि',
            body:     'Saturn governs maturity, duty, and long-term commitment in marriage. Its influence builds a relationship on a foundation of responsibility and patient endurance. The challenge is that Saturn can introduce emotional coldness or detachment that, without conscious effort to bridge, creates a sense of distance even in a formally intact marriage.',
            body_hi:  'शनि विवाह में परिपक्वता, कर्तव्य और दीर्घकालिक प्रतिबद्धता को नियंत्रित करता है। इसका प्रभाव जिम्मेदारी और धैर्यपूर्ण सहनशक्ति की नींव पर एक रिश्ता बनाता है। चुनौती यह है कि शनि भावनात्मक शीतलता या अलगाव पेश कर सकता है जो सचेत प्रयास के बिना औपचारिक रूप से बरकरार विवाह में भी दूरी की भावना पैदा करता है।',
          },
          {
            id:       'rahu',
            label:    'Rahu',
            label_hi: 'राहु',
            body:     'Rahu brings an unconventional, intense, or karmically charged quality to the marital experience. Relationships under Rahu\'s influence are rarely ordinary — they tend to be highly stimulating, often from different cultural or social backgrounds, and carry a quality of intensity that demands the couple grow into its energy or risk being overwhelmed.',
            body_hi:  'राहु वैवाहिक अनुभव में एक अपरंपरागत, तीव्र या कार्मिक रूप से आवेशित गुणवत्ता लाता है। राहु के प्रभाव में रिश्ते शायद ही कभी सामान्य होते हैं — वे अत्यधिक उत्तेजक होते हैं, अक्सर विभिन्न सांस्कृतिक या सामाजिक पृष्ठभूमि से, और तीव्रता की एक गुणवत्ता के साथ होते हैं।',
          },
          {
            id:       'ketu',
            label:    'Ketu',
            label_hi: 'केतु',
            body:     'Ketu brings a spiritual, intuitive, and often enigmatic dimension to the marriage. Partners under Ketu\'s influence may be deeply insightful yet emotionally detached, creating a marriage where spiritual resonance is high but conventional domestic warmth may need deliberate cultivation.',
            body_hi:  'केतु विवाह में एक आध्यात्मिक, सहज ज्ञान युक्त और अक्सर रहस्यमय आयाम लाता है। केतु के प्रभाव में साथी गहराई से अंतर्दृष्टिपूर्ण फिर भी भावनात्मक रूप से अलग हो सकते हैं, जो एक ऐसा विवाह बनाता है जहाँ आध्यात्मिक अनुनाद उच्च होता है लेकिन पारंपरिक घरेलू गर्मजोशी के सचेत खेती की आवश्यकता हो सकती है।',
          },
          {
            id:       'seventh-lord',
            label:    'The 7th Lord',
            label_hi: 'सप्तम स्वामी',
            body:     'The 7th Lord is the executive power of the 7th house and the single most important indicator for assessing the trajectory of married life. Its dignity, sign placement, and the house it occupies tell the story of whether the partnership brings stability, intense growth, or significant karmic lessons that must be consciously integrated.',
            body_hi:  'सप्तम स्वामी सप्तम भाव की कार्यकारी शक्ति है और वैवाहिक जीवन की दिशा का आकलन करने के लिए सबसे महत्वपूर्ण संकेतक है। इसकी गरिमा, राशि स्थान और वह जिस भाव में है — ये सब यह कहानी बताते हैं कि साझेदारी स्थिरता, तीव्र विकास या महत्वपूर्ण कार्मिक पाठ लाती है।',
          },
          {
            id:       'venus-jupiter-karakas',
            label:    'Venus and Jupiter as Marital Karakas',
            label_hi: 'विवाह कारकों के रूप में शुक्र और बृहस्पति',
            body:     'In marital analysis, Venus (Shukra) represents the capacity for romance and affection, while Jupiter (Guru) represents the capacity for traditional union, wisdom, and stable ethical structure. Their mutual strength and house placement are critical indicators of marital quality — when both are well-placed, the marriage tends toward both affection and wisdom, the two pillars of lasting happiness.',
            body_hi:  'वैवाहिक विश्लेषण में, शुक्र रोमांस और स्नेह की क्षमता का प्रतिनिधित्व करता है, जबकि बृहस्पति पारंपरिक मिलन, ज्ञान और स्थिर नैतिक संरचना की क्षमता का प्रतिनिधित्व करता है। उनकी पारस्परिक शक्ति और भाव स्थान वैवाहिक गुणवत्ता के महत्वपूर्ण संकेतक हैं।',
          },
        ],
      },
      {
        id:       'advanced-tools',
        title:    'Advanced Astrological Tools',
        title_hi: 'उन्नत ज्योतिषीय उपकरण',
        layout:   'cards',
        items: [
          {
            id:       'navamsa-d9',
            label:    'Navamsa (D9)',
            label_hi: 'नवांश (D9)',
            body:     'The Navamsa (D9) chart is the indispensable tool for marital assessment. If the Rashi chart is the external promise, the Navamsa is the internal reality. Analysis of the 7th House and the 7th Lord in the Navamsa provides the conclusive insight into the strength and character of the marital union itself — it is never optional in a serious reading.',
            body_hi:  'नवांश (D9) चार्ट वैवाहिक मूल्यांकन के लिए अपरिहार्य उपकरण है। यदि राशि चार्ट बाहरी वादा है, तो नवांश आंतरिक वास्तविकता है। नवांश में सप्तम भाव और सप्तम स्वामी का विश्लेषण वैवाहिक मिलन की शक्ति और चरित्र में निर्णायक अंतर्दृष्टि प्रदान करता है — यह गंभीर पाठन में कभी वैकल्पिक नहीं होता।',
          },
          {
            id:       'darakaraka',
            label:    'Darakaraka',
            label_hi: 'दारकारक',
            body:     'In Jaimini astrology, the Darakaraka — the planet with the lowest degree in the chart — represents the soul-level archetype of the partner. It defines the "spirit" of the partnership and the specific karmic function this partner serves in the native\'s spiritual progression, pointing to qualities that are karmically destined to enter one\'s life.',
            body_hi:  'जैमिनी ज्योतिष में, दारकारक — कुंडली में सबसे कम डिग्री वाला ग्रह — साथी के आत्मा-स्तरीय आदर्श का प्रतिनिधित्व करता है। यह साझेदारी की "भावना" और उस विशिष्ट कार्मिक कार्य को परिभाषित करता है जो यह साथी जातक की आध्यात्मिक प्रगति में सेवा करता है।',
          },
          {
            id:       'upapada-lagna',
            label:    'Upapada Lagna',
            label_hi: 'उपपद लग्न',
            body:     'The Upapada Lagna represents the marital union as viewed by society. It is crucial for understanding the spouse\'s role in influencing the native\'s public standing and the karmic implications of the union in the social realm — revealing whether the marriage enhances or complicates the native\'s standing in the world.',
            body_hi:  'उपपद लग्न समाज द्वारा देखे जाने वाले वैवाहिक मिलन का प्रतिनिधित्व करता है। यह समाज में जातक की स्थिति पर जीवनसाथी के प्रभाव और मिलन के कार्मिक निहितार्थों को समझने के लिए महत्वपूर्ण है।',
          },
          {
            id:       'marriage-yogas',
            label:    'Marriage Yogas',
            label_hi: 'विवाह योग',
            body:     'Specific planetary combinations — Yogas — indicate the nature of the marital experience. These range from Yogas indicating high levels of harmony and stability to those indicating challenges, delays, or intense transformations. A comprehensive analysis involves assessing multiple Yogas in both the Rashi and Navamsa charts before forming any conclusions.',
            body_hi:  'विशिष्ट ग्रहीय संयोजन — योग — वैवाहिक अनुभव की प्रकृति को इंगित करते हैं। ये उच्च स्तर के सद्भाव और स्थिरता के संकेत देने वाले योगों से लेकर चुनौतियों, देरी या तीव्र परिवर्तनों के संकेत देने वाले योगों तक होते हैं।',
          },
        ],
      },
      {
        id:       'harmony-and-challenges',
        title:    'Indicators of Harmony and Challenges',
        title_hi: 'सद्भाव और चुनौतियों के संकेतक',
        layout:   'list',
        items: [
          {
            id:       'strong-seventh-lord',
            label:    'Strong, Well-placed 7th Lord',
            label_hi: 'मजबूत, सुस्थित सप्तम स्वामी',
            body:     'A strong, well-placed 7th Lord is the most consistent positive indicator for a supportive and harmonious married life. It suggests a partner who brings stability, dignity, and a character that deepens the quality of the union rather than simply enduring it.',
            body_hi:  'एक मजबूत, सुस्थित सप्तम स्वामी एक सहायक और सामंजस्यपूर्ण वैवाहिक जीवन के लिए सबसे सुसंगत सकारात्मक संकेतक है। यह ऐसे साथी का सुझाव देता है जो स्थिरता, गरिमा और एक ऐसा चरित्र लाता है जो मिलन की गुणवत्ता को गहरा करता है।',
          },
          {
            id:       'benefic-influence',
            label:    'Benefics Aspecting the 7th House or 7th Lord',
            label_hi: 'सप्तम भाव या सप्तम स्वामी पर शुभ ग्रहों की दृष्टि',
            body:     'Jupiter or Venus aspecting the 7th house or 7th Lord adds grace, wisdom, and affection to the partnership. Their combined influence is particularly powerful, as it balances the ethical dimension (Jupiter) with the romantic and diplomatic (Venus), creating an environment where the relationship can genuinely flourish.',
            body_hi:  'बृहस्पति या शुक्र का सप्तम भाव या सप्तम स्वामी पर पहलू साझेदारी में अनुग्रह, ज्ञान और स्नेह जोड़ता है। उनका संयुक्त प्रभाव विशेष रूप से शक्तिशाली है, क्योंकि यह नैतिक आयाम (बृहस्पति) को रोमांटिक और राजनयिक (शुक्र) के साथ संतुलित करता है।',
          },
          {
            id:       'mutual-dignity',
            label:    'Mutual Dignity Between 7th Lord and Lagna Lord',
            label_hi: 'सप्तम स्वामी और लग्न स्वामी के बीच परस्पर गरिमा',
            body:     'Mutual dignity between the 7th Lord and Lagna Lord — through aspect, exchange, or conjunction — creates a natural resonance between the self and the partner. This alignment suggests that both individuals are moving in a compatible karmic direction, which is one of the strongest indicators of lasting marital harmony.',
            body_hi:  'सप्तम स्वामी और लग्न स्वामी के बीच परस्पर गरिमा — दृष्टि, विनिमय या संयोजन के माध्यम से — स्वयं और साथी के बीच एक प्राकृतिक अनुनाद बनाती है। यह संरेखण बताता है कि दोनों व्यक्ति एक संगत कार्मिक दिशा में आगे बढ़ रहे हैं।',
          },
          {
            id:       'strong-navamsa',
            label:    'A Strong, Supportive Navamsa Chart',
            label_hi: 'एक मजबूत, सहायक नवांश चार्ट',
            body:     'A strong Navamsa chart — where the 7th Lord is well-placed and the overall chart is free from severe afflictions — confirms that the inner reality of the marriage matches its outer promise. Without this confirmation, even a strong Rashi chart may mask underlying fragility.',
            body_hi:  'एक मजबूत नवांश चार्ट — जहाँ सप्तम स्वामी अच्छी तरह से स्थित है और समग्र चार्ट गंभीर पीड़ाओं से मुक्त है — पुष्टि करता है कि विवाह की आंतरिक वास्तविकता बाहरी वादे से मेल खाती है। इस पुष्टि के बिना, एक मजबूत राशि चार्ट भी अंतर्निहित नाजुकता को छुपा सकता है।',
          },
          {
            id:       'afflicted-seventh-lord',
            label:    'Severe Affliction of the 7th Lord Without Benefic Support',
            label_hi: 'शुभ ग्रह समर्थन के बिना सप्तम स्वामी की गंभीर पीड़ा',
            body:     'When the 7th Lord is severely afflicted by malefics and receives no relief from benefic aspects, the marriage tends to be characterized by persistent friction, karmic imbalance, or a pattern of conflict that requires sustained, conscious effort to transform rather than merely manage.',
            body_hi:  'जब सप्तम स्वामी पाप ग्रहों द्वारा गंभीर रूप से पीड़ित होता है और शुभ पहलुओं से कोई राहत नहीं मिलती, तो विवाह में लगातार घर्षण, कार्मिक असंतुलन या संघर्ष का एक पैटर्न होता है जिसे केवल प्रबंधित करने के बजाय रूपांतरित करने के लिए निरंतर, सचेत प्रयास की आवश्यकता होती है।',
          },
          {
            id:       'separation-planets',
            label:    'Separation-inducing Planets in the 7th House',
            label_hi: 'सप्तम भाव में अलगाव उत्पन्न करने वाले ग्रह',
            body:     'Certain placements — particularly Saturn\'s separative influence, the Sun\'s ego-driven independence, or Rahu\'s unconventional pull — in the 7th house can introduce emotional distance or periodic withdrawal into the marriage. These are not absolute negatives but karmic signals requiring conscious bridging work.',
            body_hi:  'कुछ स्थितियां — विशेष रूप से शनि का अलगाव प्रभाव, सूर्य की अहंकार-चालित स्वतंत्रता, या राहु का अपरंपरागत खिंचाव — सप्तम भाव में भावनात्मक दूरी या आवधिक वापसी पेश कर सकती हैं। ये पूर्ण नकारात्मकताएं नहीं हैं, बल्कि कार्मिक संकेत हैं जिनके लिए सचेत पुल बनाने की आवश्यकता होती है।',
          },
          {
            id:       'weak-navamsa',
            label:    'A Weak or Afflicted Navamsa Chart',
            label_hi: 'एक कमजोर या पीड़ित नवांश चार्ट',
            body:     'A Navamsa chart where the 7th house is compromised — through debilitation, occupation by malefics, or isolation of the 7th Lord — signals that the deeper, inner layer of the marriage may be under strain regardless of how the Rashi chart appears on the surface.',
            body_hi:  'एक नवांश चार्ट जहाँ सप्तम भाव से समझौता किया गया है — नीच, पाप ग्रहों के कब्जे, या सप्तम स्वामी के अलगाव के माध्यम से — संकेत देता है कि राशि चार्ट कैसा भी दिखे, विवाह की गहरी, आंतरिक परत दबाव में हो सकती है।',
          },
          {
            id:       'elemental-imbalance',
            label:    'Significant Elemental Imbalances Between Partner Charts',
            label_hi: 'साझेदार कुंडलियों के बीच महत्वपूर्ण तात्विक असंतुलन',
            body:     'Major imbalances in the elemental representation (fire, earth, air, water) between the charts of two partners create natural friction in emotional expression and communication style. Identifying these imbalances early allows the couple to develop conscious adaptation strategies rather than being blindsided by recurring misunderstandings.',
            body_hi:  'दो साझेदारों की कुंडलियों के बीच तात्विक प्रतिनिधित्व (अग्नि, पृथ्वी, वायु, जल) में प्रमुख असंतुलन भावनात्मक अभिव्यक्ति और संचार शैली में प्राकृतिक घर्षण पैदा करते हैं। इन असंतुलनों को जल्दी पहचानने से जोड़े को सचेत अनुकूलन रणनीतियां विकसित करने की अनुमति मिलती है।',
          },
        ],
      },
      {
        id:       'timing-and-stability',
        title:    'Timing, Stability and Compatibility',
        title_hi: 'समय, स्थिरता और अनुकूलता',
        layout:   'checklist',
        items: [
          {
            id:       'dasha-analysis',
            label:    'Dasha Analysis',
            label_hi: 'दशा विश्लेषण',
            body:     'Marriage occurs within the window of Dasha cycles. The Mahadasha and Antardasha lords active at the time of marriage significantly influence the type of relationship one experiences and the tone of the union during that period — determining whether the opening phase is marked by expansion, duty, intensity, or spiritual searching.',
            body_hi:  'विवाह दशा चक्रों की खिड़की के भीतर होता है। विवाह के समय सक्रिय महादशा और अंतर्दशा स्वामी उस संबंध के प्रकार और उस अवधि के दौरान मिलन के स्वर को महत्वपूर्ण रूप से प्रभावित करते हैं — यह निर्धारित करते हुए कि प्रारंभिक चरण विस्तार, कर्तव्य, तीव्रता या आध्यात्मिक खोज द्वारा चिह्नित है।',
          },
          {
            id:       'transit-influence',
            label:    'Transit Influence',
            label_hi: 'गोचर प्रभाव',
            body:     'Transits of slow-moving planets through the 7th house or over the 7th Lord trigger major events in marital life. Jupiter brings growth and traditional stabilization; Saturn tests endurance and reveals the underlying structural integrity of the bond; Rahu and Ketu bring unexpected karmic turns that often accelerate the couple\'s evolution.',
            body_hi:  'धीमी गति से चलने वाले ग्रहों का सप्तम भाव से या सप्तम स्वामी पर गोचर वैवाहिक जीवन में प्रमुख घटनाओं को ट्रिगर करता है। बृहस्पति विकास और पारंपरिक स्थिरीकरण लाता है; शनि सहनशक्ति की परीक्षा लेता है; राहु और केतु अप्रत्याशित कार्मिक मोड़ लाते हैं।',
          },
          {
            id:       'long-term-stability',
            label:    'Long-term Marriage Stability',
            label_hi: 'दीर्घकालिक विवाह स्थिरता',
            body:     'Longevity and stability are evaluated by assessing the overall strength of the 7th house, the 7th Lord, the 8th house (mangalya), and the Navamsa. A stable marriage requires a balance of duty, affection, and shared values — all of which are reflected in the chart\'s structural strength and the couple\'s ongoing conscious choices.',
            body_hi:  'दीर्घायु और स्थिरता का मूल्यांकन सप्तम भाव, सप्तम स्वामी, अष्टम भाव (मांगल्य) और नवांश की समग्र शक्ति का आकलन करके किया जाता है। एक स्थिर विवाह के लिए कर्तव्य, स्नेह और साझे मूल्यों के संतुलन की आवश्यकता होती है।',
          },
          {
            id:       'communication-compatibility',
            label:    'Communication and Emotional Compatibility',
            label_hi: 'संचार और भावनात्मक अनुकूलता',
            body:     'Compatibility goes beyond superficial attraction. It involves understanding the communication and emotional styles of both partners, which are revealed by the placement of Mercury and the Moon in both charts. Partners who differ sharply in Mercury-Moon orientation benefit most from learning each other\'s language for expressing needs.',
            body_hi:  'अनुकूलता सतही आकर्षण से परे है। इसमें दोनों साझेदारों की संचार और भावनात्मक शैलियों को समझना शामिल है, जो दोनों कुंडलियों में बुध और चंद्रमा की स्थिति द्वारा प्रकट होती हैं। बुध-चंद्रमा अभिविन्यास में तीव्र रूप से भिन्न साझेदार एक-दूसरे की जरूरतों को व्यक्त करने की भाषा सीखने से सर्वाधिक लाभ उठाते हैं।',
          },
        ],
      },
      {
        id:       'guidance-and-ethics',
        title:    'Remedies, Misconceptions and Ethical Use',
        title_hi: 'उपाय, भ्रांतियां और नैतिक उपयोग',
        layout:   'list',
        items: [
          {
            id:       'vedic-remedies',
            label:    'Traditional Vedic Remedies',
            label_hi: 'पारंपरिक वैदिक उपाय',
            body:     'Traditional Jyotisha remedies aim to align the native\'s consciousness with higher archetypes, fostering a state of mind conducive to harmony. This includes cultivating a Sattvic (harmonious) lifestyle, acts of service and charity to balance planetary energies, and meditative focus using traditional planetary mantras. Remedies work from the inside out — they refine the individual\'s inner state, which in turn shifts the quality of the marital dynamic.',
            body_hi:  'पारंपरिक ज्योतिषा उपाय जातक की चेतना को उच्च आदर्शों के साथ संरेखित करने का लक्ष्य रखते हैं, जो सद्भाव के अनुकूल मन की स्थिति को बढ़ावा देता है। इसमें सात्विक जीवनशैली विकसित करना, ग्रहीय ऊर्जाओं को संतुलित करने के लिए सेवा और दान के कार्य, और पारंपरिक ग्रह मंत्रों का उपयोग करके ध्यानात्मक फोकस शामिल है।',
          },
          {
            id:       'misconception-perfect-match',
            label:    '"There is Only One Perfect Match"',
            label_hi: '"केवल एक सही साथी होता है"',
            body:     'Jyotisha suggests multiple potential karmic partners may exist within one\'s life; the quality of the union is built through conscious effort and maturity, not by finding a mythically perfect person. The chart indicates the nature of partnership that one is karmically inclined toward, not a single predetermined individual.',
            body_hi:  'ज्योतिषा सुझाव देता है कि एक के जीवन में कई संभावित कार्मिक साथी हो सकते हैं; मिलन की गुणवत्ता सचेत प्रयास और परिपक्वता के माध्यम से बनाई जाती है, न कि एक पौराणिक रूप से परिपूर्ण व्यक्ति खोजकर। कुंडली उस साझेदारी की प्रकृति को इंगित करती है जिसकी ओर कोई कार्मिक रूप से झुका हुआ है।',
          },
          {
            id:       'misconception-hard-aspects',
            label:    '"Hard Aspects Equal a Failed Marriage"',
            label_hi: '"कठिन पहलू विफल विवाह के बराबर हैं"',
            body:     'Challenges in the marriage chart often indicate the most intense areas for karmic growth rather than inevitable failure. Some of the most transformative and ultimately fulfilling marriages are those that have navigated significant astrological tension, because that tension is the very crucible in which both partners are refined.',
            body_hi:  'विवाह कुंडली में चुनौतियां अक्सर अपरिहार्य विफलता के बजाय कार्मिक विकास के लिए सबसे तीव्र क्षेत्रों को इंगित करती हैं। कुछ सबसे परिवर्तनकारी और अंततः संतुष्टिदायक विवाह वे हैं जिन्होंने महत्वपूर्ण ज्योतिषीय तनाव को नेविगेट किया है।',
          },
          {
            id:       'misconception-chart-absolute',
            label:    '"The Chart is Absolute"',
            label_hi: '"कुंडली पूर्ण है"',
            body:     'The chart is the karmic baseline, not an absolute prison. Daily actions, conscious choices, and the sustained effort both partners bring to the relationship are the primary architects of the marriage\'s actual quality. Astrology maps the terrain; the partners decide how they walk it.',
            body_hi:  'कुंडली कार्मिक आधार रेखा है, पूर्ण बाधा नहीं। दैनिक कार्य, सचेत विकल्प और दोनों साझेदारों द्वारा रिश्ते में लाया गया निरंतर प्रयास विवाह की वास्तविक गुणवत्ता के प्राथमिक वास्तुकार हैं। ज्योतिष भूभाग का नक्शा बनाता है; साझेदार तय करते हैं कि वे इसे कैसे चलते हैं।',
          },
          {
            id:       'ethical-interpretation',
            label:    'Ethical Interpretation',
            label_hi: 'नैतिक व्याख्या',
            body:     'An ethical interpretation of marital astrology requires balance and empathy. It is used to foster self-improvement and informed navigation, never to manipulate, control, or prejudge a partner. The goal is always to support the native\'s growth and the health of the union — astrological knowledge in this domain carries a corresponding responsibility to use it with compassion.',
            body_hi:  'वैवाहिक ज्योतिष की नैतिक व्याख्या के लिए संतुलन और सहानुभूति की आवश्यकता होती है। इसका उपयोग आत्म-सुधार और सूचित नेविगेशन को बढ़ावा देने के लिए किया जाता है, कभी भी साथी को नियंत्रित करने, हेरफेर करने या पूर्व-निर्णय करने के लिए नहीं। लक्ष्य हमेशा जातक के विकास और मिलन के स्वास्थ्य का समर्थन करना है।',
          },
          {
            id:       'summary',
            label:    'Summary',
            label_hi: 'सारांश',
            body:     'Assessing the quality and evolution of married life through Vedic astrology is an exercise in understanding one\'s own karmic blueprint. By integrating the analysis of houses, planetary Karakas, divisional charts like the Navamsa, and the influence of Dasha cycles, Jyotisha provides a structured framework for navigating the profound experience of marital union. The chart serves not as a prison, but as a roadmap for developing the maturity, compassion, and insight necessary to transform a karmic bond into a supportive partnership.',
            body_hi:  'वैदिक ज्योतिष के माध्यम से वैवाहिक जीवन की गुणवत्ता और विकास का आकलन करना किसी की अपनी कार्मिक खाका को समझने का एक अभ्यास है। भावों, ग्रह कारकों, नवांश जैसे विभागीय चार्टों और दशा चक्रों के प्रभाव के विश्लेषण को एकीकृत करके, ज्योतिषा वैवाहिक मिलन के गहन अनुभव को नेविगेट करने के लिए एक संरचित ढांचा प्रदान करता है।',
          },
        ],
      },
      {
        id:       'faqs',
        title:    'Frequently Asked Questions',
        title_hi: 'अक्सर पूछे जाने वाले प्रश्न',
        layout:   'faq',
        items: [
          {
            id:       'faq-1',
            label:    'Can Vedic astrology predict the success of my marriage?',
            label_hi: 'क्या वैदिक ज्योतिष मेरे विवाह की सफलता की भविष्यवाणी कर सकता है?',
            body:     'No. Vedic astrology indicates karmic tendencies and potential challenges, but the success of a marriage depends on the conscious efforts and maturity of both partners. The chart is a map of potential, not a fixed verdict — how that potential is realized is determined by the daily choices both individuals make.',
            body_hi:  'नहीं। वैदिक ज्योतिष कार्मिक प्रवृत्तियों और संभावित चुनौतियों को इंगित करता है, लेकिन विवाह की सफलता दोनों साझेदारों के सचेत प्रयासों और परिपक्वता पर निर्भर करती है। कुंडली क्षमता का एक नक्शा है, न कि एक निश्चित फैसला।',
          },
          {
            id:       'faq-2',
            label:    'What if my horoscope shows marital problems?',
            label_hi: 'क्या होगा यदि मेरी कुंडली वैवाहिक समस्याओं को दर्शाती है?',
            body:     'Challenges indicated in the chart are karmic opportunities, not sentences. Understanding them allows the native to cultivate the necessary maturity to navigate them successfully — often transforming what could have been a source of conflict into the primary arena for personal growth and deepened connection.',
            body_hi:  'कुंडली में इंगित चुनौतियां कार्मिक अवसर हैं, सजाएं नहीं। उन्हें समझने से जातक को उन्हें सफलतापूर्वक नेविगेट करने के लिए आवश्यक परिपक्वता विकसित करने की अनुमति मिलती है — अक्सर जो संघर्ष का स्रोत हो सकता था उसे व्यक्तिगत विकास के प्राथमिक क्षेत्र में बदल देती है।',
          },
          {
            id:       'faq-3',
            label:    'Does the Navamsa chart reveal my partner\'s nature?',
            label_hi: 'क्या नवांश चार्ट मेरे साथी की प्रकृति को प्रकट करता है?',
            body:     'Yes. The Navamsa reveals the deeper, inner nature of the partner and the stability of the marital union itself — the qualities and dynamics that emerge in the intimacy and day-to-day reality of marriage, which may not be visible in the Rashi chart alone.',
            body_hi:  'हां। नवांश साथी की गहरी, आंतरिक प्रकृति और वैवाहिक मिलन की स्थिरता को प्रकट करता है — वे गुण और गतिशीलता जो विवाह की अंतरंगता और दिन-प्रतिदिन की वास्तविकता में उभरती हैं, जो केवल राशि चार्ट में दिखाई नहीं दे सकती।',
          },
          {
            id:       'faq-4',
            label:    'Can remedies fix my marriage?',
            label_hi: 'क्या उपाय मेरे विवाह को ठीक कर सकते हैं?',
            body:     'Remedies are designed to align your own consciousness, which shifts the dynamics and quality of the interaction within the marriage. They are not external interventions that change the partner or the circumstances directly — they refine the internal state of the native, which influences everything in the environment.',
            body_hi:  'उपाय आपकी अपनी चेतना को संरेखित करने के लिए डिज़ाइन किए गए हैं, जो विवाह के भीतर बातचीत की गतिशीलता और गुणवत्ता को बदलता है। वे बाहरी हस्तक्षेप नहीं हैं जो साथी या परिस्थितियों को सीधे बदलते हैं — वे जातक की आंतरिक स्थिति को परिष्कृत करते हैं।',
          },
          {
            id:       'faq-5',
            label:    'How important is Dasha in marriage analysis?',
            label_hi: 'विवाह विश्लेषण में दशा कितनी महत्वपूर्ण है?',
            body:     'Dasha analysis is crucial. It determines the timing of events and the dominant karmic themes the couple navigates at any given time. Even a strongly-promised marriage chart requires a supportive Dasha window for the major events to materialize, and difficult periods often coincide with challenging Dasha combinations.',
            body_hi:  'दशा विश्लेषण महत्वपूर्ण है। यह घटनाओं के समय और उस प्रमुख कार्मिक विषयों को निर्धारित करता है जिन्हें जोड़ा किसी भी समय नेविगेट करता है। यहां तक कि एक दृढ़ता से वादा किए गए विवाह चार्ट के लिए प्रमुख घटनाओं को साकार करने के लिए एक सहायक दशा खिड़की की आवश्यकता होती है।',
          },
          {
            id:       'faq-6',
            label:    'What is the significance of the 8th house in marriage?',
            label_hi: 'विवाह में 8वें भाव का क्या महत्व है?',
            body:     'The 8th house governs shared assets, the intensity of intimacy, and the transformative aspects of the union — how the couple navigates major crises, deep vulnerabilities, and the hidden dimensions of the relationship. A strong 8th house indicates the capacity for profound bonding under pressure.',
            body_hi:  'अष्टम भाव साझा संपत्ति, अंतरंगता की तीव्रता और मिलन के परिवर्तनकारी पहलुओं को नियंत्रित करता है — जोड़ा प्रमुख संकटों, गहरी कमजोरियों और रिश्ते के छिपे हुए आयामों से कैसे निपटता है। एक मजबूत अष्टम भाव दबाव में गहरे बंधन की क्षमता को इंगित करता है।',
          },
          {
            id:       'faq-7',
            label:    'Is Rahu in the 7th house always negative for marriage?',
            label_hi: 'क्या सप्तम भाव में राहु विवाह के लिए हमेशा नकारात्मक है?',
            body:     'No. Rahu in the 7th house indicates an unusual, intense, or karmically transformative relationship rather than a simply negative one. The quality of the outcome depends heavily on the overall dignity of the 7th Lord and the support available from benefic aspects or a strong Navamsa chart.',
            body_hi:  'नहीं। सप्तम भाव में राहु केवल नकारात्मक के बजाय एक असामान्य, तीव्र या कार्मिक रूप से परिवर्तनकारी संबंध को इंगित करता है। परिणाम की गुणवत्ता काफी हद तक सप्तम स्वामी की समग्र गरिमा और शुभ पहलुओं या एक मजबूत नवांश चार्ट से उपलब्ध समर्थन पर निर्भर करती है।',
          },
          {
            id:       'faq-8',
            label:    'Can astrology tell me if I will have a love or arranged marriage?',
            label_hi: 'क्या ज्योतिष मुझे बता सकता है कि मेरा प्रेम विवाह होगा या व्यवस्थित?',
            body:     'Astrology can show the nature of the partnership and the likely circumstances of meeting — for example, a strong 5th house suggests romance-driven attraction, while a strong 9th house suggests family-mediated processes — but not with absolute certainty. Multiple factors and the individual\'s own choices ultimately determine the form the union takes.',
            body_hi:  'ज्योतिष साझेदारी की प्रकृति और मिलने की संभावित परिस्थितियों को दिखा सकता है — उदाहरण के लिए, एक मजबूत पंचम भाव रोमांस-चालित आकर्षण का सुझाव देता है, जबकि एक मजबूत नवम भाव पारिवारिक-मध्यस्थ प्रक्रियाओं का — लेकिन पूर्ण निश्चितता के साथ नहीं।',
          },
          {
            id:       'faq-9',
            label:    'How do I use this knowledge ethically?',
            label_hi: 'मैं इस ज्ञान का नैतिक रूप से उपयोग कैसे करूं?',
            body:     'Use astrological knowledge of married life to foster self-improvement, empathy, and informed decision-making — never to control, manipulate, or judge a partner. The purpose is to approach the relationship with greater wisdom and realistic expectations, and to identify opportunities for growth rather than ammunition for conflict.',
            body_hi:  'वैवाहिक जीवन के ज्योतिषीय ज्ञान का उपयोग आत्म-सुधार, सहानुभूति और सूचित निर्णय लेने को बढ़ावा देने के लिए करें — कभी भी साथी को नियंत्रित करने, हेरफेर करने या न्याय करने के लिए नहीं। उद्देश्य अधिक ज्ञान और यथार्थवादी अपेक्षाओं के साथ रिश्ते के पास पहुंचना है।',
          },
          {
            id:       'faq-10',
            label:    'Is compatibility analysis the same as predicting marriage success?',
            label_hi: 'क्या अनुकूलता विश्लेषण विवाह सफलता की भविष्यवाणी के समान है?',
            body:     'No. Compatibility analysis is a snapshot of current alignment between two charts, whereas predicting success requires a deep understanding of ongoing karmic evolution — how both partners grow, adapt, and choose over time. Compatibility creates the conditions for success; sustained conscious effort builds it.',
            body_hi:  'नहीं। अनुकूलता विश्लेषण दो कुंडलियों के बीच वर्तमान संरेखण का एक स्नैपशॉट है, जबकि सफलता की भविष्यवाणी के लिए निरंतर कार्मिक विकास की गहरी समझ की आवश्यकता होती है — दोनों साथी समय के साथ कैसे बढ़ते, अनुकूलन करते और चुनते हैं। अनुकूलता सफलता की स्थितियां बनाती है; निरंतर सचेत प्रयास इसे बनाता है।',
          },
        ],
      },
    ],
    ctas: [],
  },

  aiMetadata: {
    searchIntent:   'informational',
    difficulty:     'beginner',
    authorityLevel: 'standard',
  },

  schemaSignals: {
    expertise: 'Authored by Vedic astrologers specializing in married life, Navamsa analysis, marriage yogas, and Dasha-based timing.',
  },

  authority: {
    reviewStatus:   'not-reviewed',
    contentVersion: 1,
  },

  publishing: {
    isIndexable:     false,
    isSearchEnabled: false,
    visibility:      'private',
  },

}
