import type { DomainTopic } from '@/lib/domains/_shared/domain-topic.types'

export const spouseNature: DomainTopic = {

  identity: {
    id:         'marriage-astrology:spouse-nature',
    slug:       'spouse-nature',
    title:      'Spouse Nature in Vedic Astrology: Houses & Planets',
    title_hi:   'वैदिक ज्योतिष में जीवनसाथी का स्वभाव',
    domain:     'astrology',
    subdomain:  'marriage-astrology',
    category:   'marriage',
    entityType: 'concept',
    status:     'draft',
  },

  routing: {
    canonicalPath: '/marriage-astrology/spouse-nature',
    breadcrumbs: [
      { label: 'Home',               label_hi: 'होम',                    href: '/' },
      { label: 'Marriage Astrology', label_hi: 'विवाह ज्योतिष',          href: '/marriage-astrology' },
      { label: 'Spouse Nature',      label_hi: 'जीवनसाथी का स्वभाव',    href: '/marriage-astrology/spouse-nature' },
    ],
  },

  seo: {
    metaTitle:       'Spouse Nature in Vedic Astrology: Complete Guide',
    metaDescription: 'Discover how Vedic astrology reveals your spouse\'s nature through the 7th house, planetary karakas, Navamsa, and Darakaraka for clearer understanding.',
    robots:          'noindex,follow',
  },

  hero: {
    headline:    'Spouse Nature in Vedic Astrology: Your Complete Guide',
    headline_hi: 'वैदिक ज्योतिष में जीवनसाथी का स्वभाव: एक संपूर्ण मार्गदर्शिका',
    subtext:     'Vedic astrology offers profound insights into your future spouse\'s temperament, values, and relationship patterns through the 7th house, planetary karakas, Navamsa, and Darakaraka — helping you understand your partner before and during marriage.',
    subtext_hi:  'वैदिक ज्योतिष 7वें भाव, ग्रह कारकों, नवांश और दारकारक के माध्यम से आपके जीवनसाथी के स्वभाव, मूल्यों और संबंध पैटर्न में गहरी अंतर्दृष्टि प्रदान करता है — विवाह से पहले और दौरान आपके साथी को समझने में सहायता करता है।',
  },

  taxonomy: {
    tags:        ['spouse-nature', 'vedic-astrology', '7th-house', 'navamsa', 'darakaraka', 'venus', 'jupiter', 'karaka'],
    keywords:    ['spouse nature vedic astrology', 'spouse nature astrology', '7th house spouse', 'navamsa spouse nature', 'darakaraka spouse', 'venus spouse astrology', 'jupiter spouse female chart'],
    keywords_hi: ['वैदिक ज्योतिष में जीवनसाथी का स्वभाव', 'जीवनसाथी का स्वभाव ज्योतिष', 'सप्तम भाव जीवनसाथी', 'नवांश जीवनसाथी'],
    hubPriority: 'standard',
  },

  content: {
    contentTemplate: 'concept',
    contentBlocks: [
      {
        id:       'introduction',
        title:    'Introduction',
        title_hi: 'परिचय',
        layout:   'list',
        items: [
          {
            id:       'what-is-spouse-nature',
            label:    'Understanding Spouse Nature in Jyotisha',
            label_hi: 'ज्योतिष में जीवनसाथी के स्वभाव को समझना',
            body:     'Vedic astrology, or Jyotisha, is a profound system designed not merely to predict events but to provide a deeper understanding of the soul\'s journey. Among the most earnest inquiries in astrology is the nature of a future spouse. In Jyotisha, spouse nature encompasses the totality of the partner\'s likely temperament, values, communication style, strengths and challenges, and their natural relationship patterns. Understanding these factors allows individuals to enter a relationship with greater clarity, fostering empathy and informed communication.',
            body_hi:  'वैदिक ज्योतिष, या ज्योतिषा, एक गहन प्रणाली है जो केवल घटनाओं की भविष्यवाणी के लिए नहीं, बल्कि आत्मा की यात्रा की गहरी समझ प्रदान करने के लिए डिज़ाइन की गई है। ज्योतिष में सबसे प्रमुख जिज्ञासाओं में से एक भविष्य के जीवनसाथी का स्वभाव है। ज्योतिषा में, जीवनसाथी का स्वभाव साथी के संभावित स्वभाव, मूल्यों, संचार शैली, शक्तियों और चुनौतियों तथा उनके स्वाभाविक संबंध पैटर्न की समग्रता को समाहित करता है। इन कारकों को समझने से व्यक्ति अधिक स्पष्टता के साथ रिश्ते में प्रवेश कर सकते हैं, सहानुभूति और सूचित संवाद को बढ़ावा देते हैं।',
          },
          {
            id:       'promise-vs-probability',
            label:    'Promise vs. Probability',
            label_hi: 'वादा बनाम संभावना',
            body:     'A critical distinction in Jyotisha is the difference between the "promise" of a chart and the "probability" of manifestation. The birth chart (Rashi Chakra) represents the soul\'s potential or Prarabdha Karma (destined karma). However, the timing, intensity, and manner in which these potentials manifest are governed by Vimshottari Dasha (time cycles) and Gochar (transits). Human free will and the conscious choices made within the context of the partner\'s chart act as significant modifiers. Vedic astrology provides a map of tendencies, not a fixed, inescapable script.',
            body_hi:  'ज्योतिषा में एक महत्वपूर्ण अंतर है — कुंडली के "वादे" और अभिव्यक्ति की "संभावना" के बीच। जन्म कुंडली (राशि चक्र) आत्मा की क्षमता या प्रारब्ध कर्म का प्रतिनिधित्व करती है। हालांकि, इन क्षमताओं के प्रकट होने का समय, तीव्रता और तरीका विमशोत्तरी दशा और गोचर द्वारा नियंत्रित होता है। साथी की कुंडली के संदर्भ में मानवीय स्वतंत्र इच्छा और सचेत विकल्प महत्वपूर्ण संशोधक के रूप में कार्य करते हैं। वैदिक ज्योतिष प्रवृत्तियों का एक नक्शा प्रदान करता है, न कि एक निश्चित, अपरिहार्य लिपि।',
          },
        ],
      },
      {
        id:       'primary-houses',
        title:    'Primary Houses for Spouse Analysis',
        title_hi: 'जीवनसाथी विश्लेषण के प्राथमिक भाव',
        layout:   'accordion',
        items: [
          {
            id:       'seventh-house',
            label:    'The 7th House',
            label_hi: 'सप्तम भाव',
            body:     'The 7th House is the primary indicator of the partner. The sign placed here, the planets residing within, and the condition of the 7th Lord are fundamental to understanding the spouse\'s outward nature, temperament, and the overall quality of the partnership.',
            body_hi:  'सप्तम भाव साथी का प्राथमिक संकेतक है। यहाँ स्थित राशि, इसमें निवास करने वाले ग्रह और सप्तम स्वामी की स्थिति — ये सभी जीवनसाथी के बाहरी स्वभाव, मनोवृत्ति और साझेदारी की समग्र गुणवत्ता को समझने के लिए मौलिक हैं।',
          },
          {
            id:       'second-house',
            label:    'The 2nd House',
            label_hi: 'द्वितीय भाव',
            body:     'The 2nd House represents the family, resources, and nourishment. A strong 2nd house in the spouse\'s potential indicates someone who values stability, is grounded in family traditions, and is likely to be a dependable provider within the domestic sphere.',
            body_hi:  'द्वितीय भाव परिवार, संसाधनों और पोषण का प्रतिनिधित्व करता है। जीवनसाथी की संभावना में एक मजबूत द्वितीय भाव किसी ऐसे व्यक्ति को इंगित करता है जो स्थिरता को महत्व देता है, पारिवारिक परंपराओं में दृढ़ है और घरेलू क्षेत्र में एक विश्वसनीय प्रदाता होने की संभावना है।',
          },
          {
            id:       'fourth-house',
            label:    'The 4th House',
            label_hi: 'चतुर्थ भाव',
            body:     'The 4th House represents the spouse\'s domestic orientation, their emotional foundation, and their relationship with their own mother and home environment. It reveals how comfortable they are with intimacy, their need for security, and how they create a sense of home.',
            body_hi:  'चतुर्थ भाव जीवनसाथी के घरेलू अभिमुखीकरण, उनकी भावनात्मक नींव और उनकी माँ तथा घर के वातावरण के साथ उनके संबंध का प्रतिनिधित्व करता है। यह बताता है कि वे अंतरंगता से कितने सहज हैं, उनकी सुरक्षा की आवश्यकता और वे घर का बोध कैसे बनाते हैं।',
          },
          {
            id:       'fifth-house',
            label:    'The 5th House',
            label_hi: 'पंचम भाव',
            body:     'The 5th House represents the spouse\'s creativity, intellect, and capacity for devotion or romance. A strong 5th house indicates a partner who brings joy, warmth, and a playful spirit into the relationship, and who values genuine emotional connection.',
            body_hi:  'पंचम भाव जीवनसाथी की रचनात्मकता, बुद्धि और भक्ति या रोमांस की क्षमता का प्रतिनिधित्व करता है। एक मजबूत पंचम भाव ऐसे साथी को इंगित करता है जो रिश्ते में खुशी, गर्मजोशी और चंचल भावना लाता है और वास्तविक भावनात्मक संबंध को महत्व देता है।',
          },
          {
            id:       'eighth-house',
            label:    'The 8th House',
            label_hi: 'अष्टम भाव',
            body:     'The 8th House indicates the spouse\'s capacity for deep transformation, their hidden vulnerabilities, and their approach to shared assets or intimacy. It reveals the intensity they bring to relationships and how they navigate profound emotional or financial challenges.',
            body_hi:  'अष्टम भाव जीवनसाथी की गहरे परिवर्तन की क्षमता, उनकी छिपी हुई कमजोरियों और साझा संपत्ति या अंतरंगता के प्रति उनके दृष्टिकोण को इंगित करता है। यह बताता है कि वे रिश्तों में कितनी तीव्रता लाते हैं और गहरी भावनात्मक या वित्तीय चुनौतियों से कैसे निपटते हैं।',
          },
          {
            id:       'ninth-house',
            label:    'The 9th House',
            label_hi: 'नवम भाव',
            body:     'The 9th House reflects the spouse\'s belief system, philosophical bent, and their overall wisdom. A prominent 9th house indicates a partner who is drawn to higher knowledge, spiritual or ethical values, and who brings a broad, expansive worldview to the partnership.',
            body_hi:  'नवम भाव जीवनसाथी की विश्वास प्रणाली, दार्शनिक झुकाव और उनकी समग्र बुद्धि को दर्शाता है। एक प्रमुख नवम भाव ऐसे साथी को इंगित करता है जो उच्च ज्ञान, आध्यात्मिक या नैतिक मूल्यों की ओर आकर्षित होता है और साझेदारी में एक व्यापक, विस्तृत विश्वदृष्टि लाता है।',
          },
          {
            id:       'eleventh-house',
            label:    'The 11th House',
            label_hi: 'एकादश भाव',
            body:     'The 11th House represents the spouse\'s social circle, their aspirations, and their ability to fulfill the shared goals of the marriage. A strong 11th house suggests a partner who is socially connected, ambitious, and oriented toward the long-term fulfilment of mutual desires.',
            body_hi:  'एकादश भाव जीवनसाथी के सामाजिक दायरे, उनकी आकांक्षाओं और विवाह के साझे लक्ष्यों को पूरा करने की उनकी क्षमता का प्रतिनिधित्व करता है। एक मजबूत एकादश भाव ऐसे साथी का सुझाव देता है जो सामाजिक रूप से जुड़ा हुआ, महत्वाकांक्षी और पारस्परिक इच्छाओं की दीर्घकालिक पूर्ति की ओर उन्मुख है।',
          },
          {
            id:       'twelfth-house',
            label:    'The 12th House',
            label_hi: 'द्वादश भाव',
            body:     'The 12th House highlights the spouse\'s capacity for detachment, their hidden nature, and their spiritual potential. It can indicate a partner who is introspective, drawn to solitude, or spiritually inclined — and also reveals the quality of intimacy and the private face of the relationship.',
            body_hi:  'द्वादश भाव जीवनसाथी की वैराग्य की क्षमता, उनकी छिपी हुई प्रकृति और उनकी आध्यात्मिक क्षमता पर प्रकाश डालता है। यह ऐसे साथी को इंगित कर सकता है जो आत्मनिरीक्षण में लीन, एकांत की ओर आकर्षित या आध्यात्मिक रूप से झुका हुआ है — और रिश्ते की अंतरंगता तथा निजी पहलू की गुणवत्ता भी बताता है।',
          },
        ],
      },
      {
        id:       'planet-wise-analysis',
        title:    'Planet-wise Analysis of Spouse Nature',
        title_hi: 'जीवनसाथी के स्वभाव का ग्रह-वार विश्लेषण',
        layout:   'accordion',
        items: [
          {
            id:       'sun-surya',
            label:    'Sun (Surya)',
            label_hi: 'सूर्य (सूर्य)',
            body:     'The Sun brings authority and radiance to the spouse\'s personality. The spouse may be confident, dignified, or naturally commanding. A well-placed Sun suggests a partner with strong leadership qualities, integrity, and vitality. If afflicted, there may be a tendency toward arrogance or a persistent need for recognition and control within the relationship.',
            body_hi:  'सूर्य जीवनसाथी के व्यक्तित्व में अधिकार और तेज लाता है। जीवनसाथी आत्मविश्वासी, गरिमामय या स्वाभाविक रूप से प्रभावशाली हो सकता है। एक अच्छी तरह से स्थित सूर्य मजबूत नेतृत्व गुणों, ईमानदारी और जीवन शक्ति वाले साथी का सुझाव देता है। यदि पीड़ित हो, तो अहंकार या रिश्ते में निरंतर पहचान और नियंत्रण की आवश्यकता की प्रवृत्ति हो सकती है।',
          },
          {
            id:       'moon-chandra',
            label:    'Moon (Chandra)',
            label_hi: 'चंद्रमा (चंद्र)',
            body:     'The Moon shapes a nurturing, emotionally sensitive, and receptive spouse. A strong Moon suggests a partner who is deeply caring, intuitive, and capable of creating a harmonious home environment. If the Moon is weak or afflicted, emotional instability or over-dependency may emerge, making consistency in the relationship more challenging.',
            body_hi:  'चंद्रमा एक पोषण करने वाले, भावनात्मक रूप से संवेदनशील और ग्रहणशील जीवनसाथी को आकार देता है। एक मजबूत चंद्रमा ऐसे साथी का सुझाव देता है जो गहराई से देखभाल करने वाला, सहज ज्ञान युक्त और एक सामंजस्यपूर्ण घरेलू वातावरण बनाने में सक्षम है। यदि चंद्रमा कमजोर या पीड़ित हो, तो भावनात्मक अस्थिरता या अत्यधिक निर्भरता उभर सकती है।',
          },
          {
            id:       'mars-mangala',
            label:    'Mars (Mangala)',
            label_hi: 'मंगल (मंगल)',
            body:     'Mars lends the spouse an assertive, energetic, and passionate nature. A well-positioned Mars suggests a partner who is protective, courageous, and highly motivated. If Mars is afflicted, impulsivity, aggression, or an argumentative nature may surface, requiring patience and clear boundaries to maintain harmony in the relationship.',
            body_hi:  'मंगल जीवनसाथी को एक जोरदार, ऊर्जावान और भावुक स्वभाव प्रदान करता है। एक अच्छी तरह से स्थित मंगल ऐसे साथी का सुझाव देता है जो रक्षात्मक, साहसी और अत्यधिक प्रेरित है। यदि मंगल पीड़ित हो, तो आवेगशीलता, आक्रामकता या तर्कप्रिय स्वभाव उभर सकता है, जिसके लिए धैर्य और स्पष्ट सीमाओं की आवश्यकता होती है।',
          },
          {
            id:       'mercury-budha',
            label:    'Mercury (Budha)',
            label_hi: 'बुध (बुध)',
            body:     'Mercury brings a communicative, analytical, and intellectually agile quality to the spouse. A strong Mercury indicates a partner who is curious, witty, and an excellent communicator. The challenge lies in a tendency to be overly critical, superficial in emotional matters, or mentally restless, which can make deep emotional settling more difficult.',
            body_hi:  'बुध जीवनसाथी में संवादशील, विश्लेषणात्मक और बौद्धिक रूप से फुर्तीले गुण लाता है। एक मजबूत बुध ऐसे साथी को इंगित करता है जो जिज्ञासु, विनोदी और एक उत्कृष्ट संवादकर्ता है। चुनौती अत्यधिक आलोचनात्मक होने, भावनात्मक मामलों में उथला या मानसिक रूप से बेचैन होने की प्रवृत्ति में है।',
          },
          {
            id:       'jupiter-guru',
            label:    'Jupiter (Guru)',
            label_hi: 'बृहस्पति (गुरु)',
            body:     'Jupiter bestows wisdom, generosity, and ethical depth on the spouse\'s character. A well-placed Jupiter suggests a partner who is a guide and mentor within the relationship, deeply valuing wisdom and moral rectitude. The potential challenge is a tendency toward dogmatism, preachiness, or intellectual arrogance that may need tempering through mutual respect.',
            body_hi:  'बृहस्पति जीवनसाथी के चरित्र में ज्ञान, उदारता और नैतिक गहराई प्रदान करता है। एक अच्छी तरह से स्थित बृहस्पति ऐसे साथी का सुझाव देता है जो रिश्ते में मार्गदर्शक और परामर्शदाता है, ज्ञान और नैतिक सदाचार को गहराई से महत्व देता है। संभावित चुनौती हठधर्मिता, उपदेशात्मकता या बौद्धिक अहंकार की प्रवृत्ति है।',
          },
          {
            id:       'venus-shukra',
            label:    'Venus (Shukra)',
            label_hi: 'शुक्र (शुक्र)',
            body:     'Venus brings artistry, romance, and a love of beauty to the spouse\'s expression. A strong Venus suggests a partner who is loving, graceful, and capable of fostering great harmony and beauty in the partnership. If afflicted or weak, self-indulgence, shallow priorities, or an excessive focus on material comfort may become recurring themes.',
            body_hi:  'शुक्र जीवनसाथी की अभिव्यक्ति में कलात्मकता, रोमांस और सौंदर्य का प्रेम लाता है। एक मजबूत शुक्र ऐसे साथी का सुझाव देता है जो प्रेमपूर्ण, सुशील और साझेदारी में महान सद्भाव और सौंदर्य को बढ़ावा देने में सक्षम है। यदि पीड़ित या कमजोर हो, तो आत्म-भोग, उथली प्राथमिकताएं या भौतिक आराम पर अत्यधिक ध्यान आवर्ती विषय बन सकते हैं।',
          },
          {
            id:       'saturn-shani',
            label:    'Saturn (Shani)',
            label_hi: 'शनि (शनि)',
            body:     'Saturn shapes a mature, disciplined, and serious spouse — often one who is older in spirit or demeanor. A well-placed Saturn indicates a partner who is deeply loyal, hardworking, and patient, building the relationship on a foundation of duty and reliability. Challenges include rigidity, pessimism, or emotional distance that requires conscious effort to bridge.',
            body_hi:  'शनि एक परिपक्व, अनुशासित और गंभीर जीवनसाथी को आकार देता है — अक्सर ऐसा जो आत्मा या आचरण में वरिष्ठ हो। एक अच्छी तरह से स्थित शनि ऐसे साथी को इंगित करता है जो गहराई से वफादार, मेहनती और धैर्यवान है, कर्तव्य और विश्वसनीयता की नींव पर रिश्ता बनाता है। चुनौतियों में कठोरता, निराशावाद या भावनात्मक दूरी शामिल है जिसके लिए सचेत प्रयास की आवश्यकता होती है।',
          },
          {
            id:       'rahu',
            label:    'Rahu',
            label_hi: 'राहु',
            body:     'Rahu may bring an unconventional, intensely ambitious spouse — someone perhaps from a different background, culture, or with a magnetic, unpredictable personality. The strength of Rahu lies in its ability to bring immense success and willingness to break barriers. Its challenge is a potential for obsessiveness, deceitfulness, or an insatiable quality that keeps the partner from feeling settled.',
            body_hi:  'राहु एक अपरंपरागत, तीव्र रूप से महत्वाकांक्षी जीवनसाथी ला सकता है — शायद कोई अलग पृष्ठभूमि, संस्कृति से या चुंबकीय, अप्रत्याशित व्यक्तित्व वाला। राहु की शक्ति अपार सफलता लाने और बाधाओं को तोड़ने की इच्छाशक्ति में निहित है। इसकी चुनौती जुनून, छल-कपट या एक अतृप्त गुण की क्षमता है।',
          },
          {
            id:       'ketu',
            label:    'Ketu',
            label_hi: 'केतु',
            body:     'Ketu brings a spiritually oriented, detached, and often enigmatic quality to the spouse. Their strength lies in profound spiritual insight, non-attachment, and clarity of perception. The challenge is a tendency toward feelings of isolation, restlessness, or difficulty in conventional emotional expression — making intentional emotional communication especially important.',
            body_hi:  'केतु जीवनसाथी में आध्यात्मिक रूप से उन्मुख, विरक्त और अक्सर रहस्यमय गुण लाता है। उनकी शक्ति गहरी आध्यात्मिक अंतर्दृष्टि, अनासक्ति और धारणा की स्पष्टता में निहित है। चुनौती अकेलेपन, बेचैनी या पारंपरिक भावनात्मक अभिव्यक्ति में कठिनाई की प्रवृत्ति है।',
          },
        ],
      },
      {
        id:       'key-indicators',
        title:    'Key Indicators and Divisional Tools',
        title_hi: 'मुख्य संकेतक और विभागीय उपकरण',
        layout:   'cards',
        items: [
          {
            id:       'seventh-lord',
            label:    '7th Lord',
            label_hi: 'सप्तम स्वामी',
            body:     'The 7th Lord is the "ruler" of the partnership. Its placement, sign, and dignity define the primary trajectory of the marriage. In a Kendra (1, 4, 7, 10) it emphasizes the centrality of partnership; in a Dusthana (6, 8, 12) it points to karmic challenges that must be consciously integrated into the relationship.',
            body_hi:  'सप्तम स्वामी साझेदारी का "शासक" है। इसकी स्थिति, राशि और गरिमा विवाह की प्राथमिक दिशा निर्धारित करती है। केंद्र (1, 4, 7, 10) में यह साझेदारी की केंद्रीयता पर जोर देता है; दुस्थान (6, 8, 12) में यह कार्मिक चुनौतियों की ओर इशारा करता है जिन्हें सचेत रूप से एकीकृत किया जाना चाहिए।',
          },
          {
            id:       'venus-male-chart',
            label:    'Venus in Male Charts',
            label_hi: 'पुरुष कुंडली में शुक्र',
            body:     'In a male chart, Venus is the Karaka (significator) for the spouse. Its sign and house placement reveal his idealization of the partner, his expectations for romance, and how he naturally approaches intimacy and affection in the relationship.',
            body_hi:  'पुरुष कुंडली में, शुक्र जीवनसाथी का कारक (संकेतक) है। इसकी राशि और भाव स्थान उसके साथी के आदर्शीकरण, रोमांस की अपेक्षाओं और अंतरंगता के प्रति उसके स्वाभाविक दृष्टिकोण को प्रकट करता है।',
          },
          {
            id:       'jupiter-female-chart',
            label:    'Jupiter in Female Charts',
            label_hi: 'महिला कुंडली में बृहस्पति',
            body:     'In a female chart, Jupiter is the Karaka for the husband or spouse. It reflects her expectations regarding his guidance, wisdom, and the ethical foundation of their union — indicating the qualities she seeks in a long-term partner.',
            body_hi:  'महिला कुंडली में, बृहस्पति पति या जीवनसाथी का कारक है। यह उनके मार्गदर्शन, ज्ञान और उनके मिलन की नैतिक नींव के बारे में उसकी अपेक्षाओं को दर्शाता है — जो गुण वह दीर्घकालिक साथी में चाहती है।',
          },
          {
            id:       'navamsa-d9',
            label:    'Navamsa (D9)',
            label_hi: 'नवांश (D9)',
            body:     'The Navamsa chart is the most critical divisional chart for marriage. While the Rashi chart shows the external manifestation of the spouse, the Navamsa reveals the inner nature of the spouse and the underlying strength and health of the marriage union. The 7th house and 7th Lord in D9 are essential for any authoritative assessment.',
            body_hi:  'नवांश चार्ट विवाह के लिए सबसे महत्वपूर्ण विभागीय चार्ट है। जहाँ राशि चार्ट जीवनसाथी की बाहरी अभिव्यक्ति को दिखाता है, वहाँ नवांश जीवनसाथी की आंतरिक प्रकृति और विवाह मिलन की अंतर्निहित शक्ति और स्वास्थ्य को प्रकट करता है। किसी भी आधिकारिक मूल्यांकन के लिए D9 में सप्तम भाव और सप्तम स्वामी आवश्यक हैं।',
          },
          {
            id:       'darakaraka',
            label:    'Darakaraka',
            label_hi: 'दारकारक',
            body:     'In the Jaimini system, the Darakaraka is the planet with the lowest degree in the chart. It represents the spouse\'s soul-level archetype and the specific Guna (quality) they bring to the relationship — pointing to the deepest layer of the partner\'s intrinsic nature.',
            body_hi:  'जैमिनी प्रणाली में, दारकारक कुंडली में सबसे कम डिग्री वाला ग्रह है। यह जीवनसाथी के आत्मा-स्तरीय आदर्श और वे रिश्ते में जो विशिष्ट गुण लाते हैं उसका प्रतिनिधित्व करता है — साथी की आंतरिक प्रकृति की सबसे गहरी परत को इंगित करता है।',
          },
          {
            id:       'upapada-lagna',
            label:    'Upapada Lagna',
            label_hi: 'उपपद लग्न',
            body:     'The Upapada Lagna is a specialized Arudha point calculated from the 12th house. It represents the nature of the marital union as viewed by the world and its karmic implications, and is crucial for understanding the spouse\'s impact on one\'s social and public life.',
            body_hi:  'उपपद लग्न 12वें भाव से गणना किया गया एक विशेष आरूढ़ बिंदु है। यह दुनिया द्वारा देखे जाने वाले वैवाहिक मिलन की प्रकृति और इसके कार्मिक निहितार्थों का प्रतिनिधित्व करता है, और जीवनसाथी के सामाजिक और सार्वजनिक जीवन पर प्रभाव को समझने के लिए महत्वपूर्ण है।',
          },
          {
            id:       'nakshatra-influence',
            label:    'Nakshatra Influence',
            label_hi: 'नक्षत्र प्रभाव',
            body:     'Nakshatras (lunar mansions) add a layer of specificity beyond the sign and planet. The Nakshatra of the 7th Lord or the Darakaraka reveals the spouse\'s innate character, their primal motivations, and the way they instinctively interact with the world and within the partnership.',
            body_hi:  'नक्षत्र (चंद्र मंशन) राशि और ग्रह से परे विशिष्टता की एक परत जोड़ते हैं। सप्तम स्वामी या दारकारक का नक्षत्र जीवनसाथी के जन्मजात चरित्र, उनकी प्राथमिक प्रेरणाओं और दुनिया के साथ तथा साझेदारी के भीतर उनके सहज बातचीत के तरीके को प्रकट करता है।',
          },
          {
            id:       'dasha-influence',
            label:    'Dasha Influence',
            label_hi: 'दशा प्रभाव',
            body:     'Marriage occurs within the window of Dasha (time cycles). The Mahadasha and Antardasha lords active at the time of meeting or marriage significantly influence the type of person one is attracted to and the overall tone of the relationship during that cycle.',
            body_hi:  'विवाह दशा (समय चक्र) की खिड़की के भीतर होता है। मिलने या विवाह के समय सक्रिय महादशा और अंतर्दशा स्वामी उस व्यक्ति के प्रकार को महत्वपूर्ण रूप से प्रभावित करते हैं जिसकी ओर कोई आकर्षित होता है और उस चक्र के दौरान रिश्ते के समग्र स्वर को।',
          },
          {
            id:       'transit-influence',
            label:    'Transit Influence',
            label_hi: 'गोचर प्रभाव',
            body:     'Transits of slow-moving planets — Jupiter, Saturn, and Rahu/Ketu — through the 7th house or over the 7th Lord initiate the events that lead to meeting a partner. They modulate the expression of the birth chart\'s potential during specific years, opening or closing windows for partnership.',
            body_hi:  'धीमी गति से चलने वाले ग्रहों — बृहस्पति, शनि और राहु/केतु — का सप्तम भाव से या सप्तम स्वामी पर गोचर उन घटनाओं की शुरुआत करता है जो साथी से मिलने का कारण बनती हैं। वे विशिष्ट वर्षों के दौरान जन्म कुंडली की क्षमता की अभिव्यक्ति को नियंत्रित करते हैं, साझेदारी के लिए खिड़कियां खोलते या बंद करते हैं।',
          },
        ],
      },
      {
        id:       'astrological-combinations',
        title:    'Positive and Challenging Combinations',
        title_hi: 'सकारात्मक और चुनौतीपूर्ण संयोजन',
        layout:   'list',
        items: [
          {
            id:       'strong-seventh-lord',
            label:    'Strong, Well-placed 7th Lord',
            label_hi: 'मजबूत, सुस्थित सप्तम स्वामी',
            body:     'A strong, well-placed 7th Lord is the single most reliable positive indicator for a supportive partnership. It suggests that the spouse will be a meaningful presence — offering stability, alignment, and a character that complements the native\'s own nature.',
            body_hi:  'एक मजबूत, सुस्थित सप्तम स्वामी एक सहायक साझेदारी के लिए सबसे विश्वसनीय सकारात्मक संकेतक है। यह बताता है कि जीवनसाथी एक अर्थपूर्ण उपस्थिति होगा — स्थिरता, संरेखण और जातक की अपनी प्रकृति को पूरक चरित्र प्रदान करेगा।',
          },
          {
            id:       'benefic-seventh-house',
            label:    'Benefics Influencing the 7th House',
            label_hi: 'सप्तम भाव पर शुभ ग्रहों का प्रभाव',
            body:     'Jupiter or Venus aspecting or occupying the 7th house is a positive combination that adds grace, wisdom, and harmony to the partnership. Jupiter\'s influence brings dharmic depth; Venus brings affection and mutual appreciation that sustain the bond through ordinary life.',
            body_hi:  'बृहस्पति या शुक्र का सप्तम भाव पर दृष्टि या स्थिति एक सकारात्मक संयोजन है जो साझेदारी में अनुग्रह, ज्ञान और सद्भाव जोड़ता है। बृहस्पति का प्रभाव धार्मिक गहराई लाता है; शुक्र स्नेह और पारस्परिक प्रशंसा लाता है जो साधारण जीवन में बंधन को बनाए रखता है।',
          },
          {
            id:       'mutual-dignity',
            label:    'Mutual Dignity Between 7th Lord and Lagna Lord',
            label_hi: 'सप्तम स्वामी और लग्न स्वामी के बीच परस्पर गरिमा',
            body:     'When the 7th Lord and Lagna Lord are in a position of mutual dignity — aspecting or exchanging signs — it creates a natural resonance between the self and the partner, fostering shared goals, deep understanding, and an enduring sense of compatibility.',
            body_hi:  'जब सप्तम स्वामी और लग्न स्वामी परस्पर गरिमा की स्थिति में होते हैं — दृष्टि या राशि विनिमय — तो यह स्वयं और साथी के बीच एक प्राकृतिक अनुनाद बनाता है, साझे लक्ष्यों, गहरी समझ और अनुकूलता की स्थायी भावना को बढ़ावा देता है।',
          },
          {
            id:       'darakaraka-harmony',
            label:    'Harmony Between Darakaraka and Key Planets',
            label_hi: 'दारकारक और मुख्य ग्रहों के बीच सामंजस्य',
            body:     'When the Darakaraka is harmoniously aligned with the native\'s own key planets — particularly the Lagna Lord or Moon — it points to a partner whose soul-level qualities resonate deeply with the native\'s own karmic direction and emotional needs.',
            body_hi:  'जब दारकारक जातक के अपने मुख्य ग्रहों — विशेष रूप से लग्न स्वामी या चंद्रमा — के साथ सामंजस्यपूर्ण रूप से संरेखित होता है, तो यह ऐसे साथी की ओर इशारा करता है जिसके आत्मा-स्तरीय गुण जातक की अपनी कार्मिक दिशा और भावनात्मक जरूरतों के साथ गहराई से प्रतिध्वनित होते हैं।',
          },
          {
            id:       'afflicted-seventh-lord',
            label:    'Affliction to the 7th Lord by Malefics',
            label_hi: 'पाप ग्रहों द्वारा सप्तम स्वामी को पीड़ा',
            body:     'Mars, Saturn, or Rahu afflicting the 7th Lord can introduce conflict, delay, or instability into the partnership. These are not absolute negatives but karmic invitations for growth — the challenge lies in developing the patience and discernment needed to navigate a more complex dynamic.',
            body_hi:  'मंगल, शनि या राहु द्वारा सप्तम स्वामी को पीड़ित करने से साझेदारी में संघर्ष, विलंब या अस्थिरता आ सकती है। ये पूर्ण नकारात्मकताएं नहीं हैं, बल्कि विकास के लिए कार्मिक निमंत्रण हैं — चुनौती अधिक जटिल गतिशीलता को नेविगेट करने के लिए आवश्यक धैर्य और विवेक विकसित करने में है।',
          },
          {
            id:       'separation-indicators',
            label:    'Separative Planets in the 7th House',
            label_hi: 'सप्तम भाव में अलगाव के संकेतक ग्रह',
            body:     'Saturn\'s separative influence, Rahu\'s unconventional pull, or the Sun\'s ego-driven independence in or strongly aspecting the 7th house can create emotional distance within marriage. Awareness of these combinations allows for proactive communication and conscious partnership strategies.',
            body_hi:  'शनि का अलगाव प्रभाव, राहु का अपरंपरागत खिंचाव, या सूर्य की अहंकार-चालित स्वतंत्रता सप्तम भाव में या मजबूती से पहलू करते हुए विवाह के भीतर भावनात्मक दूरी बना सकती है। इन संयोजनों के बारे में जागरूकता सक्रिय संचार और सचेत साझेदारी रणनीतियों की अनुमति देती है।',
          },
          {
            id:       'weak-navamsa',
            label:    'Lack of Strength in the Navamsa',
            label_hi: 'नवांश में शक्ति की कमी',
            body:     'Even when the Rashi chart shows a good 7th house, a weak Navamsa — with the 7th Lord debilitated or in a Dusthana — suggests that the deeper, inner nature of the partnership may be strained. The Navamsa must always be consulted alongside the Rashi chart for a complete picture.',
            body_hi:  'यहां तक कि जब राशि चार्ट एक अच्छा सप्तम भाव दिखाता है, एक कमजोर नवांश — जिसमें सप्तम स्वामी नीच का या दुस्थान में है — यह सुझाव देता है कि साझेदारी की गहरी, आंतरिक प्रकृति तनावपूर्ण हो सकती है। एक पूर्ण चित्र के लिए नवांश को हमेशा राशि चार्ट के साथ परामर्श किया जाना चाहिए।',
          },
          {
            id:       'elemental-imbalance',
            label:    'Major Elemental Imbalance Between Partners',
            label_hi: 'भागीदारों के बीच प्रमुख तात्विक असंतुलन',
            body:     'A significant imbalance between the elemental natures (fire, earth, air, water) of the two partners can create friction in communication and emotional expression. Awareness of this imbalance is the first step toward conscious adaptation and bridging the natural gap between different temperamental styles.',
            body_hi:  'दो भागीदारों की मूलभूत प्रकृतियों (अग्नि, पृथ्वी, वायु, जल) के बीच एक महत्वपूर्ण असंतुलन संचार और भावनात्मक अभिव्यक्ति में घर्षण पैदा कर सकता है। इस असंतुलन के बारे में जागरूकता सचेत अनुकूलन और विभिन्न स्वभाव शैलियों के बीच प्राकृतिक अंतर को पाटने की दिशा में पहला कदम है।',
          },
        ],
      },
      {
        id:       'improving-married-life',
        title:    'Factors That Improve Married Life',
        title_hi: 'वैवाहिक जीवन को बेहतर बनाने वाले कारक',
        layout:   'checklist',
        items: [
          {
            id:       'conscious-communication',
            label:    'Conscious Communication',
            label_hi: 'सचेत संचार',
            body:     'Understanding the different communication styles shown by the chart — Mercury-focused versus Moon-focused — allows partners to speak to each other\'s actual needs rather than default assumptions, reducing unnecessary friction and deepening mutual understanding.',
            body_hi:  'कुंडली द्वारा दिखाई गई विभिन्न संचार शैलियों को समझना — बुध-केंद्रित बनाम चंद्रमा-केंद्रित — साझेदारों को डिफ़ॉल्ट धारणाओं के बजाय एक-दूसरे की वास्तविक जरूरतों के लिए बात करने की अनुमति देता है, अनावश्यक घर्षण को कम करता है और पारस्परिक समझ को गहरा करता है।',
          },
          {
            id:       'shared-values',
            label:    'Shared Values and Life Goals',
            label_hi: 'साझा मूल्य और जीवन लक्ष्य',
            body:     'Aligning on core ethical and life goals — reflected through the 9th house and Jupiter — is one of the strongest stabilizers in any marriage. Partners who share a broad philosophical or value framework naturally support each other through the inevitable challenges that life presents.',
            body_hi:  'मुख्य नैतिक और जीवन लक्ष्यों पर संरेखण — नवम भाव और बृहस्पति के माध्यम से परिलक्षित — किसी भी विवाह में सबसे मजबूत स्थिरीकरण में से एक है। जो भागीदार एक व्यापक दार्शनिक या मूल्य ढांचा साझा करते हैं वे स्वाभाविक रूप से जीवन की अपरिहार्य चुनौतियों के माध्यम से एक-दूसरे का समर्थन करते हैं।',
          },
          {
            id:       'respect-for-differences',
            label:    'Respect for Differences',
            label_hi: 'अंतरों के प्रति सम्मान',
            body:     'Acknowledging the inherent nature shown by each partner\'s chart — rather than trying to change it — is a profound act of respect. Each placement represents a specific karmic pattern; accepting it with empathy rather than resistance is the foundation of lasting harmony.',
            body_hi:  'प्रत्येक साथी की कुंडली द्वारा दिखाई गई अंतर्निहित प्रकृति को स्वीकार करना — इसे बदलने की कोशिश करने के बजाय — सम्मान का एक गहरा कार्य है। प्रत्येक स्थिति एक विशिष्ट कार्मिक पैटर्न का प्रतिनिधित्व करती है; प्रतिरोध के बजाय सहानुभूति के साथ इसे स्वीकार करना स्थायी सद्भाव की नींव है।',
          },
          {
            id:       'mutual-growth',
            label:    'Commitment to Mutual Growth',
            label_hi: 'पारस्परिक विकास के प्रति प्रतिबद्धता',
            body:     'Viewing the relationship as a space for both individual and joint evolution — not merely a social institution — transforms marriage from a static arrangement into a living, growing partnership. This orientation is especially powerful when both charts show strong 5th or 9th house placements.',
            body_hi:  'रिश्ते को व्यक्तिगत और संयुक्त विकास दोनों के लिए एक स्थान के रूप में देखना — न केवल एक सामाजिक संस्था — विवाह को एक स्थिर व्यवस्था से एक जीवंत, बढ़ती साझेदारी में बदल देता है। यह अभिविन्यास विशेष रूप से शक्तिशाली होता है जब दोनों कुंडलियों में मजबूत पंचम या नवम भाव की स्थिति होती है।',
          },
        ],
      },
      {
        id:       'misconceptions-and-remedies',
        title:    'Misconceptions, Remedies and Practical Guidance',
        title_hi: 'भ्रांतियां, उपाय और व्यावहारिक मार्गदर्शन',
        layout:   'list',
        items: [
          {
            id:       'one-perfect-match',
            label:    'There is Only One Perfect Match',
            label_hi: 'केवल एक सही साथी होता है',
            body:     'Jyotisha acknowledges that multiple potential partners may exist within one\'s karmic field; the choice depends on the timing of Dashas and transits and the individual\'s own capacity for connection. The chart describes the quality and nature of partnership, not a single predetermined person.',
            body_hi:  'ज्योतिषा स्वीकार करता है कि एक व्यक्ति के कार्मिक क्षेत्र में कई संभावित साथी हो सकते हैं; चुनाव दशाओं और गोचरों के समय और व्यक्ति की संबंध की अपनी क्षमता पर निर्भर करता है। कुंडली साझेदारी की गुणवत्ता और प्रकृति का वर्णन करती है, एक पूर्व-निर्धारित व्यक्ति का नहीं।',
          },
          {
            id:       'chart-is-destiny',
            label:    '"The Chart is Destiny"',
            label_hi: '"कुंडली ही भाग्य है"',
            body:     'The chart is not destiny — it is the starting point. The quality and texture of a relationship is built daily through conscious choices, communication, and the maturity that both partners bring. Astrology maps the potential; how fully that potential is realized depends entirely on human effort and will.',
            body_hi:  'कुंडली भाग्य नहीं है — यह शुरुआती बिंदु है। एक रिश्ते की गुणवत्ता और बनावट सचेत विकल्पों, संचार और दोनों साझेदारों द्वारा लाई गई परिपक्वता के माध्यम से प्रतिदिन बनाई जाती है। ज्योतिष क्षमता का नक्शा बनाता है; वह क्षमता कितनी पूरी तरह से महसूस होती है यह पूरी तरह से मानवीय प्रयास और इच्छाशक्ति पर निर्भर करती है।',
          },
          {
            id:       'hard-aspects-bad',
            label:    '"Hard Aspects Mean a Bad Marriage"',
            label_hi: '"कठिन पहलू खराब विवाह का संकेत है"',
            body:     'Challenging planetary combinations in the marriage houses often represent intense karmic work rather than inevitable failure. When navigated consciously, these patterns frequently lead to the most profound growth, deepest bonds, and the greatest sense of earned partnership between two individuals.',
            body_hi:  'विवाह भावों में चुनौतीपूर्ण ग्रहीय संयोजन अक्सर अपरिहार्य विफलता के बजाय तीव्र कार्मिक कार्य का प्रतिनिधित्व करते हैं। जब सचेत रूप से नेविगेट किया जाता है, तो ये पैटर्न अक्सर सबसे गहन विकास, सबसे गहरे बंधन और दो व्यक्तियों के बीच अर्जित साझेदारी की सबसे बड़ी भावना की ओर ले जाते हैं।',
          },
          {
            id:       'self-reflection-remedy',
            label:    'Remedy: Self-Reflection and Study',
            label_hi: 'उपाय: आत्म-चिंतन और अध्ययन',
            body:     'The most effective remedy is a deep study of one\'s own chart to understand one\'s own contribution to relationship patterns. Recognizing which planetary energies govern one\'s own expectations, reactions, and needs is the first step toward conscious partnership.',
            body_hi:  'सबसे प्रभावी उपाय अपनी कुंडली का गहन अध्ययन है ताकि संबंध पैटर्न में अपने स्वयं के योगदान को समझा जा सके। यह पहचानना कि कौन सी ग्रहीय ऊर्जाएं अपनी अपेक्षाओं, प्रतिक्रियाओं और जरूरतों को नियंत्रित करती हैं, सचेत साझेदारी की दिशा में पहला कदम है।',
          },
          {
            id:       'meditative-practices',
            label:    'Remedy: Meditative Practices and Seva',
            label_hi: 'उपाय: ध्यान अभ्यास और सेवा',
            body:     'Meditative practices, charity, and acts of service directed toward fostering patience, humility, and unconditional love are designed to align one\'s own energy — not to change the partner\'s nature. Remedies work from the inside out, improving one\'s own capacity for relationship.',
            body_hi:  'ध्यान अभ्यास, दान और सेवा के कार्य जो धैर्य, विनम्रता और बिना शर्त प्रेम को बढ़ावा देने की दिशा में हैं, किसी के अपने ऊर्जा को संरेखित करने के लिए डिज़ाइन किए गए हैं — साथी की प्रकृति को बदलने के लिए नहीं। उपाय अंदर से बाहर काम करते हैं, रिश्ते के लिए किसी की अपनी क्षमता में सुधार करते हैं।',
          },
          {
            id:       'mantras-remedy',
            label:    'Remedy: Mantras',
            label_hi: 'उपाय: मंत्र',
            body:     'Authentic, traditional mantras can aid in cultivating the virtues required for a harmonious union — patience, compassion, clarity, and the capacity for genuine devotion. They function as tools for inner calibration, not magical interventions in external circumstances.',
            body_hi:  'प्रामाणिक, पारंपरिक मंत्र एक सामंजस्यपूर्ण मिलन के लिए आवश्यक गुणों को विकसित करने में सहायता कर सकते हैं — धैर्य, करुणा, स्पष्टता और वास्तविक भक्ति की क्षमता। वे बाहरी परिस्थितियों में जादुई हस्तक्षेप के बजाय आंतरिक अंशांकन के उपकरण के रूप में कार्य करते हैं।',
          },
          {
            id:       'self-awareness',
            label:    'Practical: Self-Awareness Before Marriage',
            label_hi: 'व्यावहारिक: विवाह से पहले आत्म-जागरूकता',
            body:     'Understand your own emotional needs and behavioral patterns before evaluating a potential partner. The clarity you bring to the process of choosing a partner is directly proportional to the degree of self-knowledge you have cultivated — this is the most reliable preparation for a lasting union.',
            body_hi:  'किसी संभावित साथी का मूल्यांकन करने से पहले अपनी भावनात्मक जरूरतों और व्यवहार पैटर्न को समझें। आप साथी चुनने की प्रक्रिया में जो स्पष्टता लाते हैं वह सीधे उस आत्म-ज्ञान के अनुपात में है जो आपने विकसित किया है — यह स्थायी मिलन के लिए सबसे विश्वसनीय तैयारी है।',
          },
          {
            id:       'patience-compatibility',
            label:    'Practical: Patience and Broad Compatibility',
            label_hi: 'व्यावहारिक: धैर्य और व्यापक अनुकूलता',
            body:     'Do not rush into a decision based on superficial attraction. Look for broad compatibility in values, communication style, and life vision rather than just physical or transient attraction. These deeper alignments, reflected in the chart\'s structural indicators, are what sustain a partnership through time.',
            body_hi:  'सतही आकर्षण के आधार पर निर्णय लेने में जल्दबाजी न करें। केवल शारीरिक या क्षणिक आकर्षण के बजाय मूल्यों, संचार शैली और जीवन दृष्टि में व्यापक अनुकूलता की तलाश करें। ये गहरे संरेखण, कुंडली के संरचनात्मक संकेतकों में परिलक्षित, समय के साथ साझेदारी को बनाए रखते हैं।',
          },
        ],
      },
      {
        id:       'faqs',
        title:    'Frequently Asked Questions',
        title_hi: 'अक्सर पूछे जाने वाले प्रश्न',
        layout:   'faq',
        items: [
          {
            id:       'faq-1',
            label:    'Can Vedic astrology tell me exactly who I will marry?',
            label_hi: 'क्या वैदिक ज्योतिष मुझे बता सकता है कि मैं किससे शादी करूंगा?',
            body:     'No. Vedic astrology indicates tendencies, archetypes, and timing, but the final choice remains entirely with the individual. The chart maps the quality and nature of the partnership that karmic circumstances favor — it does not name a specific, predetermined person.',
            body_hi:  'नहीं। वैदिक ज्योतिष प्रवृत्तियों, आदर्शों और समय का संकेत देता है, लेकिन अंतिम विकल्प पूरी तरह से व्यक्ति के पास रहता है। कुंडली उस साझेदारी की गुणवत्ता और प्रकृति का नक्शा बनाती है जो कार्मिक परिस्थितियां पसंद करती हैं — यह किसी विशिष्ट, पूर्व-निर्धारित व्यक्ति का नाम नहीं लेती।',
          },
          {
            id:       'faq-2',
            label:    'Is it better to have a spouse with a similar chart?',
            label_hi: 'क्या समान कुंडली वाला जीवनसाथी होना बेहतर है?',
            body:     'Not necessarily. Often, complementary energies create a stronger union than identical ones. A person who needs stability paired with a grounded, Saturn-strong partner, or someone whose emotional gaps are met by their partner\'s strengths — these complementary dynamics frequently produce more growth than mirrored charts.',
            body_hi:  'जरूरी नहीं। अक्सर, पूरक ऊर्जाएं समान ऊर्जाओं की तुलना में एक मजबूत मिलन बनाती हैं। एक ऐसा व्यक्ति जिसे एक स्थिर, शनि-मजबूत साथी के साथ स्थिरता की आवश्यकता है, या कोई ऐसा व्यक्ति जिसकी भावनात्मक कमियां उनके साथी की ताकत से पूरी होती हैं — ये पूरक गतिशीलताएं अक्सर समान कुंडलियों की तुलना में अधिक विकास उत्पन्न करती हैं।',
          },
          {
            id:       'faq-3',
            label:    'What if my 7th house indicates challenges?',
            label_hi: 'क्या होगा यदि मेरा सप्तम भाव चुनौतियों का संकेत देता है?',
            body:     'Challenges in the 7th house are not a verdict — they are karmic opportunities for growth. Understanding them early provides a crucial advantage: it helps in developing the maturity, patience, and specific emotional skills needed to navigate a more complex relational dynamic with wisdom rather than resistance.',
            body_hi:  'सप्तम भाव में चुनौतियां कोई फैसला नहीं हैं — वे विकास के कार्मिक अवसर हैं। उन्हें जल्दी समझने से एक महत्वपूर्ण लाभ मिलता है: यह प्रतिरोध के बजाय ज्ञान के साथ अधिक जटिल संबंधात्मक गतिशीलता को नेविगेट करने के लिए आवश्यक परिपक्वता, धैर्य और विशिष्ट भावनात्मक कौशल विकसित करने में मदद करता है।',
          },
          {
            id:       'faq-4',
            label:    'Does the Navamsa chart reveal my partner\'s personality?',
            label_hi: 'क्या नवांश चार्ट मेरे साथी के व्यक्तित्व को प्रकट करता है?',
            body:     'Yes. The Navamsa (D9) reveals the deeper, inner nature of the spouse — the qualities that emerge in the intimacy and day-to-day reality of marriage, which may not be apparent in the more outward indicators of the Rashi chart. It also reveals the underlying health and strength of the partnership itself.',
            body_hi:  'हां। नवांश (D9) जीवनसाथी की गहरी, आंतरिक प्रकृति को प्रकट करता है — वे गुण जो विवाह की अंतरंगता और दिन-प्रतिदिन की वास्तविकता में उभरते हैं, जो राशि चार्ट के अधिक बाहरी संकेतकों में स्पष्ट नहीं हो सकते। यह साझेदारी की अंतर्निहित स्वास्थ्य और शक्ति को भी प्रकट करता है।',
          },
          {
            id:       'faq-5',
            label:    'Can remedies change my spouse\'s nature?',
            label_hi: 'क्या उपाय मेरे जीवनसाथी का स्वभाव बदल सकते हैं?',
            body:     'No. Remedies in Vedic astrology are designed to align your own consciousness, not to change another person. As you cultivate greater patience, clarity, and compassion within yourself, the dynamics of the relationship naturally improve — because the quality of any interaction depends on both participants\' inner states.',
            body_hi:  'नहीं। वैदिक ज्योतिष में उपाय आपकी अपनी चेतना को संरेखित करने के लिए डिज़ाइन किए गए हैं, किसी अन्य व्यक्ति को बदलने के लिए नहीं। जैसे-जैसे आप अपने भीतर अधिक धैर्य, स्पष्टता और करुणा विकसित करते हैं, रिश्ते की गतिशीलता स्वाभाविक रूप से सुधरती है — क्योंकि किसी भी बातचीत की गुणवत्ता दोनों प्रतिभागियों की आंतरिक अवस्थाओं पर निर्भर करती है।',
          },
          {
            id:       'faq-6',
            label:    'How important is the Darakaraka?',
            label_hi: 'दारकारक कितना महत्वपूर्ण है?',
            body:     'The Darakaraka is highly significant in Jaimini astrology. It points to the soul-level archetype of the spouse — not just their outer personality but the deepest quality they are karmically designed to bring into your life. Analyzed alongside the 7th house and Navamsa, it provides a layered, nuanced picture of the partner.',
            body_hi:  'दारकारक जैमिनी ज्योतिष में अत्यधिक महत्वपूर्ण है। यह जीवनसाथी के आत्मा-स्तरीय आदर्श की ओर इशारा करता है — न केवल उनका बाहरी व्यक्तित्व बल्कि वह गहरी गुणवत्ता जो वे कार्मिक रूप से आपके जीवन में लाने के लिए डिज़ाइन किए गए हैं। सप्तम भाव और नवांश के साथ विश्लेषण किया गया, यह साथी की एक स्तरीय, सूक्ष्म तस्वीर प्रदान करता है।',
          },
          {
            id:       'faq-7',
            label:    'Can I know the exact time of meeting my spouse?',
            label_hi: 'क्या मैं अपने जीवनसाथी से मिलने का सटीक समय जान सकता हूँ?',
            body:     'Astrology can identify periods of high probability — specific Dasha windows and transit alignments that favor the meeting of a partner — but not usually the exact date or time. Think of it as narrowing a wide river into a specific channel rather than pinpointing a single moment.',
            body_hi:  'ज्योतिष उच्च संभावना की अवधियों की पहचान कर सकता है — विशिष्ट दशा विंडो और गोचर संरेखण जो साथी से मिलने का समर्थन करते हैं — लेकिन आमतौर पर सटीक तारीख या समय नहीं। इसे एक एकल क्षण को इंगित करने के बजाय एक विस्तृत नदी को एक विशिष्ट चैनल में संकुचित करने के रूप में सोचें।',
          },
          {
            id:       'faq-8',
            label:    'What does it mean if my 7th Lord is in the 8th house?',
            label_hi: 'इसका क्या मतलब है यदि मेरा सप्तम स्वामी 8वें भाव में है?',
            body:     'The 7th Lord in the 8th house suggests a karmic journey through deep transformation, intensity, and possibly shared resources or secrets. It often indicates a relationship that requires high levels of trust and a willingness to face the partner\'s — and one\'s own — hidden dimensions. This is a profound placement, not simply a problematic one.',
            body_hi:  'सप्तम स्वामी का 8वें भाव में होना गहरे परिवर्तन, तीव्रता और संभवतः साझा संसाधनों या रहस्यों के माध्यम से एक कार्मिक यात्रा का सुझाव देता है। यह अक्सर ऐसे रिश्ते को इंगित करता है जिसके लिए उच्च स्तर के विश्वास और साथी की — तथा अपनी — छिपी हुई आयामों का सामना करने की इच्छा की आवश्यकता होती है। यह एक गहन स्थिति है, केवल समस्याग्रस्त नहीं।',
          },
          {
            id:       'faq-9',
            label:    'Is Rahu in the 7th house always bad?',
            label_hi: 'क्या सप्तम भाव में राहु हमेशा बुरा होता है?',
            body:     'No. Rahu in the 7th house can indicate a highly unusual, intense, or transformative relationship — one that brings significant growth, ambition, or unconventional fulfilment. The key is the overall dignity of the 7th Lord and the support available from benefic aspects, which determine whether Rahu\'s amplifying energy serves the relationship positively.',
            body_hi:  'नहीं। सप्तम भाव में राहु एक अत्यधिक असामान्य, तीव्र या परिवर्तनकारी रिश्ते का संकेत दे सकता है — जो महत्वपूर्ण विकास, महत्वाकांक्षा या अपरंपरागत पूर्ति लाता है। कुंजी सप्तम स्वामी की समग्र गरिमा और शुभ दृष्टियों से उपलब्ध समर्थन है, जो यह निर्धारित करता है कि राहु की प्रवर्धक ऊर्जा रिश्ते की सकारात्मक सेवा करती है या नहीं।',
          },
          {
            id:       'faq-10',
            label:    'How should I use this knowledge ethically?',
            label_hi: 'मुझे इस ज्ञान का नैतिक रूप से उपयोग कैसे करना चाहिए?',
            body:     'Use astrological knowledge for self-improvement, empathy, and making informed decisions — never to control, judge, or pre-judge a partner. The purpose of understanding spouse nature through astrology is to approach partnership with greater wisdom, compassion, and realistic expectations, not to exercise power over another person\'s life choices.',
            body_hi:  'ज्योतिषीय ज्ञान का उपयोग आत्म-सुधार, सहानुभूति और सूचित निर्णय लेने के लिए करें — कभी भी साथी को नियंत्रित करने, न्याय करने या पूर्व-निर्णय करने के लिए नहीं। ज्योतिष के माध्यम से जीवनसाथी के स्वभाव को समझने का उद्देश्य अधिक ज्ञान, करुणा और यथार्थवादी अपेक्षाओं के साथ साझेदारी के पास पहुंचना है, न कि किसी अन्य व्यक्ति के जीवन विकल्पों पर शक्ति का प्रयोग करना।',
          },
        ],
      },
    ],
    ctas: [],
  },

  aiMetadata: {
    searchIntent:   'informational',
    difficulty:     'beginner',
    authorityLevel: 'standard',
  },

  schemaSignals: {
    expertise: 'Authored by Vedic astrologers specializing in spouse nature, 7th house analysis, Navamsa, and Darakaraka.',
  },

  authority: {
    reviewStatus:   'not-reviewed',
    contentVersion: 1,
  },

  publishing: {
    isIndexable:     false,
    isSearchEnabled: false,
    visibility:      'private',
  },

}
