import type { PlanetInHouseData } from "../types"
import { skeleton } from "./skeleton"

const house2: PlanetInHouseData = {
  ...skeleton(2),
  meta_title: "Venus in 2nd House in Vedic Astrology: Voice, Wealth & Beautiful Possessions | Jyotishasha",
  meta_title_hi: "द्वितीय भाव में शुक्र — वाणी, धन और सुंदर संपत्ति | ज्योतिष आशा",
  meta_description: "Discover how Venus in the 2nd house creates a naturally beautiful speaking voice, a talent for accumulating beautiful possessions, and a deeply sensuous relationship with wealth, family, and material comfort.",
  meta_description_hi: "जानिए द्वितीय भाव में शुक्र कैसे एक स्वाभाविक रूप से सुंदर आवाज़, सुंदर संपत्ति संग्रह की प्रतिभा और धन, परिवार तथा भौतिक आराम के साथ गहरे संवेदनशील संबंध का निर्माण करता है।",
  keywords: [
    "venus in 2nd house",
    "venus in 2nd house vedic astrology",
    "shukra dwitiya bhav",
    "venus 2nd house wealth possessions",
    "venus 2nd house voice family"
  ],
  keywords_hi: [
    "द्वितीय भाव में शुक्र",
    "शुक्र का धन पर प्रभाव",
    "शुक्र द्वितीय भाव में"
  ],
  title: "Venus in 2nd House in Vedic Astrology: Voice, Wealth & Beautiful Possessions",
  title_hi: "द्वितीय भाव में शुक्र: वाणी, धन और सुंदर संपत्ति",
  overview: "Venus in the 2nd house places the planet of beauty, refinement, and aesthetic intelligence into the domain of accumulated resources, the speaking voice, and the early family environment. The effect is a kind of Venusian magnetism that operates through tangible wealth — the capacity not just to earn but to attract beautiful things, to accumulate what is genuinely lovely rather than merely valuable, and to understand the house of possessions as a curated extension of personal identity. These natives do not simply own things; they surround themselves with things that have been chosen according to a specific aesthetic sensibility.\n\nThe voice is one of this placement's most distinctive gifts. The 2nd house governs speech, and Venus here infuses that speech with a quality that is hard to define but immediately recognizable: a musicality, a warmth, a tendency toward word choices that are slightly more poetic than occasion requires, a vocal tone that makes people want to continue listening regardless of what is being said. These natives are often unaware of this gift because it operates below the level of deliberate technique — it is not performance, it is simply how they sound when they speak.\n\nPractitioners observe in these charts a pattern around the early family environment that shapes the adult relationship with wealth in specific ways. In a significant proportion of Venus-in-2nd charts, the native grew up in a family where either beauty and material comfort were present as a norm that the adult struggles to replicate, or where material constraint was compensated by an appreciation of beauty — beautiful things made at home, aesthetics maintained on a small budget, an understanding that the beautiful and the expensive are not the same thing. This early lesson, whatever form it took, becomes the native's private philosophy of wealth.",
  overview_hi: "द्वितीय भाव में शुक्र सौंदर्य और परिष्करण को संचित संसाधनों, बोलने की आवाज़ और प्रारंभिक पारिवारिक वातावरण के क्षेत्र में रखता है। ये न केवल कमाते हैं — वे सुंदर चीज़ें आकर्षित करते हैं, एक क्यूरेटेड सौंदर्य विश्व बनाते हैं।\n\nआवाज़ इस स्थान के सबसे विशिष्ट उपहारों में से एक है — एक संगीतात्मकता, गर्माहट, जो लोगों को सुनते रहने पर मजबूर करती है। अनुभवी ज्योतिषी देखते हैं: प्रारंभिक पारिवारिक वातावरण — चाहे प्रचुर हो या सीमित — धन के प्रति वयस्क दर्शन को आकार देता है।",
  personality: "The personality of a Venus-in-2nd native is organized around value in both its material and immaterial senses. These are people who think about what things are worth — not in the commercial sense of market price, but in the experiential sense of what something adds to the quality of a life. They distinguish between the expensive that is not beautiful and the beautiful that is not expensive with a discernment that most people acquire only through years of deliberate aesthetic education, if they acquire it at all.\n\nThis relationship with value extends to relationships themselves. The 2nd house is also the house of family by blood, and Venus here creates a native who loves their family with a particular kind of sensuous attachment — an appreciation for the family's specific textures, histories, recipes, physical objects, aesthetic traditions, and ways of being together. Even in families where there was conflict or difficulty, Venus in the 2nd tends to produce an adult who preserves the family's beautiful things, who carries the family recipes, who knows where the jewelry came from.\n\nThe 2nd house governs the speaking voice, and what is less commonly noted is that it also governs the choice of words. Venus-in-2nd natives tend toward a more eloquent diction than the surrounding culture, not as performance but as natural preference — they like words that are specific, that have pleasant sounds, that earn their place in a sentence. They often have a gift for the kind of speech that makes a compliment feel genuine rather than formulaic, because they actually mean it and have chosen the right words to say so.\n\nThe shadow of this placement is the confusion of beauty with worth. The native who believes that beautiful things justify their cost regardless of other considerations, or who maintains surface elegance at the expense of financial stability, or who values relationships partly for their aesthetic quality — the partner who looks right, the friend group that photographs well — is operating from Venus-in-2nd's most distorted mode. Material comfort can become so necessary to this native's sense of wellbeing that financial insecurity produces a kind of existential anxiety that far exceeds what the circumstances warrant.",
  personality_hi: "इनका व्यक्तित्व 'मूल्य' के इर्द-गिर्द व्यवस्थित है — भौतिक और अभौतिक दोनों अर्थों में। महंगे-लेकिन-नहीं-सुंदर और सुंदर-लेकिन-महंगे-नहीं के बीच अंतर की उनकी पहचान विशेष है।\n\nपारिवारिक लगाव में सौंदर्यबोध है — व्यंजन, आभूषण, पारिवारिक परंपराएँ। शब्द-चुनाव में भी: ये अधिक वाक्पटु, विशिष्ट और सुखद-ध्वनि वाले शब्द पसंद करते हैं। छाया: सौंदर्य को मूल्य से भ्रमित करना — सुंदर चीज़ें अपनी कीमत को उचित नहीं ठहरातीं।",
  career: "The professional world of Venus-in-2nd natives clusters around the intersection of beauty and value — fields where the native's ability to recognize what is genuinely good, beautiful, or worth acquiring translates into professional judgment that others will pay for. Gemology and jewelry, fine art dealing, luxury real estate, antique dealing, high-end fashion buying, wine and culinary expertise, financial advisory roles for high-net-worth clients, and voice work of all kinds — all fit this placement because they require exactly the kind of aesthetic-value intelligence that Venus in the 2nd provides naturally.\n\nA second cluster uses the voice directly: voice acting, radio and podcast presentation, singing, public speaking, oratory, and therapeutic listening roles where the quality of the voice itself is a professional tool. These natives may not recognize their voice as a professional asset because it has always simply been how they sound; a recording played back to them often produces the surprised recognition that others have been noticing it all along.\n\nThe career arc for Venus in the 2nd often develops through the accumulation of expertise in a specific aesthetic domain — becoming the person who genuinely knows a particular field deeply enough that others seek their judgment. This is different from becoming famous; many Venus-in-2nd professionals have highly localized but very deep authority within their domain, which produces financial security through reputation rather than through scale.\n\nThe professional risk is an over-attachment to financial comfort that limits risk-taking. These natives may stay in situations that pay well and feel aesthetically acceptable long past the point where a change would be beneficial, because the financial security — the knowing that the beautiful life can continue — feels more important than the opportunity that the change represents.",
  career_hi: "सौंदर्य और मूल्य के चौराहे पर पेशेवर क्षेत्र: रत्नशास्त्र, आभूषण, ललित कला, विलासिता रियल एस्टेट, पुरावशेष, उच्च-स्तरीय फैशन खरीद। आवाज़ का उपयोग: वॉयस एक्टिंग, रेडियो, पॉडकास्ट, गायन। करियर एक विशिष्ट सौंदर्य डोमेन में विशेषज्ञता के संचय के माध्यम से विकसित होता है। जोखिम: वित्तीय आराम से लगाव जो परिवर्तन को सीमित करता है।",
  relationships: "In relationships, Venus in the 2nd creates a native whose love is expressed substantially through material giving and aesthetic curation of shared life. This is the person who chooses gifts with exceptional care, who remembers that a partner said once that they loved a particular flower and then fills a table with those flowers six months later for no reason, who understands that the quality of the shared dinner matters as much as what is said at it. Love here is a practice of attention to what is beautiful and what is valued — in the other person, in the relationship's material environment, in the small accumulation of objects that tell the story of a life shared.\n\nThe challenge is that this can be misread as materialism rather than recognized as a love language. A partner who doesn't speak the language of material beauty — who has no relationship to objects, who is indifferent to food or environment or the quality of sensory experience — may miss entirely what is being offered when the native creates a beautiful dinner or gives a gift that required extensive thought. The mismatch is not about depth; it's about the vocabulary through which depth is expressed.\n\nFamily relationships, governed partly by this house, tend to be warm and aesthetically rich when Venus is well-placed: the native creates beautiful family environments, maintains aesthetic traditions, curates the family's shared material culture. There can be tension, however, around money and family inheritance — Venus in the 2nd can produce an acute sensitivity around material possessions within the family, particularly beautiful or historically significant objects, that creates conflict if handled without awareness.\n\nPractitioners note in these charts a recurring pattern in which the native's most lasting relationships develop through shared taste. The friend or partner who said something that revealed an aesthetic sensibility matching the native's, who chose an object or named a preference that signaled they were people who understood beauty in the same key, becomes significant often before any more conventional intimacy has developed. Shared taste is, for this native, a form of recognition.",
  relationships_hi: "रिश्तों में प्रेम भौतिक देने और साझा जीवन के सौंदर्य क्यूरेशन के माध्यम से व्यक्त होता है — असाधारण देखभाल से चुने गए उपहार, सुंदर रात्रिभोज, संयुक्त जीवन की सुंदर सामग्री। यह प्रेम भाषा है, भौतिकवाद नहीं।\n\nचुनौती: ऐसे साथियों के साथ गलतफहमी जो भौतिक सौंदर्य की भाषा नहीं बोलते। परिवार: गर्म और सौंदर्यपूर्ण समृद्ध, लेकिन विरासत वस्तुओं के आसपास तनाव संभव। साझा रुचि के माध्यम से गहरे रिश्ते।",
  health: "Venus in the 2nd house connects the physical body to the quality of what it ingests — and to the quality of what surrounds it in the eating experience. These natives are often genuinely skilled cooks or food appreciators, and their relationship with food can be one of the most pleasant aspects of their daily life. When this is in balance, they eat well, enjoy what they eat, and receive the health benefits that come from genuinely pleasurable, high-quality nourishment. When it goes out of balance, the same pleasure-orientation produces over-indulgence in rich foods, sugar, and the excess comfort that Venus accumulates when its regulatory function weakens.\n\nThe classical Venusian body zone — kidneys, reproductive system, skin — applies here with an additional emphasis on the throat and jaw (2nd house territory), which can manifest as thyroid vulnerabilities, vocal strain, dental issues, or temporomandibular tension in natives who carry stress in the jaw area. The voice, such an asset for this placement, is also a vulnerability: periods of excessive speaking, emotional stress, or physical illness can affect it disproportionately.\n\nThe most effective health approach for this native is making nourishment beautiful. These are people for whom the effort of preparing genuinely good food — fresh ingredients, pleasant preparation, attractive presentation — is not a chore but a pleasure, and when they cook for themselves, they tend to eat better than when they rely on convenience. The practice of a genuinely beautiful, well-prepared meal as a daily ritual is both a health and a wellbeing strategy for this placement.",
  health_hi: "स्वास्थ्य इस बात से जुड़ा है कि शरीर में क्या जाता है और खाने के अनुभव की गुणवत्ता से। संतुलन में: उत्तम पोषण। असंतुलन में: समृद्ध खाद्य और मिठाई का अति-भोग। गले, जबड़े (द्वितीय भाव क्षेत्र) की कमज़ोरियाँ — थायरॉइड, आवाज़ का तनाव, दंत समस्याएँ।\n\nसर्वश्रेष्ठ स्वास्थ्य दृष्टिकोण: पोषण को सुंदर बनाना — ताज़ी सामग्री, सुंदर प्रस्तुति। भोजन एक दैनिक अनुष्ठान के रूप में।",
  spirituality: "Venus in the 2nd house finds the sacred in the material world itself — in the specificity of beautiful things, in the gratitude that arises from genuine enjoyment of what the sensory world offers, and in the recognition that the body's pleasures, properly attended to, are themselves a form of divine gift rather than an obstacle to spiritual development. This is the tradition of bhoga leading toward yoga — the enjoyment of the world as a path toward its transcendence — and these natives often embody this principle more naturally than they realize.\n\nThe specific practices that resonate most include the devotion expressed through beautiful physical objects — creating altars with care, choosing offerings with aesthetic attention, maintaining sacred spaces with the same craft that they bring to their homes. The Lalita tradition in Hinduism, which understands the goddess as the beautiful pleasure of the world, speaks directly to this placement. So does the tradition of sacred food — prasad offered and received with genuine appreciation, the cooking of offerings as a meditative act.\n\nThe spiritual challenge for Venus in the 2nd is the deepening of the relationship with impermanence. Beautiful things do not last. Loved people age and die. Accumulated wealth can be lost. The 2nd house is also associated with what we carry from one life to the next, which in Vedic understanding is not material possession but the accumulated impressions — samskaras — of how we used our senses, what we valued, what we created. The invitation is to hold the beautiful things lightly enough that their loss, when it comes, is grief rather than devastation — to love the beautiful world without requiring it to remain.",
  spirituality_hi: "द्वितीय भाव में शुक्र सांसारिक सौंदर्य में ही पवित्र खोजता है — भोग से योग की ओर। सुंदर वस्तुओं के माध्यम से भक्ति, वेदियों की देखभाल, प्रसाद का आनंद — ये स्वाभाविक आध्यात्मिक मार्ग हैं।\n\nचुनौती: अनित्यता के साथ गहरा रिश्ता। सुंदर चीज़ें नहीं टिकतीं। द्वितीय भाव हमें याद दिलाता है कि एक जीवन से दूसरे जीवन में क्या जाता है — संपत्ति नहीं, बल्कि संस्कार।",
  strengths: [
    "A naturally beautiful and musicially textured speaking voice that draws people into conversation and creates trust and warmth in both personal and professional encounters without the native needing to deliberately cultivate these effects.",
    "An aesthetic intelligence applied to material life — the ability to select, accumulate, and arrange beautiful objects such that homes and personal spaces become genuinely restorative environments rather than functional containers.",
    "A deep knowledge of what things are worth in the experiential sense — the ability to recognize genuine quality, to distinguish the beautiful from the merely expensive, and to teach others to make this distinction.",
    "A gift for meaningful material giving — the selection of gifts with such accuracy that the recipient feels genuinely seen, because the giver noticed something specific about them and found the object that responds to it.",
    "A natural connection to food as culture and pleasure that makes them excellent cooks, discerning diners, and people who understand that shared meals are among the primary ways that humans create intimacy and belonging.",
    "A warm and aesthetically rich relationship with family and family history — the preservation of beautiful traditions, recipes, and objects that gives families a sense of continuity and aesthetic identity that can sustain members across generations.",
    "A professional instinct for value in aesthetic domains — the ability to know what will appreciate, what is genuinely good, and what represents an authentic expression of quality in any domain that involves beauty or material refinement."
  ],
  strengths_hi: [
    "प्राकृतिक रूप से सुंदर और संगीतात्मक आवाज़ जो विश्वास और गर्माहट बनाती है।",
    "भौतिक जीवन पर सौंदर्य बुद्धिमत्ता — सुंदर वस्तुएँ चुनने, संग्रह करने और व्यवस्थित करने की क्षमता।",
    "चीज़ों का अनुभवात्मक मूल्य जानना — असली गुणवत्ता और महंगे के बीच अंतर।",
    "सार्थक भौतिक उपहार देने की प्रतिभा — ऐसे उपहार जो प्राप्तकर्ता को वास्तव में देखा महसूस कराएँ।",
    "भोजन को संस्कृति और आनंद के रूप में समझना — बेहतरीन रसोइए और रात्रिभोज साथी।",
    "पारिवारिक इतिहास के साथ गर्म और सौंदर्यपूर्ण संबंध — परंपराओं और वस्तुओं का संरक्षण।",
    "सौंदर्य डोमेन में मूल्य की व्यावसायिक वृत्ति।"
  ],
  challenges: [
    "A tendency to conflate financial security with existential safety — so that periods of material constraint produce anxiety far exceeding their actual threat, and the pursuit of financial comfort can crowd out other forms of risk and growth.",
    "An over-investment in material possessions as expressions of self that makes loss — whether through theft, damage, financial necessity, or age — register as attacks on identity rather than the ordinary entropy of material life.",
    "A difficulty maintaining financial discipline when beautiful things are available — the acquisition instinct can outrun the budget, particularly in domains where the native's taste and desire are genuinely refined.",
    "A tendency to evaluate relationships partly on the basis of aesthetic compatibility — the partner who looks right, the friend group that understands beauty — that can lead to shallow or materially motivated connections rather than the deep ones Venus in the 2nd ultimately needs.",
    "A voice that is used as a social asset in ways that become habitual before the native's words have been fully examined — the beautiful voice can speak untested things with conviction; learning to slow down what is said, not just how it sounds, is a specific developmental task.",
    "A family-of-origin dynamic around material possessions and inheritance that can become contentious — the native's strong aesthetic opinions about what should be kept, given, or divided may generate friction that more detached family members find disproportionate."
  ],
  challenges_hi: [
    "वित्तीय सुरक्षा को अस्तित्वगत सुरक्षा से जोड़ने की प्रवृत्ति — भौतिक बाधाएँ अत्यधिक चिंता पैदा करती हैं।",
    "स्वयं की अभिव्यक्ति के रूप में संपत्ति में अत्यधिक निवेश।",
    "सुंदर चीज़ें उपलब्ध होने पर वित्तीय अनुशासन बनाए रखने में कठिनाई।",
    "सौंदर्य संगतता के आधार पर रिश्तों का मूल्यांकन करना।",
    "सामाजिक संपत्ति के रूप में आवाज़ का उपयोग — जो कहा जाए उसे धीमा करना सीखना।",
    "परिवार में भौतिक संपत्ति और विरासत के आसपास मतभेद।"
  ],
  faqs: [
    {
      q: "Is Venus in the 2nd house a good placement for wealth?",
      a: "Venus in the 2nd house is generally considered auspicious for material accumulation because Venus is a natural benefic and the 2nd house is the house of accumulated resources. The specific expression depends on Venus's sign, strength, and aspects, but the general tendency is for these natives to attract material prosperity — particularly beautiful, high-quality possessions — through their aesthetic intelligence and natural charm. The wealth may come through beauty-related fields, voice or communication work, or through social connections that Venus facilitates. What is less often noted is that Venus in the 2nd is as much about the quality of what is accumulated as the quantity — these natives tend toward fewer, better things rather than mass accumulation.",
      q_hi: "क्या द्वितीय भाव में शुक्र धन के लिए अच्छी स्थिति है?",
      a_hi: "हाँ, यह आम तौर पर भौतिक संचय के लिए शुभ है। ये लोग सुंदर, उच्च-गुणवत्ता वाली संपत्ति आकर्षित करते हैं। मात्रा से अधिक गुणवत्ता — कम, लेकिन बेहतर चीज़ें।"
    },
    {
      q: "What does Venus in the 2nd house mean for the voice?",
      a: "This is one of the most consistently reported gifts of this placement. Venus in the 2nd house tends to produce a speaking voice that is naturally pleasant, melodious, and warm — a voice that draws people in and creates trust without the native needing to consciously work at it. This can manifest as a gift for singing, for public speaking, for podcast or radio presentation, for voice acting, or simply for the kind of casual conversation that people genuinely enjoy being part of. The voice is often an underutilized professional asset for these natives, who may not be aware that others find it exceptional.",
      q_hi: "आवाज़ के लिए इसका क्या अर्थ है?",
      a_hi: "यह इस स्थान के सबसे सुसंगत उपहारों में से एक है। शुक्र एक स्वाभाविक रूप से सुखद, राग-सम्पन्न आवाज़ देता है जो बिना प्रयास के विश्वास बनाती है। गायन, सार्वजनिक भाषण, पॉडकास्ट — ये इस उपहार की अभिव्यक्तियाँ हैं।"
    },
    {
      q: "How does Venus in the 2nd house affect family relationships?",
      a: "The 2nd house governs the family of origin, and Venus here tends to create warm, aesthetically rich family connections. The native often has a deep appreciation for family traditions, recipes, heirlooms, and the material culture of the family — they tend to be the one who preserves the grandmother's jewelry or knows the family's traditional dishes. The relationship with siblings and parents tends toward affection expressed through shared sensory experience — good meals, beautiful environments, gift-giving. Tension can arise around material inheritance or shared possessions if the native's aesthetic opinions about these objects are stronger than other family members'.",
      q_hi: "परिवार के रिश्तों पर कैसा प्रभाव पड़ता है?",
      a_hi: "परिवार के साथ गर्म, सौंदर्यपूर्ण समृद्ध संबंध। ये पारिवारिक परंपराओं, व्यंजनों और विरासत वस्तुओं को संरक्षित करते हैं। विरासत या साझा संपत्ति के आसपास तनाव संभव।"
    },
    {
      q: "Does Venus in the 2nd house indicate a talent for singing?",
      a: "This placement is one of the classical indicators of vocal talent in Vedic astrology, yes — the 2nd house governs the voice and Venus governs beauty of expression, so the combination tends to produce a naturally pleasant singing voice. Whether this translates into a professional singing career depends on the strength of Venus, the sign it occupies, supporting aspects, and the overall chart pattern. But even when professional singing isn't the path, these natives tend to have voices that others enjoy hearing, and many find that music — whether making it or deeply appreciating it — is a significant source of pleasure and self-expression throughout their lives.",
      q_hi: "क्या यह गायन प्रतिभा का संकेत देता है?",
      a_hi: "हाँ, यह वैदिक ज्योतिष में स्वर प्रतिभा के शास्त्रीय संकेतकों में से एक है। पेशेवर गायन शुक्र की शक्ति और पूरी कुंडली पर निर्भर करता है, लेकिन स्वाभाविक रूप से सुखद आवाज़ आम है।"
    },
    {
      q: "How does Venus in the 2nd house affect spending habits?",
      a: "Venus in the 2nd house creates a native who spends on beauty — not necessarily on expensive things, but on things that are genuinely well-made, aesthetically considered, or sensorially pleasing. They tend to prefer fewer, better possessions over many mediocre ones, and they will spend more than most people would in their financial situation on the things that matter to their sense of beauty. The risk is that this aesthetic spending can outrun financial discipline, particularly when Venus is under stress or when other chart factors amplify the indulgent tendency. These natives benefit from a clear financial framework that preserves space for beauty-spending as a legitimate budgetary category rather than trying to suppress it entirely.",
      q_hi: "खर्च करने की आदतों पर कैसा प्रभाव पड़ता है?",
      a_hi: "ये सुंदरता पर खर्च करते हैं — जरूरी नहीं कि महंगी चीज़ों पर, लेकिन वास्तव में अच्छी तरह से बनी, सौंदर्यपूर्ण रूप से विचारित चीज़ों पर। जोखिम: वित्तीय अनुशासन को पीछे छोड़ना।"
    },
    {
      q: "What are the best careers for Venus in the 2nd house?",
      a: "The careers that suit this placement best use either the aesthetic intelligence — jewelry design, gemology, fine art dealing, luxury retail, antique expertise, interior design, high-end food and wine — or the voice directly: singing, voice acting, podcasting, public speaking, radio, and therapeutic listening roles. A third category uses both: luxury hospitality, brand management for heritage and beauty brands, and advisory roles for high-net-worth clients in financial domains where understanding what is genuinely valuable and beautiful matters.",
      q_hi: "सर्वश्रेष्ठ करियर कौन से हैं?",
      a_hi: "आभूषण डिज़ाइन, रत्नशास्त्र, ललित कला, विलासिता खुदरा, पुरावशेष, आंतरिक डिज़ाइन — या गायन, वॉयस एक्टिंग, पॉडकास्टिंग, सार्वजनिक भाषण।"
    },
    {
      q: "Does Venus in the 2nd house affect relationships with money in a unique way?",
      a: "Yes — the specific quality is that money, for this native, is not abstract. It is concretely and viscerally connected to the experience of beauty, comfort, and sensory quality. These natives know what it feels like when money is available in terms of the difference it makes to their daily sensory experience — the quality of what they eat, what they wear, where they sleep, what they look at. This makes financial security something that is felt in the body rather than tracked in a spreadsheet, which can be motivating or anxiety-producing depending on the native's current situation and the chart's overall signature.",
      q_hi: "धन के साथ संबंध अनूठा कैसे है?",
      a_hi: "इनके लिए धन अमूर्त नहीं है — यह शरीर में महसूस होता है: भोजन की गुणवत्ता, वस्त्र, नींद, दृश्य। यह प्रेरक या चिंता-उत्पादक हो सकता है।"
    },
    {
      q: "What does Venus in the 2nd house say about food?",
      a: "The relationship with food for Venus in the 2nd is among the most pleasurable dimensions of this placement. These natives tend to be genuinely discerning about what they eat — not necessarily in the sense of dietary restriction, but in the sense of preferring good food to convenient food, genuine flavor to processed approximations, and the experience of a meal as a whole event rather than a nutritional transaction. Many are excellent cooks. They understand instinctively that a well-made dish communicates care, culture, and aesthetic sensibility — that cooking is one of the most accessible forms of beauty-making that daily life offers.",
      q_hi: "भोजन के साथ क्या संबंध है?",
      a_hi: "भोजन इस स्थान के सबसे आनंददायक आयामों में से एक है। ये उत्तम, वास्तविक स्वाद वाले भोजन को प्राथमिकता देते हैं। अनेक उत्कृष्ट रसोइए होते हैं।"
    },
    {
      q: "How does this placement affect self-worth and self-esteem?",
      a: "Venus in the 2nd house connects self-worth to value in a way that is double-edged. On one side: these natives often have a genuine and stable sense of their own worth rooted in what they have cultivated — their taste, their skills, their ability to create beauty — which is a healthy foundation for self-esteem. On the other: their sense of worth can become too entangled with external validation through material circumstances, so that financial difficulty, material loss, or an aesthetically inadequate living situation undermines self-esteem in ways that seem disproportionate. The developmental task is building a relationship with self-worth that is grounded in the cultivated inner quality — the taste, the discernment, the ability to create beauty — rather than in the accumulated external beauty that validates it.",
      q_hi: "यह आत्म-मूल्य को कैसे प्रभावित करता है?",
      a_hi: "यह आत्म-मूल्य को मूल्य के साथ जोड़ता है — दोनों तरफ से। स्वस्थ: विकसित स्वाद और कौशल पर आधारित। चुनौती: बाहरी भौतिक परिस्थितियों से अत्यधिक जुड़ाव।"
    },
    {
      q: "What remedies are helpful for Venus in the 2nd house?",
      a: "Remedies for Venus in the 2nd house work well when they engage with the placement's specific domains: keeping fresh white flowers in the home, particularly near the entrance or in the area where the native eats or speaks most; practicing gratitude specifically for the beautiful things in daily life as a regular acknowledgment of what has been given; Friday fasts with white or sweet foods as offerings; the Shukra beej mantra recited on Fridays. For the placement's specific challenge — the anxiety around material security and the identification of self-worth with material wealth — the most targeted remedy is a regular practice of finding beauty in what is present rather than in what is desired: cultivating the eye for what is already beautiful in the native's current circumstances.",
      q_hi: "कौन से उपाय सहायक हैं?",
      a_hi: "घर में ताज़े सफेद फूल, विशेषतः प्रवेश द्वार के पास। दैनिक जीवन की सुंदर चीज़ों के लिए कृतज्ञता। शुक्रवार का उपवास, शुक्र बीज मंत्र।"
    }
  ],
  discoverMore: ["venus-in-2nd-house-vedic-astrology"],
  cta: {
    title: "Understand Your Complete Venus Placement",
    title_hi: "अपनी कुंडली के अनुसार शुक्र का वास्तविक प्रभाव जानें",
    description: "Your birth chart is unique. The effects of Venus in the 2nd House can change significantly depending on its zodiac sign, conjunctions, planetary aspects, retrograde motion, planetary strength, divisional charts, and planetary periods.\n\nGet your personalized PDF report delivered to your email and discover how Venus interacts with every other planet in your Kundali, with practical insights based on your complete birth chart.",
    description_hi: "हर व्यक्ति की जन्म कुंडली अलग होती है।\n\nद्वितीय भाव में शुक्र का वास्तविक प्रभाव उसकी राशि, अन्य ग्रहों के साथ युति, दृष्टि, वक्री स्थिति, ग्रह बल, दशा तथा संपूर्ण कुंडली के आधार पर बदल सकता है।\n\nअपनी कुंडली के अनुसार विस्तृत Personalized PDF Report अपने ईमेल पर प्राप्त करें और जानें कि शुक्र आपकी कुंडली में अन्य ग्रहों के साथ मिलकर आपके जीवन को कैसे प्रभावित करता है।",
    reportSlug: "venus-analysis-report"
  }
}

export default house2
