// app/astrology-methodology/page.tsx
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Astrology Methodology | The Science Behind Jyotishasha Engine",
  description:
    "Understand how Jyotishasha calculates Kundali using ephemeris-based astronomical computation, Lahiri Ayanamsa, Google Places REST location accuracy, and deterministic Vedic rule-based interpretation.",
  alternates: { canonical: "https://www.jyotishasha.com/astrology-methodology" },
  openGraph: {
    title: "Astrology Methodology | Jyotishasha Engine",
    description:
      "A transparent explanation of Jyotishasha’s Kundali calculation method: ephemeris-based astronomy, Lahiri Ayanamsa, location precision, and rule-based Vedic logic.",
    url: "https://www.jyotishasha.com/astrology-methodology",
    siteName: "Jyotishasha",
    type: "article",
    locale: "en_IN",
    images: [
      {
        url: "/og/astrology-methodology-og.jpg",
        width: 1200,
        height: 630,
        alt: "Jyotishasha Astrology Methodology",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Astrology Methodology | Jyotishasha",
    description:
      "How Jyotishasha calculates Kundali: ephemeris-based astronomy, Lahiri Ayanamsa, Google Places precision, and deterministic Vedic rules.",
    images: ["/og/astrology-methodology-og.jpg"],
    creator: "@jyotishasha",
  },
  other: {
    "theme-color": "#4f46e5",
    "application-name": "Jyotishasha",
  },
};

const faqs = [
  {
    q: "How does Jyotishasha ensure the accuracy of planetary positions?",
    a: "Jyotishasha computes planetary longitudes using ephemeris-based astronomical calculation via Python libraries such as Swiss Ephemeris / PyEphem. These follow high-precision ephemeris standards referenced by NASA and other leading astronomical institutions, enabling accurate transit timing and planetary placement.",
  },
  {
    q: "Why is birth location precision so important?",
    a: "In Vedic Astrology, the Ascendant (Lagna) and divisional charts can shift with small changes in location. Jyotishasha validates birth location using Google Places REST API and uses exact latitude–longitude coordinates (not city approximations) to compute Lagna, houses, Nakshatra Pada, and timing-sensitive results with high geographic integrity.",
  },
  {
    q: "Which Ayanamsa does the system use?",
    a: "By default, Jyotishasha uses Lahiri Ayanamsa (Chitra Paksha), the most widely accepted and government-recognized standard in Indian Vedic astrology, to align sidereal planetary positions.",
  },
  {
    q: "Is the astrology content generated by AI?",
    a: "No. Jyotishasha uses a deterministic, rule-based interpretation system. Insights are shown only when classical Jyotish conditions (Yogas, placements, aspects/Drishtis) are mathematically present in the chart—ensuring consistent, justified outputs instead of generic or hallucinated text.",
  },
  {
    q: "How are the Dasha timelines calculated?",
    a: "Jyotishasha computes Vimshottari Dasha based on the Moon’s precise birth-position. Because ephemeris-based calculations are used for the Moon longitude, the Dasha start/end periods and timelines are significantly more accurate than simplified or approximate methods.",
  },
  {
    q: "Does Jyotishasha store my personal birth data?",
    a: "Jyotishasha prioritizes privacy. Birth details are used to generate Kundali calculations and outputs. We do not sell or share sensitive birth data with third parties. Where storage is required for user experience, standard security practices are applied.",
  },
];

function buildFaqSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faqs.map((f) => ({
      "@type": "Question",
      name: f.q,
      acceptedAnswer: {
        "@type": "Answer",
        text: f.a,
      },
    })),
  };
}

function buildPageSchema() {
  return {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "WebPage",
        name: "Astrology Methodology | Jyotishasha Engine",
        url: "https://www.jyotishasha.com/astrology-methodology",
        description:
          "Transparent explanation of Jyotishasha Kundali calculation methodology: ephemeris-based astronomy, Lahiri Ayanamsa, Google Places REST precision, and deterministic Vedic rules.",
        isPartOf: {
          "@type": "WebSite",
          name: "Jyotishasha",
          url: "https://www.jyotishasha.com/",
        },
        about: {
          "@type": "Thing",
          name: "Vedic Astrology Methodology",
        },
      },
      {
        "@type": "Organization",
        name: "Jyotishasha",
        url: "https://www.jyotishasha.com/",
      },
      {
        "@type": "BreadcrumbList",
        itemListElement: [
          {
            "@type": "ListItem",
            position: 1,
            name: "Home",
            item: "https://www.jyotishasha.com/",
          },
          {
            "@type": "ListItem",
            position: 2,
            name: "Astrology Methodology",
            item: "https://www.jyotishasha.com/astrology-methodology",
          },
        ],
      },
    ],
  };
}

export default function AstrologyMethodologyPage() {
  const pageSchema = buildPageSchema();
  const faqSchema = buildFaqSchema();

  return (
    <section className="min-h-screen py-12 px-4 text-white bg-gradient-to-b from-[#0f0c29] via-[#302b63] to-[#24243e]">
      {/* JSON-LD (Page + Breadcrumb + Org) */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(pageSchema) }}
      />
      {/* JSON-LD (FAQPage) */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />

      <div className="max-w-4xl mx-auto bg-white/10 backdrop-blur-lg rounded-3xl shadow-2xl p-8 border border-indigo-500/30">
        <h1 className="text-3xl sm:text-4xl font-bold text-indigo-300 mb-3">
          Methodology: The Science and Engineering Behind Jyotishasha
        </h1>
        <p className="text-gray-200 leading-relaxed">
          A transparent explanation of how Jyotishasha calculates Kundali using
          ephemeris-based astronomy, classical standards, and deterministic
          Vedic logic.
        </p>

        <div className="mt-10 space-y-10">
          {/* Vision */}
          <div>
            <h2 className="text-2xl font-semibold text-indigo-200 mb-3">
              Our Vision: Astrology Meets Mathematical Precision
            </h2>
            <p className="text-gray-200 leading-relaxed">
              At Jyotishasha, we treat Vedic Astrology (Jyotish) not as guesswork,
              but as a structured mathematical and astronomical discipline. Our
              platform is powered by a proprietary, rule-based calculation engine
              designed to eliminate human bias, generic interpretations, and
              hallucinated predictions.
            </p>
            <p className="text-gray-200 leading-relaxed mt-3">
              Every insight delivered by Jyotishasha is the outcome of deterministic
              logic, precise astronomical computation, and classical Vedic
              principles.
            </p>
          </div>

          {/* Engine */}
          <div>
            <h2 className="text-2xl font-semibold text-indigo-200 mb-3">
              The Jyotishasha Calculation Engine
            </h2>
            <p className="text-gray-200 leading-relaxed mb-4">
              Unlike standard astrology apps that rely on approximate tables or static
              datasets, Jyotishasha operates on a deterministic logic model:
            </p>
            <ul className="list-disc list-inside text-gray-200 space-y-2">
              <li>
                <strong className="text-indigo-100">Precision Inputs:</strong>{" "}
                Every Kundali is generated strictly from the exact Date, Time, and
                Geographic Coordinates (Latitude & Longitude).
              </li>
              <li>
                <strong className="text-indigo-100">Repeatability:</strong>{" "}
                The same input always produces the same mathematical output, ensuring
                transparency and consistency.
              </li>
              <li>
                <strong className="text-indigo-100">Rule Integrity:</strong>{" "}
                No subjective overrides or manual adjustments are applied at any stage.
              </li>
            </ul>
            <p className="text-gray-200 leading-relaxed mt-4">
              This approach ensures results are verifiable, repeatable, and free
              from randomness.
            </p>
          </div>

          {/* Ephemeris */}
          <div>
            <h2 className="text-2xl font-semibold text-indigo-200 mb-3">
              High-Precision Astronomical Data (Ephemeris-Based Standards)
            </h2>
            <p className="text-gray-200 leading-relaxed mb-4">
              Planetary positions are calculated using Python-based astronomical
              libraries such as <strong>Swiss Ephemeris / PyEphem</strong>, which follow
              high-precision ephemeris standards referenced by NASA and leading
              astronomical institutions.
            </p>
            <ul className="list-disc list-inside text-gray-200 space-y-2">
              <li>Real-time computation of planetary longitudes, house cusps, and transits</li>
              <li>Mathematical astronomy calculations (not symbolic mappings)</li>
              <li>Arc-second level precision where applicable</li>
            </ul>
            <p className="text-gray-200 leading-relaxed mt-4">
              No approximations, shortcuts, or lookup-table astrology is used.
            </p>
          </div>

          {/* Standards */}
          <div>
            <h2 className="text-2xl font-semibold text-indigo-200 mb-3">
              Classical Standards & Ayanamsa
            </h2>
            <ul className="list-disc list-inside text-gray-200 space-y-2">
              <li>
                <strong className="text-indigo-100">Lahiri Ayanamsa (Chitra Paksha):</strong>{" "}
                Widely accepted and government-recognized standard in Indian Vedic astrology
              </li>
              <li>
                <strong className="text-indigo-100">Sidereal Zodiac System:</strong>{" "}
                aligned with actual celestial constellations
              </li>
              <li>
                <strong className="text-indigo-100">Localized Panchang logic:</strong>{" "}
                sunrise, sunset, Tithi, and Nakshatra calculations based on birthplace
              </li>
            </ul>
            <p className="text-gray-200 leading-relaxed mt-4">
              This ensures harmony between traditional Jyotish texts and modern
              astronomical accuracy.
            </p>
          </div>

          {/* Location */}
          <div>
            <h2 className="text-2xl font-semibold text-indigo-200 mb-3">
              Geographic Integrity via Google Places REST API
            </h2>
            <p className="text-gray-200 leading-relaxed mb-4">
              Small geographic inaccuracies can alter Lagna, Nakshatra Pada, and Dasha
              timelines. To prevent this:
            </p>
            <ul className="list-disc list-inside text-gray-200 space-y-2">
              <li>Jyotishasha uses the Google Places REST API for location validation</li>
              <li>Exact latitude–longitude coordinates are fetched instead of city-level approximations</li>
            </ul>
            <p className="text-gray-200 leading-relaxed mt-4">
              This precision is critical for accurate Lagna, house divisions, Moon
              position, Nakshatra, and Varga computations.
            </p>
          </div>

          {/* Interpretation */}
          <div>
            <h2 className="text-2xl font-semibold text-indigo-200 mb-3">
              Rule-Based Interpretation System (Non-Generative)
            </h2>
            <p className="text-gray-200 leading-relaxed mb-4">
              Jyotishasha does not rely on generic AI-generated astrology text.
            </p>
            <ul className="list-disc list-inside text-gray-200 space-y-2">
              <li>
                <strong className="text-indigo-100">Coded Vedic Logic:</strong>{" "}
                Thousands of classical Jyotish rules are encoded into a structured logic layer
              </li>
              <li>
                <strong className="text-indigo-100">Conditional Triggering:</strong>{" "}
                Interpretations appear only when relevant Yogas/Drishtis are mathematically present
              </li>
              <li>
                <strong className="text-indigo-100">Dynamic Construction:</strong>{" "}
                Every report is built from the individual Kundali — no copy-paste content
              </li>
            </ul>
            <p className="text-gray-200 leading-relaxed mt-4">
              This ensures interpretations remain contextual, justified, and chart-specific.
            </p>
          </div>

          {/* Trust */}
          <div>
            <h2 className="text-2xl font-semibold text-indigo-200 mb-3">
              Data Integrity & User Trust
            </h2>
            <ul className="list-disc list-inside text-gray-200 space-y-2">
              <li>
                <strong className="text-indigo-100">Privacy First:</strong>{" "}
                Birth details are used solely for astrological calculations and are not sold to third parties.
              </li>
              <li>
                <strong className="text-indigo-100">Transparency:</strong>{" "}
                Results are generated strictly from user-provided inputs, without hidden assumptions or manipulation.
              </li>
            </ul>
          </div>

          {/* Disclaimer */}
          <div className="rounded-2xl border border-indigo-400/30 bg-indigo-900/20 p-5">
            <h2 className="text-xl font-semibold text-indigo-200 mb-2">
              Accuracy, Limitations & Disclaimer
            </h2>
            <p className="text-gray-200 leading-relaxed">
              Astrological outcomes depend on the accuracy of birth data. Even minor
              variations in time or location may affect results. Jyotishasha insights are
              intended for guidance and self-understanding only and are not a substitute
              for professional medical, legal, or financial advice.
            </p>
          </div>

          {/* Summary */}
          <div>
            <h2 className="text-2xl font-semibold text-indigo-200 mb-3">In Summary</h2>
            <ul className="list-disc list-inside text-gray-200 space-y-2">
              <li>Ephemeris-based mathematical astronomy</li>
              <li>Classical Vedic rules encoded into deterministic logic</li>
              <li>Precise time and location validation</li>
            </ul>
          </div>

          {/* FAQ */}
          <div className="pt-2">
            <h2 className="text-2xl font-semibold text-indigo-200 mb-4">
              Technical FAQ: Understanding the Jyotishasha Engine
            </h2>

            <div className="space-y-3">
              {faqs.map((f, i) => (
                <details
                  key={i}
                  className="rounded-2xl border border-indigo-400/30 bg-white/5 hover:bg-white/10 transition"
                >
                  <summary className="cursor-pointer px-5 py-4 text-indigo-100 font-semibold">
                    {f.q}
                  </summary>
                  <div className="px-5 pb-4 text-gray-200 leading-relaxed">
                    {f.a}
                  </div>
                </details>
              ))}
            </div>

            <div className="mt-6 text-sm text-indigo-200/80">
              Want to generate your Kundali now?{" "}
              <a
                href="/free-kundali"
                className="underline hover:text-white"
              >
                Use Free Kundali Generator
              </a>
              .
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
